### ISSUE TITLE
[MICROGRANT] Rhada

### ISSUE THREAD

**Issue by jordaniza** [ipfs/devgrants#106]
### 1. What is your project? (max 100 words)

Rhada is building an application to help crypto-native organisations connect payment streams to real world events. We are initially focusing on DAOs looking to provide incentive structures for meaningful participation, by offering a way to start and stop payment streams based on whether members log meaningful activities that further the interests of the DAO.

[Check us out on Github](https://github.com/RhadaPay)

[Our HackFS Submission](https://showcase.ethglobal.co/hackfs2021/rhadapay)

### 2. How are you planning to improve this project? (max 200 words)

We are planning on building a working use case for real DAOs, using ourselves as guinea pigs. To do this, we need to connect our payment protocol, to meaningful events in the community space. Examples of events we are looking to track:

* GitHub PRs Merged
* Discord Activity
* Snapshot Votes Participation

Additionally, we relied upon a centralised API to handle tracking of events, before logging them to IPFS using Textile. We want now to research how that event log can be shared with users in a decentralised way, so that we can give DAOs access to their own data, stored on the IPFS network, without a centralised API as a single point of failure. 
 
### 3. Will the work be Open Source?

Yes

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
  
https://github.com/ipfs/community/blob/master/projects/Rhada.md

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 
Yes  

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
Yes
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

| Name              | Email                    | Github                        | Role          |
|-------------------|--------------------------|-------------------------------|---------------|
| Kevin Silvergold  | ksilvergold18@gmail.com  | https://github.com/k-agau     | Developer     |
| Levi Willms       | leviwillms@gmail.com     | https://github.com/leviwillms | Developer     |
| Franz Moca        | francesco.moca@gmail.com | https://github.com/franzmoca  | Developer     |
| Jordan Imran      | jordan.imran@predixa.ai  | https://github.com/jordaniza  | Developer     |
| Christian Koopman* | c.k.e.koopmann@gmail.com  | https://github.com/ckoopmann  | Developer     |
| Kit Blake*         | kitblake@infrae.com      | https://github.com/kitblake   | Community Mgr |

**New Members*

* If your project was created as part of an event or hackathon:
  * What was the name of the event?
  *Hack FS*
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.
  [Our HackFS Submission](https://showcase.ethglobal.co/hackfs2021/rhadapay)

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.

**Comment by SeedingTrees** [comment]
@Christian Koopman - Your email address shows as inactive.  You can drop your valid email address here or simply ask your team to forward you the email I sent with the next steps for funding.  

Cheers,

ST

**Comment by jordaniza** [comment]
@SeedingTrees, my mistake I missed out an n:

c.k.e.koopmann@gmail.com
