### ISSUE TITLE
[MICROGRANT] TrueBlocks

### ISSUE THREAD

**Issue by tjayrush** [ipfs/devgrants#109]
### 1. What is your project? (max 100 words)

TrueBlocks includes an indexing solution, Unchained Index, for any blockchain. We use IPFS and an Ethereum smart contract to produce, publish, and distribute the index in a way that is (a) reproducible, (b) uncapturable, (c) private by default, and (d) most importantly, very inexpensive.

Using IPFS, and without the user's intervention, the index is naturally and equitably distributed, as heavy users of the chain carry a heavier burden and lighter users of the chain carry a lighter burden.

Unlike other index providers, Unchained Index seeks to treat chain data as a "public good" by eliminating dependency on central gatekeepers, retaining immutability, and promoting cheap and widespread data access to the chain data.

https://github.com/TrueBlocks/trueblocks-core
  
https://showcase.ethglobal.com/hackfs/unchained-index

### 2. How are you planning to improve this project? (max 200 words)
Unchained Index leverages IPFS to broadly distribute the index of the chain data cheaply, securely, verifiably and decentrally. Currently, we use Pinata as a pinning services, however, we wish to explore the use of FileCoin as a pinning service.
 
### 3. Will the work be Open Source?
Yes. Fully.

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Yes.
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes.

### 6. Links and submissions
  
* Have you submitted to the IPFS Community Showcase ([instructions]

    Yes. PR is not yet merged. Here's the PR: https://github.com/ipfs/community/pull/659

* Have you added your project to the [IPFS Ecosystem Directory]

    Yes  

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

    We started this project as part of HackFS Summer 2020. Won one of the Pinata Prizes (https://mobile.twitter.com/ETHGlobal/status/1295786335538679809). HackFS link: https://showcase.ethglobal.com/hackfs/unchained-index

* Have you filled out the [Interplanetary Builder Feedback Survey]

    Yes
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

  - Thomas Jay Rush - [lead developer](https://github.com/tjayrush)
  - Dawid Szlachta - [full stack developer](https://github.com/dszlachta)
  - Matt Dodson - [documentation](https://github.com/MattDodsonEnglish)  
  - Meriam Zandi - [product manager](https://www.linkedin.com/in/meriam-zandi-6799661b1/)

* If your project was created as part of an event or hackathon, what was the name of the event?
  
  HackFS Summer 2020
  
* Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.

    https://showcase.ethglobal.com/hackfs/unchained-index

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.

**Comment by SeedingTrees** [comment]
Can you please reply with the email addresses for your team so that we can send instructions for receiving your payment?

**Comment by tjayrush** [comment]
That’s great. Thanks so much..

The email to send payments instructions is ***@***.*** ***@***.***>.

If possible, not necessary though, please cc ***@***.*** ***@***.***>

Thanks so much!

**Comment by SeedingTrees** [comment]
Thanks, Tjayrush.  It looks like Github blocked those email addresses.  Is the email address in your Github profile the right place to reach you?  If so, I can email you, and then you can add the rest of your team to that email chain.

**Comment by tjayrush** [comment]
Yes. That email address is valid. But, if you wish, you can change the word 'quickblocks' to 'trueblocks'. Either will get to me.

**Comment by SeedingTrees** [comment]
Got it, thanks.  I just sent you the email with the details for receiving the grant.
