### ISSUE TITLE
Mesh Services

### ISSUE THREAD

**Issue by olivernyc** [ipfs/devgrants#11]
### What do you work on? (max 100 words)
We are working on "mesh services" which will run on the NYC Mesh network and leverage its decentralized topology. For example, a chat app [1], message board, blogging platform [2], etc. The network spans over three hundred building rooftops across three boroughs and many neighborhoods of Manhattan. 

[1] https://github.com/georgeaf99/NYCMeshChatService
[2] https://github.com/olivernyc/static

### How are you planning to incorporate IPFS into your work? (max 250 words)
We think building on top of IPFS, or maybe a library like peerbase, will allow us to focus on designing great apps instead of wrangling with decentralized systems. The IPFS model is a natural fit with a lot of the services we intend to build. If we don't use IPFS, we will probably end up reimplementing a lot of the same concepts. We have also been discussing building some base infrastructure on the mesh, like servers running IPFS at various nodes across the city, which we hope to provide to the community as a nonprofit platform for deploying decentralized apps.

### Website(s) (CV, GitHub, personal page...)
https://github.com/olivernyc
https://github.com/georgeaf99
https://www.nycmesh.net

### Will the work be Open Source? (if not, explain why)
Yes

### Does your proposal comply with our Community Standards?
Yes

**Comment by parkan** [comment]
FYI Oliver and George presented about NYC Mesh and the chat prototype at the locol call in December https://github.com/ipfs/local-offline-collab/issues/25#issuecomment-567089862

**Comment by momack2** [comment]
Hey @olivernyc - this microgrant has been approved! I'll go ahead and start the process to issue NYC Mesh a one time grant of $1K for developer time, hosting services, relevant hardware, etc. Can you send your payment details to bills@protocol.ai?

Will early March be a good time to check in about how you'd like to share the results of your microgrant (like presenting at the weekly IPFS all hands or writing a short blog post)? We're excited to hear how it goes!

**Comment by olivernyc** [comment]
Thanks, we are so excited to get this up and running! I emailed bills@protocol.ai today with payment details. We should have something to show by early March. Happy to present at the IPFS all hands and write a blog post.

**Comment by momack2** [comment]
Awesome! Looks like slots in march are filling up so sign up soon! https://docs.google.com/spreadsheets/d/1XRB2QsPzCPLPOErKvDZfOKK3CMohI9t_QKNdztYMlK0/edit#gid=350755898

**Comment by parkan** [comment]
an update from George:

> We made some progress on the project: deployed a functional CLI based chat client, installed Raspberry PIs on the mesh, and used ansible to automatically provision the pi (w/ ipfs, ipfs cluster, etc.). I have put aside the project for now as I'm focusing on helping to get a mutual aid org off the ground in my neighborhood: https://bedstuystrong.com/. I would like to pick it up again once my responsibilities for the mutual aid org are lessened.

accordingly, we'll check back on the project in +1 month
