### ISSUE TITLE
Next Step Microgrant: Covision

### ISSUE THREAD

**Issue by Mr-Cryptocoder** [ipfs/devgrants#119]
### 1. What is your project? (max 100 words)
Most of the countries need to handle their own database due to lack of a decentralized platform. This leads to complications when global data is being compiled. Being a decentralized platform handled by behind the scene Smart Contracts and IPFS provides one global platform to report medical data.
Authenticity and quality of medical data is another issue when we are being faced with pandemics. With the proper use of IPFS technology Covision has been made such that only verified individuals/organisations can write data.

Covision is an ipfs based decentailsed platfrom being handled by behind the scene Smart Contracts which provides one global platform to report medical data. Authenticity and quality of medical data is another issue when we are being faced with pandemics. With the proper use of blockchain technology Covision has been made such that only verified individuals can write the data. Covision divides the medical data into initial reports and daily records, which is hashed using IPFS.

 https://github.com/Mr-Cryptocoder

![Screenshot 1](https://media.discordapp.net/attachments/873587956013752340/873588008325111868/img1.png)
![Screenshot 2](https://cdn.discordapp.com/attachments/873587956013752340/873588011340816444/img2.png)
![Screenshot 3](https://cdn.discordapp.com/attachments/873587956013752340/873588011948970044/img3.png)
![Screenshot 4](https://cdn.discordapp.com/attachments/873587956013752340/873588013463109702/img4.png)
![Screenshot 4](https://media.discordapp.net/attachments/873587956013752340/873587990205714462/img5.png)

### 2. How are you planning to improve this project? (max 200 words)
We will be trying to complete the project within the next 30 days and then try to document and deploy it to know the shortcomings. We will try to enhance the user interface and experience in the first week. In the second and third weeks, we will complete the backend and IPFS functionalities. In the fourth week, we will be testing our application for bugs and get ready for deployment.
### 3. Will the work be Open Source?
Yes, the project will be MIT licensed.

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Yes, I would agree to submit weekly reports and final grant report upon completion of the project.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions
  
* Have you submitted to the IPFS Community Showcase ([instructions]?
https://github.com/ipfs/community/blob/master/projects/Covision.md

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 
Yes
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
yes
  
### Additional questions:
*Team Members :

Sanil(Mr-Cryptocoder) - Blockchain Developer - https://github.com/Mr-Cryptocoder

**Comment by SeedingTrees** [comment]
Thank you for this application.  Since the prototype isn’t built yet, can you add an additional paragraph with more details on your software architecture?  Please include in that paragraph details on your IPFS pinning service.  If you have not yet picked a pinning service, we are happy to discuss this with you.

**Comment by Mr-Cryptocoder** [comment]
@SeedingTrees  Sure ! , Actually I almost completed the prototype , I have use ipfs-http-client with infura.io for file hashing

**Comment by Mr-Cryptocoder** [comment]
@SeedingTrees I have also added an additional paragraph.

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Please provide your email address so that we can send you the instructions for processing your payment. Let's then use your existing Community Discussion thread for updates.

**Comment by Mr-Cryptocoder** [comment]
@SeedingTrees Thank You , my email is sanildev21@gmail.com
