### ISSUE TITLE
[MICROGRANT] Flutter IPFS Plugin

### ISSUE THREAD

**Issue by hackyguru** [ipfs/devgrants#121]
### 1. What is your project? (max 100 words)
A plugin library for the IPFS using HTTP API and Infura. The code is implemented in Dart and the plugin can be imported and used in android application projects. Support for iOS and Windows will be added soon. Flutter is one of the rapidly growing cross-platform development frameworks. This plugin uses IPFS HTTP API along with Infura to easily store and retrieve strings, files and JSON objects on the IPFS.

   https://github.com/hackyguru/IPFS-Flutter

### 2. How are you planning to improve this project? (max 200 words)
I wish to make proper documentation for the flutter plugin that I've made. I wish to maintain the plugin over the course of time and make necessary updates and migrations when required.
 
### 3. Will the work be Open Source?
Yes.

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Yes.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes.

### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
https://github.com/ipfs/community/pull/631/

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? Yes
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: No, this project was developed independently.
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)?  Yes.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Kumaraguru T
	- Full stack web developer and blockchain enthusiast.
	- https://github.com/hackyguru/

Mridula Kalaiselvan
	- Front end developer
	- https://github.com/Mridula90/

* If your project was created as part of an event or hackathon: No
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
