### ISSUE TITLE
[MICROGRANT] IPNSGoServer

### ISSUE THREAD

**Issue by mrodriguez3313** [ipfs/devgrants#123]
### 1. What is your project? (max 100 words)

The current limitation for IPNS is that you can only create an IPNS record from the Go implementation of IPFS. The goal of my project is to create an API for developers to allow them to harness the power of IPNS from the browser. This is an amazing idea because we will generate & return keys to users, and they will use those to create, embed, and publish their data to IPNS! As an open-source tool, any developer will be able to easily use IPNS in their own dapps.

  [IPNSGoServer](https://github.com/mrodriguez3313/IPNSGoServer)

### 2. How are you planning to improve this project? (max 200 words)

The most immediate plan of action is getting the project to work as intended. The goal is to have two endpoints, getKey() & postKey(), where a user will request a key and SHA256 key pair will be returned (getKey()). Then postKey() will take that key and create an IPNS record and embed their public key in it.  Publishing can technically be done with either js-ipfs or go-ipfs, but for ease of use, we will offer that ability as well. With these things done, we can move onto the bigger picture plan.
The end goal will be to create an IPNS pinning service. Since records can be created with a certain time to live. We will have to conduct research/survey as for what would be the optimal time to keep alive before re-pinning, we would need to create a priority algorithm to re-pin records, and authentication for requests to ward off DDOS attacks and managing other requests. 
### 3. Will the work be Open Source?

Yes, MIT license
### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

 Yes
### 5. Does your proposal comply with our Community Code of Conduct?

Yes 
### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
  

 [Community Showcase](https://github.com/ipfs/community/pull/705)

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 
  Yes
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
 [Customizeable-nfts](https://showcase.ethglobal.com/web3jam/customizeable-nfts)
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
  Yes
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
 - Marco Rodriguez-Salinas, marco.rodriguez113@gmail.com, GitHub.com/mrodriguez3313, Lead Developer
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) 
Web3 Jam   
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.
  [Web3 Jame submission](https://showcase.ethglobal.com/web3jam/customizeable-nfts)

**Comment by SeedingTrees** [comment]
Can you please fill in the information for the members of this team, including names, email addresses, github account, and role in the project?  I would like to approve this application, but I need that information.  Please be sure to include at least one email address so that I can send the instructions for receiving payment.

**Comment by mrodriguez3313** [comment]
> Can you please fill in the information for the members of this team, including names, email addresses, github account, and role in the project? I would like to approve this application, but I need that information. Please be sure to include at least one email address so that I can send the instructions for receiving payment.

Sorry about that! At the moment I'm currently the only one apart of the team.

**Comment by SeedingTrees** [comment]
No problem.  Can you please provide your email address?

**Comment by mrodriguez3313** [comment]
> No problem. Can you please provide your email address?

Yes it's marco.rodriguez113@gmail.com. I also updated the Issue

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
