### ISSUE TITLE
[OPEN GRANT] Distributed pronunciation assistance in OmniLingo

### ISSUE THREAD

**Issue by ftyers** [ipfs/devgrants#124]
**Issuer:** Dietrich?
**Recipient:** @nlhowell @ftyers

## Project Description

Our successful transition of OmniLingo from completely centralised to
completely decentralised language resources for listening exercises, we want to
extend this to AI-based pronunciation assistance. This grant will allow us to
implement an IPFS-based voice sample contribution system which can be used to
train an artificial pronunciation coach. Using the flexible and high-performing
IPFS storage layer will enable full duplex decentralisation, with users
self-hosting their contributions, promoting their data sovereignty.

### Background

We are building a language-learning app for language communities
that are either unsupported by major platforms or do not wish
to give up sovereignty over their languages. Centralised language-learning
systems privately collect user data and audio samples, trapping communities
into proprietary silos and walled gardens. With the popularisation of open
content licences and the innovation of new accessible distributed storage
systems, we can build language-learning for the decentralised web.

Our design is decentralised from the beginning, with common resources
accessible through a robust simple protocol amenable to offline, http-based, or
peer-to-peer access; user settings stored in one or more persistent stores of
the user's choice; and clients offering users maximum sovereignty over who has
their data.

## Value

Language learning resources is an embarrassingly distributable system, and is an
opportunity to expose the large population of language learners to the
distributed web. Extending this to pronunciation assistance will give OmniLingo
best-in-class features for learners of all languages, and self-hosting through
the decentralised web supports these learners and communities.

## Deliverables

1. Demo for IPFS-based distributed language learner voice sample contribution and storage
1. Protocol and toolkit for IPNS-based user sovereignty policy for user control of data
1. Protocol and toolkit for pronunciation assistance using models stored on IPFS
1. Demo of pronunciation assistant integrated into OmniLingo
1. Post about the project for the IPFS blog
1. Scientific article describing our success published in workshop proceedings and/or on arxiv.

## Team

* @ftyers, @nlhowell - Grant recipients. Computational linguists with
  familiarity with multilingualism and experience in distributed computing and
  speech processing
* Dietrich Ayala - PL Grant advisor

## Milestones & Funding

**Total Funding Amount:** $25,000

Week | Milestone | Cost
---- | --------- | ----
   1 |  voice sample contrib demo | $3125
   2 |  voice sample contrib demo | $3125
   3 |  user sovereignty toolkit  | $3125
   4 |  user sovereignty demo     | $3125
   5 |  demo contrib webapp       | $3125
   6 |  pron. assistant toolkit   | $3125
   7 |  pron. assistant demo      | $3125
   8 |  paper and blog post       | $3125

## Resources

* Omnilingo: https://omnilingo.github.io, https://demo.omnilingo.cc
* A centralised language learning system: https://duolingo.com
* A research project using AI pronunciation feedback:
  https://papareo.nz/docs/PapaReo_NeurIPS2020_Poster.pdf

## Support and Funding

This grant is funded by Protocol Labs.

**Comment by realChainLife** [comment]
Hi @ftyers thank you for this proposal. We would like to fund the work outlined here. Please email devgrants@fil.org to discuss next steps.

**Comment by ftyers** [comment]
Updates 30/03/2023:
- To solve the browser connection issues (e.g. with preload nodes), we switched to kubo-rpc after js-ipfs was deprecated and while waiting for WebTransport to get deployed. This was really easy, a few lines of code and all of the rest of the API didn't need changing.
- The voice sample contribution demo is completed, clips can be recorded and uploaded to IPFS
- The pronunciation toolkit and web demo is completed, models and clips on IPFS, model runs in the browser.
