### ISSUE TITLE
[OPEN GRANT] DeAI - IPFS based Web3 SaaS Platform for Public AI

### ISSUE THREAD

**Issue by DeAINet** [ipfs/devgrants#125]
## Project Description

The DeAI project aims to deliver a fully decentralized artificial intelligence (AI) service network with highly scalable, crypto token incentivized and results in a solution that can serve as the application interface (API) layer in the decentralized development (web3) stack. We present solutions for incentivizing AI nodes for maximum usage of idle resources and distributing AI services for higher availability and security.  This grant will allow us to implement an IPFS-based AI algorithm storage system that can not only be used to execute on decentralized servers but also used to create DeAI Algorithm NFT. All the AI pretrained weight files and source code will be deployed on IPFS as well as Algorithm NFT. 

### **Background**

DeAI team is devoted for constructing a fully decentralized network to provide AI services for developers. We
propose a novel concept which is decentralized API (DeAPI) to deliver a Web3.0 SaaS solution, which has no centralized node for API deployment. In our design, DeAI protocol will be interactive with four roles: 

1). **AI users** as well as **App/Dapp Developers** send the input information such as images or text to the DeAI network and get response from DeAPIs. 

2). **AI miners** execute DeAPI on their hardware which reply AI users with DeResponse by doing inference on corresponding AI model. 

3). **AI inventors** who submit AI algorithm APIs to deploy on DeAINet.

4). **Token Holders** who stake their token to miners for DPoS consensus to earn incentive. 

## Value

The reliable miners execute all DeAPIs in 7x24 beyond DPoS consensus to guarantee that DeAINet has the following rich values:

* Protect the privacy of AI users by executing encryption protocol transparently. 
* Improve the security for AI system by miners’ DPoS consensus. 
* Strengthen robustness for AI service by DeAPI runtime redundancy of miners. 
* Save energy and reduce the service cost by making use of spare resources to mine. 
* Protect AI intellectual properties by algorithm NFTs which will be detailed refer to our PitchDeck for more detail.

## Deliverables

1. Demo for IPFS-based distributed algorithm and deep learning pretrained models on IPFS storage.
2. Demo for IPFS-based Algorithm NFT mint. 
3. Demo for peer-to-peer decentralized APIs. 

## Team

@DeAINet
- Laekshan: Software Engineer in world-leading company with 4 years crypto experience
- Nael Hailemariam: Co-founder and GM at Chapa.co. Ex Software Engineer in world leading company.
- Israel Goytom: Founder, CTO of Chapa.co, Colimo City. AI Researcher in Google Brain, MILA of Turing Award Winner Yoshua Bengio Lab.
- Dikshan Kharel: Researcher in Innovation Factory. Blockchain Developer.
- Rocky Yang: Presidential AI Postdoctoral Fellow in NTU. Chief Scientist in Singapore Smart City Project. AI Researcher of UCB. Visiting Lecture Professor of NTU, NUS

## Milestones & Funding

**Total Funding Amount:** $20,000

| Week    | Milestone                      | Cost  |
| ------- | ------------------------------ | ----- |
| 2021 Q4 | Functional Demo                | $2000 |
| 2022 Q1 | DeAPI Standard NFT Marketplace | $2000 |
| 2022 Q2 | DeAI Protocol, Miner Network   | $2000 |
| 2022 Q3 | User Network, Main Net         | $2000 |
| 2022 Q4 | Ecosystem Development          | $2000 |
| 2023 Q1 | DeAI 2.0                       | $10000 |
|         |                                |       |

## Resources

- PitchDeck: https://www.deainet.io/file/PitchDeck_DeAI.pdf
- DeAI Website: https://deainet.io
- Algorithm NFT Demo: https://deainet.io/non-api-nft

**Comment by realChainLife** [comment]
Hi @DeAINet thank you for this proposal. We would like to fund the work outlined here. Please email devgrants@fil.org to discuss next steps.
