### ISSUE TITLE
[MICROGRANT] ETH My Song

### ISSUE THREAD

**Issue by shivani7q** [ipfs/devgrants#126]
### 1. What is your project? (max 100 words)

Project - https://ethmysong.vercel.app/

This dapp aims to makes it easy for Independent artists to raise funds for their compositions. This dapp can be perceived as a combination of SoundCloud + Kickstarter. Our dApp allows peer-to-peer tipping without any cuts, hence allowing artist fans to directly fund their favorite artists' music. Like SoundCloud, artists/users can directly upload their music composition on the platform, but by signing the smart contract to upload it and it would be live on the platform. 

Then listeners can listen to the audio and if they want to support, they can tip the artist.

GitHub Repository - https://github.com/shivani7q/ETH_my_Song
  

Demo Video - https://www.youtube.com/watch?v=U_RKD7fRYJE

Vercel Deployed Dapp prototype - https://ethmysong.vercel.app/

### 2. How are you planning to improve this project? (max 200 words)

- We need to improve the UI/UX of the dapp - that would be our prime focus.
- We want to make an authentication system to authenticate original artists/owners of music file.
- Enabling tip deposits in ETH, BTC, MATIC, SOL and AVAX instead of Mumbai Matic testnet (as it's currently)
- Spam removal techniques - still brainstorming 
- Bringing artists profile pages to tip directly
- Reaching out to artists and onboarding them on the platform (dapp). Encouraging them to spread the word in the music community and their peers.
- Marketing on Social Media channels, making illustrations and videos.
- onboarding more members as the dapp scales
 
### 3. Will the work be Open Source?

Yes our work is open source and licensed under the MIT license. 

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

Yes, I agree to submit weekly/bi-weekly reports and final grant report upon completion of the project.
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions

* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
  
Yes, here's the link - https://github.com/ipfs/community/blob/master/projects/ETHmySong.md

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 
Yes
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes, here's the link - https://devfolio.co/submissions/eth-my-song-3f8f

* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
Yes, I have.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

> **Shivani Singh**, beginner Blockchain developer, published writer on Kindle, marketing enthusiast.
> Role in the project - Suggested the idea, made the smart contracts and made the demo video 
> Current Role - Student, KNC-University of Delhi | Part Time Project Manager 
> Email - shivani7q@gmail.com
> Github - https://github.com/shivani7q
> 
> **Karan Singh**, _Spotify India Featured Indie artist_, blockchain and game developer, Sales and distribution experience
> Role in the project - frontend + backend
> Github - https://github.com/krn17
> Email - karan7q@gmail.com

* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
**Polygon India BUIDLit Hackathon** 

 * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.
 - Link to the hackathon submission - https://devfolio.co/submissions/eth-my-song-3f8f

**Comment by shivani7q** [comment]
@realChainLife can you please review my submission? Noticed you assigned the last submission to yourself for reviewing therefore thought to tag you.

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
