### ISSUE TITLE
[MICROGRANT] Blockchain Ticketing

### ISSUE THREAD

**Issue by eerkaijun** [ipfs/devgrants#127]
### 1. What is your project? (max 100 words)

A decentralised ticketing marketplace with three core features:
1. Use of smart contract to regulate the secondary market - currently popular events often end up with high ticket resale price
2. Each ticket is represented as an NFT - elimininate tickets fraud and ticket could become collectible at the end of event
3. Pre-event financing option - often times event organisers struggle to obtain loan from centralised institutions, our platform offer a decentralised method to raise loan from individual investors

The application uses IPFS. Event and ticket details are stored on IPFS to reduce on chain cost. 

[Link to Github Repo](https://github.com/eerkaijun/tixlab)
  

### 2. How are you planning to improve this project? (max 200 words)

We would like to carry beta testing on our prototype in preparation for a launch. As such, we are looking to redesign the user interface to ensure a good user experience. The areas that we are planning to work on: 
1. Streamline the event organisers flow in creating events
2. Streamline the ticket buyers flow in browsing and purchasing tickets for events 
3. Tickets verification at event entrance (physical and virtual events)

On the other hand, we think that tickets could become NFT collectible at the end of an event. In order for the NFT and its corresponding metadata to be permanent, we need to have persistent storage for the NFTs. Therefore, we are looking to migrate from IPFS to NFT.storage. 

We are requesting grant to support the above development work. 
 
### 3. Will the work be Open Source?

Yes

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
  

[Link to Community Showcase](https://github.com/ipfs/community/pull/721)

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 

Yes
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

Yes, the project is for NFT Hack by Filecoin and Encode Club. Submission link [here](https://www.youtube.com/watch?v=GKkhje97x68).
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 

Yes
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  * Kai Jun Eer (kaijuneer@gmail.com), [Github](https://github.com/eerkaijun), Smart contract developer
  * Maria Maliarets (marie0901@gmail.com), [Github](https://github.com/marie0901), Front end developer
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
    * NFT Hack by Filecoin and Encode Club
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.
    * [Submission](https://www.youtube.com/watch?v=GKkhje97x68)
    * [Finale Pitch](https://www.youtube.com/watch?v=b9vErLt_cyA)

**Comment by mishmosh** [comment]
Hi @eerkaijun — for migrating to Filecoin you probably want to use [NFT.storage](https://nft.storage). It's a service built by Protocol Labs that lets you write to both IPFS nodes and Filecoin storage providers in a single API call — free and super simple to use.

If you have any questions about it, the team is in the #nft-storage channel on the IPFS Discord: https://discord.com/channels/806902334369824788/831502708082081822

**Comment by eerkaijun** [comment]
Hi @mishmosh, thanks for the suggestion! I've checked it out and it suits us well! I have edited the proposal. 

For the grant application, what is the expected timeline and process?

**Comment by mishmosh** [comment]
Microgrant applications are reviewed weekly, so you should hear back from
the team this week.

**Comment by eerkaijun** [comment]
Hi @mishmosh, just as a follow up on the status of the grant application review.

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
