### ISSUE TITLE
[MICROGRANT] Phi

### ISSUE THREAD

**Issue by robin-thomas** [ipfs/devgrants#128]
### 1. What is your project? (max 100 words)

Phi is a decentralized, secure, end-to-end encrypted chat engine built on blockchain & IPFS.

Once logged in, you can update your profile details like name, about, and profile picture. If those are missing, *John Doe* and *Available* shall be used as the name and about respectively. Profile pictures are hosted on IPFS using Textile buckets. Profile information is stored using Ceramic Protocol (previously 3Box).

You can send chat requests to Ethereum addresses. Once they approve, they become your friends. You can then share text messages and image attachments securely with end-to-end encryption.

<https://github.com/robin-thomas/phi>
  

<http://connect-phi.vercel.app/>
<https://www.youtube.com/watch?v=EtiIS4ZcLHE&feature=emb_imp_woyt>

### 2. How are you planning to improve this project? (max 200 words)

 
* Improve the UI/UX of the dapp, like:
  * Basic UI/UX improvements and performance improvements
  * Notifications when new chat messages come in
  * Re-order the friend list based on the last chat activity
* Emoji support for chats (encrypted)
* Support more wallet based logins (currently supports only Metamask)

### 3. Will the work be Open Source?

Code is already under [MIT License](https://github.com/robin-thomas/phi/blob/main/LICENSE).

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

Yes.

### 5. Does your proposal comply with our Community Code of Conduct?

Yes.

### 6. Links and submissions

  
* *Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?*
  
  **<https://github.com/ipfs/community/pull/718>**

* *Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)?* 
**Yes.**

* *If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:*
**<https://devpost.com/software/phi-wi8deq>**

* *Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)?*
**Yes.** 

### Additional questions:
* *For each team member(s), please list name, email, Github account, and role in the project.*
**Robin Thomas, robinthomas2591@gmail.com, [GitHub](https://github.com/robin-thomas), Developer**

* *If your project was created as part of an event or hackathon:*
  * *What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)*
  **Chainlink Fall hackathon 2021**

  * *Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.*
  **<https://devpost.com/software/phi-wi8deq>**

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
