### ISSUE TITLE
[MICROGRANT] Lifefram

### ISSUE THREAD

**Issue by melwong** [ipfs/devgrants#133]
### 1. What is your project? (max 100 words)
Wikipedia rejects biography of non-notable people while 160,000 non-notable people die every day. Is death the end of us as we know it? Thus, we're building a global decentralized database to store records of the deceased for 300 years and beyond. We're currently using nft.storage.

The reason we're doing this is because knowledge should last forever, including the knowledge of us. It is also from the past that we learn about the present and future and to understand mankind and our world. 

https://github.com/lifefram/lf/
  

https://lifefram.org

### 2. How are you planning to improve this project? (max 200 words)

* Host our own IPFS nodes and to push our files (biographies containing text and images) to these nodes. Having our own nodes ensure we can always easily access our data. We aim to host these nodes at different geographical locations independent of data storage facility providers.
* Deploy our dapp on cloud server like AWS. It currently sits on a shared hosting server (Linux) with very limited hardware resources.  
* Curate existing biographies of the deceased from partners such as funeral homes and newspapers.
* Improve on UI/UX of our dapp.
 
### 3. Will the work be Open Source?

Our code is GPL licensed and our content (like biographies) is licensed under CC-BY-SA 3.0

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

Yes, absolutely. Our team has the experience of receiving two grants some years ago and understands the procedures in grants. 
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes, indeed.

### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
  
Yes

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 
Yes
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
Yes
 
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Melvin Wong, melvinwonghc at gmail period com, developer
Pedro Machado, pedromachado at orange period fr, blockchain server architect
Shin Gahee, shingahe7273 at gmail period com, publicist cum content curator

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  We won the grand prize of Babylon 2.0 Hackathon. Then, the project was called Peopedia. Here's the winning video - https://youtu.be/Vt1jKClfdtA?t=132
  
  * Please link to your hackathon submission
  https://youtu.be/NaxODG2_XzY

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
