### ISSUE TITLE
[MICROGRANT] Creativerse - Minecraft on Ethereum

### ISSUE THREAD

**Issue by CreativerseMC** [ipfs/devgrants#134]
### 1. What is your project? (max 100 words)
A truly decentralized Minecraft protocol where you own plots of land as NFTs, and each NFT stores the block data of that plot. This allows anyone to run a Creativerse server, enabling it to be a truly decentralized server.

https://github.com/CreativerseMC/CreativerseMC-Plugin
  
https://CreativerseMC.com
https://showcase.ethglobal.com/nfthack2022/creativerse-minecraft-on-ethereum

### 2. How are you planning to improve this project? (max 200 words)
As a beginner Java developer, I want to hire some other more experienced Java developers on my team to both optimize the codebase (things freeze a lot as of right now) and add extra features to the protocol, like saving biomes, weather, and music in a plot.
 
### 3. Will the work be Open Source?
Yes, MIT license

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Absolutely, everything about this project is open source, transparent and public
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
https://github.com/ipfs/community/pull/741

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? Yes
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: https://showcase.ethglobal.com/nfthack2022/creativerse-minecraft-on-ethereum
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)?  Yes
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
phaze jeff, https://github.com/phazjeff, developer

* If your project was created as part of an event or hackathon:
  * What was the name of the event? EthGlobal NFTHack 2022
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize. https://showcase.ethglobal.com/nfthack2022/creativerse-minecraft-on-ethereum

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.

**Comment by SeedingTrees** [comment]
Hi, @CreativerseMC - I am trying to approve this microgrant but it looks like you did not include you email address in the application.  We need your email address so that we can send the payment details to you.  I also noticed that your personal Github account seems to no longer be active.  Can you please provide your email address so that we can approve this microgrant?

**Comment by CreativerseMC** [comment]
Sorry about that @SeedingTrees, you can email me at phazejeff@protonmail.com
