### ISSUE TITLE
[MICROGRANT] realityDapp

### ISSUE THREAD

**Issue by Josiassejod1** [ipfs/devgrants#136]
### 1. What is your project? (max 100 words)

Reality Dapp is a project that allows you to purchase real estate using NFTS, IPFS.

  https://github.com/Josiassejod1/realityDapp

[showcase.ethglobal.com/nfthack2022/reality-dapp](https://showcase.ethglobal.com/nfthack2022/reality-dapp)

### 2. How are you planning to improve this project? (max 200 words)

I already have a fleshed out mockup for the designs. The next part is perfecting the flow in order to handle auctions using ThirdWeb3 and then handling how IPFS upload works on the backend for the Lenders on the platform
 
### 3. Will the work be Open Source?

Won't be open source
### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

I would provide updated on a weekly basis
  
### 5. Does your proposal comply with our Community Code of Conduct?

It follows the guidelines 

### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
  

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 
Yes
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
Yes
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  ETHGlobal NFTHack
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.
[showcase.ethglobal.com/nfthack2022/reality-dapp](https://showcase.ethglobal.com/nfthack2022/reality-dapp)

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
