### ISSUE TITLE
[Microgrant] NetSepio

### ISSUE THREAD

**Issue by Shachindra** [ipfs/devgrants#137]
### 1. What is your project? (max 100 words)
NetSepio aims to provide a safe and secure internet browsing experience through Data Democratization to empower individuals & companies to use this data in their decision making. We're building browser extensions, mobile and web apps to give users insights on the safe and harmful websites they browse and report the websites for having unsafe content.

[GitHub Repo](https://github.com/NetSepio/ChromiumExtension)
  
[Website](https://netsepio.com/)

### 2. How are you planning to improve this project? (max 200 words)

- Review Websites across various categories
- Support for more categories
- Web Archives on IPFS for every review submitted
- Improve the UI/UX of the App
- Marketing & Beta Launch
- Onboard more developers

[Project Plan](https://docs.google.com/document/d/1WONWyGu5Jh6YaDsZoAWS-mmMtJ2PGf8nwxgmo2WlhrQ)
[Figma](https://www.figma.com/file/jpxJmJLJxSWWxMvDS5oGEb/NetSepio)
[Roadmap](https://docs.google.com/presentation/d/17vIUpHeoJaAirWERiqzriGia5CbmyrA0/edit#slide=id.gcf8e05e63e_0_6) 

### 3. Will the work be Open Source?
Yes. Our code is open source and licensed under the MIT License.

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Yes, For sure. We'll also release a weekly newsletter.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes.

### 6. Links and submissions
  
* Have you submitted to the IPFS Community Showcase ([instructions]
Yes. Link - https://github.com/ipfs/community/pull/743

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 
Yes
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  Yes. Link: https://devpost.com/software/netsepio

* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
  Yes
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Shachindra - shachindra [at] netsepio [dot] com, Blockchain Developer
Om More - ommore [at] netsepio [dot] com, Backend Developer
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  Browsers 3000 - [Demo Video](https://youtu.be/os3CJNFsl7c)
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.
  https://devpost.com/software/netsepio

**Comment by ErinOCon** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
