### ISSUE TITLE
[MICROGRANT] Prānah - ebook NFT Marketplace

### ISSUE THREAD

**Issue by RichuAK** [ipfs/devgrants#141]
### 1. What is your project? (max 100 words)

An eBay-like marketplace for ebooks, where each ebook is represented by NFTs. As unique entities, each copy becomes a user's property, similar to how physical books behave. Reselling, renting etc are made possible, and readers can read and collect special editions and signed copies, in addition to cheaper used ebook copies. Authors and publishers get royalties on any subsequent purchase of a given copy (in addition to the primary sales revenue), with the potential of huge bonanza on rare collectibles being auctioned off.  

GitHub : https://github.com/pranah/DBM-client
  
Website: www.pranah.co

### 2. How are you planning to improve this project? (max 200 words)
1. Development of clear and appealing web app front end. 
2. Design and development of safe and secure smart contracts.
3. Development of iOS and Android apps.
4. Travelling to book fairs and conferences to introduce and promote the project among book readers and crypto enthusiasts.

### 3. Will the work be Open Source?

Yes.

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

Yes
One aspect we have troubled with is masking the CID from end users: how to give access to a particular CID to a user at time t, and then revoke access from the same user at time t+n, based on contract logic. We would love to work on this and figure it out.
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
  

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

https://showcase.ethglobal.com/web3jam/pranah-web3

  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Richu A Kuttikattu - richuakuttikattu@gmail.com, GitHub.com/richuak, smart contract developer/project manager
Mansoor Othupurrayil - opmansoor7@gmail.com , https://github.com/mansoorop, Blockchain Engineer/Operations Manager
Aiswarya Walter - aiswaryawalter@gmail.com, https://github.com/aiswaryawalter, Protocol Engineer/Community Manager
Arjun Vinod - arjunvnd@gmail.com, https://github.com/arjunvnd, React Developer
Anandu S - anandu97@gmail.com, https://github.com/anandu97, React Lead
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.
  
  https://showcase.ethglobal.com/web3jam/pranah-web3

**Comment by ErinOCon** [comment]
Hi @RichuAK, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.
