### ISSUE TITLE
[MICROGRANT] SmartCOOP

### ISSUE THREAD

**Issue by ilijapet** [ipfs/devgrants#144]
### 1. What is your project? (max 100 words)

With this project we try to assess possibilities coming out from blockchain world to address some of the most pressing challenges small agricultural producers confront. 

### 1) Problem statement

Small agricultural producers don't have enough capacity to be effectively present on market as individual producer. That is why they have two basic options. First to organize themselves in traditional cooperatives in order to improve their negotiation position with bigger corporate buyers or to sell as individual producers to big corporations under conditions often not so favorable to them. Both solutions have some drawbacks associated with them. Big corporation tend to offer price to induvial producers which is basically less then average season price for raw small fruits and they pay them at the end of season. Additionally, there is a counterparty risk involved. Corporations can delay or entirely avoid their obligation to pay producers. On the other hand if they organize themselves in form of more traditional cooperatives there is counterparty risk of mismanagement of cooperative funds or collected goods, high managing cost for running traditional cooperative and low overall management efficiency often associated with this type of organizational structure.

### 2) Some of potential benefits from introducing blockchain technology and smart contracts to the field o agricultural cooperatives

<br>

- Get real time market price on the day of selling and not lowest average season price
- Cut different contraparty risks (corporative and cooperative one)
- Cost effective way to manage cooperative
- Increased number of possible buyers. In the blockchain world you don't need to know or trust buyers or to have already developed relations with them to be able to effectively do business with them. This can drastically increases the number of potential business partners (cooperation links) and lower legal and logistical cost of doing business.

https://github.com/ilijapet/smartCOOP2.0_react_version

https://muddy-art-3856.on.fleek.co/

Screencast
https://www.youtube.com/watch?v=Y9qr7ybG-lA

### 2. How are you planning to improve this project? (max 200 words)

Re-factor my smart contract: improve existing contract code, integrate DAO component with ERC20 COOP tokens, move from web3.js to ethers.js, re-design React front-end. 
 
### 3. Will the work be Open Source?

Yes

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?

https://github.com/ipfs/community/pull/736#issuecomment-1076814928

https://github.com/ipfs/community/discussions/735

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 

Yes I submit
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

No
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 

Yes
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Ilija Petronijevic
ilijapet@gmail.com
https://github.com/ilijapet
Developer

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  
Yes this project is result of ConsenSys academy bootcamp.

  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.

**Comment by ErinOCon** [comment]
Hi @ilijapet , Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by ErinOCon** [comment]
Hi @ilijapet, This microgrant has been approved! Look out for an email to submit payment details.
