### ISSUE TITLE
[MICROGRANT] Auction House

### ISSUE THREAD

**Issue by lmedury** [ipfs/devgrants#145]
### 1. What is your project? (max 100 words)

Auction House is a fully decentralized, and customized NFT Auction Marketplace. It is built using Ethereum Smart Contracts and leverages Rarible Protocol and IPFS for decentralized storage of media (images) and NFT metadata.
https://github.com/lmedury/auctionhouse
https://lmedury.github.io/auctionhouse/
### 2. How are you planning to improve this project? (max 200 words)
    In terms of UI/UX:
        Use mobile-friendly and responsive design
        Dark mode

    Technical Side:
        Performance improvements, including building a backend for loading NFT information for faster lookup
        Analytics and dashboard component to search by wallet address
        Building user engagement by enabling reactions and comments to NFTs

### 3. Will the work be Open Source?
Yes

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions

* Have you submitted to the IPFS Community Showcase 
**https://github.com/ipfs/community/pull/686/commits**
* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)?
  **Yes**
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
**Yes, and this project also won a sponsor prize by Filecoin: https://devpost.com/software/auction-house**
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
**Yes**
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
**Only one team member**:
    Name: Lalith Medury
    Email: lalith.aakash970@gmail.com
    Github Account: https://github.com/lmedury
    Role: Building Smart Contracts, and a full start developer
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  **NFT Vision Hack**
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.
  **https://devpost.com/software/auction-house**

**Comment by ErinOCon** [comment]
Hi @lmedury, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by ErinOCon** [comment]
Hi @lmedury, This microgrant has been approved! We recommend checking out [NFT.storage](https://nft.storage/) for this project. Look out for an email to submit payment details.

**Comment by lmedury** [comment]
Thank you so much! Will definitely check out NFT.storage.
