### ISSUE TITLE
Next Step Microgrant: Statistical Data Viewer on IPFS

### ISSUE THREAD

**Issue by noryev** [ipfs/devgrants#146]
# Statistical Data Viewer on IPFS

### 1. What is your project? (max 100 words)

We are building a web-app to save and monitor your data via IPFS. Our program scans your IPFS cache folder to show a detailed summary of what is stored on your IPFS node. The data will be visualized using organized colorful graphics similar to apps like Windirstat, Spacesniffer, or Disk Recon. Each file type (MP3, ZIP, EXE, JPEG, etc.) is assigned a color in a collage of rectangles that are sized depending on how much space that file type is using. 

Project were building off of: http://galerielestudio.com
Project Github: https://github.com/galaxyxone/glsx_live2.2
Company Github: https://github.com/galaxyone

### 2. How are you planning to improve this project? (max 200 words)

Add more features and improving the data monitoring capabilities of our CID Management tool. With our easy to use statistical data visualization tool, users will have a better way to understand the statistics of the data they save on IPFS. We are using the JS-IPFS HTTP API's to do the communication to our web-app. The better we get with IPFS, the more we can certainly build. 

### 3. Will the work be Open Source?

- Yes

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

- Yes

### 5. Does your proposal comply with our Community Standards?

- Yes

### 6. Links and submissions
- https://github.com/ipfs/community/blob/master/projects/CID-Management-Webapp.md
### Additional Questions: For each team members, please list name, Github Account, and role in the project. 
- Logan Lentz - Email: llentz@galaxyx.io, Github: github.com/noryev, Lead Full Stack Dev/Project Manager
- Alex Mirran - Email: amirran@galaxyx.io, Github: github.com/galaxytwo, Junior Dev/Project Manager
- Giorgio Fasoli- Email: gfasoli@galaxyx.io, Github: github.com/galaxythree, Graphic Design/Documentation

**Comment by ErinOCon** [comment]
Hi @noryev , Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by noryev** [comment]
Thanks so much!

**Comment by ErinOCon** [comment]
Hi @noryev , This microgrant has been approved! Look out for an email to submit payment details.

**Comment by ErinOCon** [comment]
Hi @noryev, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!

**Comment by noryev** [comment]
Done. Thanks so much!

**Comment by ErinOCon** [comment]
Hi @noryev, thank you for the submitted report! Can you point to where I can review the code that was built during the time of this grant? I didn't find updates in the linked repo.

**Comment by noryev** [comment]
Ahh so sorry! I have multiple repo's for the different versions(builds) and I must have sent you the wrong one... I need to organize the builds in one repo- my apologies! [this](https://github.com/galaxyxone/ipfsStatViewerChrome) repo has the additions in association to this grant.
