### ISSUE TITLE
[MICROGRANT] IPFS Scan

### ISSUE THREAD

**Issue by badkk** [ipfs/devgrants#147]
### 1. What is your project? (max 100 words)
IPFS Scan shows the file's(CID) storage status on IPFS Network, including gelocation information and incentive layers'(Crust/Filecoin/Arweave) on-chain storage state.
https://github.com/crustio/ipfsscan
https://ipfs-scan.io/

### 2. How are you planning to improve this project? (max 200 words)

1. Support show more WRITEABLE gateways beyond Crust ecosystem
2. Support more incentive layers storage status, like Filecoin/Arweave/Storj/etc.
 
### 3. Will the work be Open Source?
Yes

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions
  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
https://github.com/ipfs/community/pull/699

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 
Yes.

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
No.  

* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
Yes  

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Name: Luke Fan
Email: [kun@crust.network](mailto:kun@crust.network)
Github Account: https://github.com/badkk
Role: Full stack & Blockchain developer

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.

**Comment by ErinOCon** [comment]
Hi @badkk , Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by badkk** [comment]
> Hi @badkk , Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

tysm!

**Comment by ErinOCon** [comment]
Hi @badkk, can you build out the ReadMe for this project? This will support future reviews of this work. I am pleased to inform you that this grant has been approved! Look out for an email to submit payment details.

**Comment by badkk** [comment]
> Hi @badkk, can you build out the ReadMe for this project? This will support future reviews of this work. I am pleased to inform you that this grant has been approved! Look out for an email to submit payment details.
> 
> 

Thank you so much! We'll build it ASAP
