### ISSUE TITLE
[MICROGRANT] Sytime

### ISSUE THREAD

**Issue by poolsar42** [ipfs/devgrants#148]
### 1. What is your project? (max 100 words)

Sytime is decentralised chat application. 
Users can connect to our DApp with their Ethereum wallet, with an extension like Metamask.
Sytime allows users to create and edit personal accounts on the Ceramic platform leveraging decentralized identity
and user data sovereignty to interact with other users in a chat.
Users can also chat with others in different rooms and view the history of each room as well as send pictures to chat.
The list of rooms is also stored as part of the ceramic profile so users can keep their chat history handy in different browser sessions.

I have intention to make it electron-app in the near future.

  https://github.com/ThirdRockEngineering/Sytime
https://sparkling-morning-4135.on.fleek.co/
### 2. How are you planning to improve this project? (max 200 words)

  add encryption
 make it more customisable (ui/ux, ipfs config) 
 Make it as a desktop client as well. It'll be most preferable to use it as a desktop app actually. Because all history will be stored on the client's side.
### 3. Will the work be Open Source?

Of course!
### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

  Yes. I actually want to do so.
### 5. Does your proposal comply with our Community Code of Conduct?

Done 👍 
### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
  
https://github.com/ipfs/community/commit/d7dbeb162962d551f95e3f0f7631d1d931802816
* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 
  yes
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://showcase.ethglobal.com/web3jam/sytime
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
  Yes
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
(poolsar.42@gmail.com) poolsar42, Emil - lead;
 fjohngomez, Freddy - most valuable employee
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  ETHGlobal Web3 Jam
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.
https://showcase.ethglobal.com/web3jam/sytime

**Comment by ErinOCon** [comment]
Hi @poolsar42, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by ErinOCon** [comment]
Hi @poolsar42, This microgrant has been approved! Look out for an email to submit payment details.
