### ISSUE TITLE
[MICROGRANT] DExplorer

### ISSUE THREAD

**Issue by codeyager** [ipfs/devgrants#151]
### 1. What is your project? (max 100 words)
Dexplorer is a Distributed file explorer built with the power of IPFS. Quickly organize your files and store them on an immutable file system.

https://github.com/codeyager/Dexplorer

will update in the future

### 2. How are you planning to improve this project? (max 200 words)
Hiring two more developers and launching the beta version in 2 months.
 
### 3. Will the work be Open Source?
Yes. All the work will be completely Open Source.

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Yes. I agree to provide a grant report upon conclusion.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes.

### 6. Links and submissions
 https://github.com/codeyager/Dexplorer
https://github.com/ipfs/community/discussions/633
  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
https://github.com/ipfs/community/pull/634/files

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? Yes
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
No, the project was not submitted at hackathon.  

* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
Yes.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Thambidurai K
        - Project manager
	- https://github.com/codeyager

Akbar Nawas
  - Web developer
  - https://github.com/codeyager

Mridula Kalaiselvan
- Front end developer
- https://github.com/Mridula90/

**Comment by ErinOCon** [comment]
Hi @codeyager, thank you again for your submission! Can you provide a full description of what you have built so far using Filecoin or related tech? In addition to this, further detail regarding your next steps for this project will help us complete our review.

**Comment by codeyager** [comment]
Hello @ErinOCon. .

As of now - I've built a React frontend that can use IPFS to view files on IPFS as well as upload files to IPFS (similar to iCloud but decentralized). I have also been exploring options to mint an NFT with the file that is stored in Dexplorer (work is half-done). The mail goal of DExplorer is to experiment and create a searching algorithm using pubsubs. However, I am learning IPFS and Filecoin now and I believe I will be able to add more novelty in what I am building.

Please let me know if you have any more questions, I will be very happy to answer.

**Comment by ErinOCon** [comment]
Hi @codeyager, thank you for the additional information! Can you provide your email address?

**Comment by codeyager** [comment]
Sure @ErinOCon , it's akbarnawas7@gmail.com

**Comment by ErinOCon** [comment]
Hi @codeyager! As discussed, this microgrant has been approved. Please reach out by email if you have any questions regarding next steps. Thank you for this submission!
