### ISSUE TITLE
[MICROGRANT] py-is_ipfs

### ISSUE THREAD

**Issue by Barabazs** [ipfs/devgrants#152]
### 1. What is your project? (max 100 words)
[py-is_ipfs](https://github.com/Barabazs/py-is_ipfs
) is a Python library (currently a WIP) to identify valid IPFS resources. The goal is to have a comprehensive method to be able to detect if *X* is a valid IPFS resource. *X* can be anything, URL, path, CID, hash, base encoded, ... 

The user should not have to worry about what kind of IPFS-related resource they provide to the library. Whether it's a CID, or a complete URL, the library does the heavy lifting of identifying, converting and validating the input.
E.g. :
```python
from is_ipfs import Validator

print(Validator("QmYjtig7VJQ6XsnUjqqJvj7QaMcCAwtrgNdahSiFofrE7o").is_ipfs())
# True
```
https://github.com/Barabazs/py-is_ipfs
https://pypi.org/project/py-is-ipfs/  

### 2. How are you planning to improve this project? (max 200 words)
Currently only CIDs are detected and validated. I plan on adding support for URL (including subdomains), paths, IPNS and other related references to IPFS resources. This includes researching appropriate methods and specifications, the actual implementation, robust testing, writing documentation, ...

### 3. Will the work be Open Source?
Yes, the code is currently licensed under MIT.

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions
  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
Yes, https://github.com/ipfs/community/pull/744

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 
  Yes
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  N/A

* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
  Yes
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

| Name     | Email                             | Github                      | Role      |
| -------- | --------------------------------- | --------------------------- | --------- |
| Barabazs | barabazs2021[​AT​]gmail[​DOT​]com | https://github.com/Barabazs | Developer |

**Comment by Barabazs** [comment]
Thank you @ErinOCon I'm looking forward to your feedback. :pray:

**Comment by ErinOCon** [comment]
Hi @Barabazs, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by Barabazs** [comment]
Hi @ErinOCon I'm having trouble finding where the weekly update should be posted. Can you advise please?
