### ISSUE TITLE
[MICROGRANT] dBranch News: Decentralized Journalism

### ISSUE THREAD

**Issue by b-rad-c** [ipfs/devgrants#155]
### 1. What is your project? (max 100 words)
An app that enables journalists to publish sources and content into IPFS. It will add immutable versioning and combat link rot in journalism through content addressing. By publishing ipfs CIDs on a blockchain (NFT, etc) authors can create a transparent audit trail. Additionally, it will enable official sources to publish press releases to create a cryptographic audit trail that would enable identification of misinformation. It would enable the marginalized to circumnavigate gatekeeping in journalism as well as enabling existing governments and journalists to establish trust via transparency and verifiability. 

#### Link to Github repo
[main repo](https://github.com/b-rad-c/dbranch-desktop)
[all repos](https://github.com/b-rad-c?tab=repositories&q=dbranch-&type=&language=&sort=)

#### Link to demo or website, if applicable
This [demo](https://dbranch.news/app) uses IPFS on the backend to make articles available to legacy browsers, the main repo (linked above) runs an electron desktop version that connects to a local IPFS node.

### 2. How are you planning to improve this project? (max 200 words)
The full white paper is available [here](https://dbranch.news/info), and a more focused technical paper is available [here](https://dbranch.news/app?article=dbranch_technology.news). Both of those are beyond the scope of a microgrant, for this I will focus on:

- creating a build process for the desktop application so anyone can use it instead of CLI wizards
- a go backend that uses the open api pin service to enable journalists to pin their articles to their outlet's ipfs server
- integration with the cardano blockchain that will enable the audit ability described above
- docker container for easily running your own dbranch node which will contain an ipfs node, cardano node and pin server
- harden security using electron [guidelines](https://www.electronjs.org/docs/latest/tutorial/security).

### 3. Will the work be Open Source?
Yes, it already uses the MIT license ([proof](https://github.com/b-rad-c/dbranch-desktop/blob/main/LICENSE.txt)).

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Yes.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes.

### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
  Not yet

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 
Yes
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
N/A
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Brad Corlett - bradcorlett@gmail.com - https://github.com/b-rad-c - founder / lead developer
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.

**Comment by b-rad-c** [comment]
Oops, I accidentally hit enter before typing anything in, will edit this with content shortly...

**Comment by b-rad-c** [comment]
Edited.

**Comment by ErinOCon** [comment]
Hi @b-rad-c, This microgrant has been approved! Look out for an email to submit payment details.
