### ISSUE TITLE
[MICROGRANT] SLON - a recommendation letter system

### ISSUE THREAD

**Issue by slonigiraf** [ipfs/devgrants#156]
### 1. What is your project? (max 100 words)
Web3 version of the traditional [recommendation letter](https://en.wikipedia.org/wiki/Letter_of_recommendation) with an option for a referee to stake reputation token on a recommendation letter about a worker. An employer can slash the referee reputation tokens in case of a fake recommendation letter, for example if the worker lacks skills mentioned in the recommendation.

Github:
[https://github.com/slonigiraf/slon-ui](https://github.com/slonigiraf/slon-ui)
Web2 MVP:
[https://slon-i-giraf.ru/app/work?language=ENG](https://slon-i-giraf.ru/app/work?language=ENG)
Web3 MVP can be build from the repo:
[https://github.com/slonigiraf/slon-ui](https://github.com/slonigiraf/slon-ui)

### 2. How are you planning to improve this project? (max 200 words)

- Pin recommendation letters CIDs
- Sync recommendation letters between user devices via IPFS
- Migrate local data backup from localStorage to IndexedDB
- Enable keys generation through UI (public/private pair)
- Launch public beta-version on a single node network with UI
 
### 3. Will the work be Open Source?
Yes

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
  https://github.com/ipfs/community/pull/756

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 
 Yes
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
 No
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
 Yes

* For each team member(s), please list name, email, Github account, and role in the project.
Reshetov Denis. Founder, Rust/JavaScript developer.
Email: reshetovdenis@gmail.com
Github: https://github.com/reshetovdenis

**Comment by ErinOCon** [comment]
Hi @slonigiraf, This microgrant has been approved! Look out for an email to submit payment details.
