### ISSUE TITLE
[MICROGRANT] <scrt bazzar>

### ISSUE THREAD

**Issue by Bild96** [ipfs/devgrants#160]
### 1. What is your project? (max 100 words)
_secret marketplace_

[ScrtBazzar](https://github.com/Bild96/scrtBazaar)
 
[secret marketplace](https://gateway.pinata.cloud/ipfs/QmVTHcM7s45ndyzswG2LCc4oLMjDdbA7UxELrWqWvYzv6j)

### 2. How are you planning to improve this project? (max 200 words)
_Digital product marketplace host in IPFS and integrating the payment process through web3 gateway._

 
### 3. Will the work be Open Source?

_The whole work source code will be available in the GitHub repo_ 

### 6. Links and submissions

  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)?  _already done._
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* If your project was created as part of an event or hackathon: _No_
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.

**Comment by ErinOCon** [comment]
Hi @Bild96, Thank you for the submitted proposal! Can you provide more detail regarding the work of your project and the next steps you plan to take over the next several months? In case it can be helpful, previous grants approved through the program can be found [here](https://github.com/filecoin-project/devgrants/blob/master/microgrants/accepted-microgrant-applications.md).

**Comment by Bild96** [comment]
I will create a music playlist, built in python based on auditory processing artifacts, and apparent sounds, the perception of which arises in the brain for specific physical stimuli. that binaural beats could help induce relaxation, meditation, creativity and other desirable mental states [ meditation sound tracks ].

**Comment by ErinOCon** [comment]
Thanks, @Bild96. Can you expand on your project further? Below are some questions to consider when addressing the first two items of this application: 

**"What is your project?"**
* What will your project accomplish? If applicable, how can it help users?
* What are the key objectives of your project?
* How is IPFS, Filecoin, or related tech being used?

**“How are you planning to improve this project?”**
* What are the next steps for this project? 
* If this grant is received, what will be accomplished in the next three months? 
* Any foreseen hurdles? If so, how are they being addressed?

**Comment by ErinOCon** [comment]
Hi @Bild96, I hope you are doing well! Do you have an update at this time?

**Comment by ErinOCon** [comment]
Hi @Bild96, this issue has been closed. Once more details are available, please feel welcome to reapply!
