### ISSUE TITLE
[MICROGRANT] <Sympodium>

### ISSUE THREAD

**Issue by Brilliant497705** [ipfs/devgrants#161]
### 1. What is your project? (max 100 words)

Sympodium coin is the first community based cryptocurrency that allows users mine transactions while adding to the blocks. It also comes with a smart contract called Sympodium NFT that allows users upload NFTs and trade among themselves.

  https://github.com/mendsalbert/sympodiumCoin

https://sympodium.netlify.app/

### 2. How are you planning to improve this project? (max 200 words)

 We intend to add more features to the Sympodium NFT market place where users can add to favorite and also follow the history of a collectible. We also intend to improve the Sympodium Coin where holders are not just nodes mining the coin but also can use it to perform whatever transaction they wish to use the coin for.

### 3. Will the work be Open Source?

Yes it will be an Open Source

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions

  https://sympodium.netlify.app/
https://github.com/mendsalbert/sympodiumCoin

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  

* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
  Yes

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Brilliant Kwakye, kwakyebrilliant@gmail.com, Brilliant497705, I worked on the documentation and Frontend.
* Albert Mends, mendsalbert@gmail.com, mendsalbert , I worked as a full stack developer. From the Backend to the frontend.
* Daniel Sarkodie, dsarkodie500@gmail.com, AbrantepaSark ,I worked on the UI/UX of Sympodium to have the best user experience.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Faber Web3
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.
https://devpost.com/software/sympodium

**Comment by ErinOCon** [comment]
Hi @Brilliant497705, thank you for your proposal! Can you briefly explain how IPFS, Filecoin, or related tech will be integrated into your work? Also, can you confirm the next steps of your project over the next three months? In case it can be helpful, [here](https://github.com/filecoin-project/devgrants/blob/master/microgrants/accepted-microgrant-applications.md) are examples of previously approved grants.

**Comment by Brilliant497705** [comment]
The NFT images are stored on IPFS server.

In the next three months, sympodium NFT will integrate other native cryptocurrency into its NFT marketplace including filecoin. The sympodium NFT will also have add to favorite button, an NFT transaction history which includes the prize paid and the previous owners and any other information needed.

We are planning to include a decentralized social platform into our system and also include a file security system that will allow people to determine who has access to the files. File owners will be getting royalties on any purchases or use of their property. And all these will make use of the IPFS server.

**Comment by Brilliant497705** [comment]
The NFT images are stored on IPFS server.

In the next three months, sympodium NFT will integrate other native
cryptocurrency into its NFT marketplace including filecoin. The sympodium
NFT will also have add to favorite button, an NFT transaction history which
includes the prize paid and the previous owners and any other information
needed.

We are planning to include a decentralized social platform into our system
and also include a file security system that will allow people to determine
who has access to the files. File owners will be getting royalties on any
purchases or use of their property. And all these will make use of the IPFS
server.

**Comment by ErinOCon** [comment]
Hi @Brilliant497705, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by Brilliant497705** [comment]
Awesome, thanks!
