### ISSUE TITLE
Next Step Microgrant: <4EVERLAND BUCKET>

### ISSUE THREAD

**Issue by 4everlandorg** [ipfs/devgrants#162]
### 1. What is your project? (max 100 words)

4EVERLAND BUCKET enables users to upload, store, PIN, and fetch files from the IPFS in a secure, convenient, and efficient manner. BUCKET is also compatible with AWS S3 application programming interface, CLI, and other upload methods, making it easier for users to use our product.

  https://github.com/4everland/bucket-website

https://www.4everland.org/bucket
### 2. How are you planning to improve this project? (max 200 words)

 1. Build more decenterlized gateway for IPFS.
 2. Add more global nodes to speed up upload rates.
 3. Create a domain system for users to bind custom domains.
 4. Looking for publicity and more collaboration opportunities.
### 3. Will the work be Open Source?

YES, 4EVERLAND BUCKET is licensed with MIT license for code or CC-BY-SA 3.0 license for content.
### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

 YES.
### 5. Does your proposal comply with our Community Code of Conduct?

YES.
### 6. Links and submissions

  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  NO.
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
  YES.
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Name: Clarence
Role: Core Team Developer|Full Stack Engineer
Email: [qwertyhqwerty475@gmail.com](mailto:qwertyhqwerty475@gmail.com)
Github: [@cryptobuffer](https://github.com/cryptobuffer)
Name: Thloyi
Role: Core Team Developer|4EVER-Hosting Architect
Email: [tfspq@protonmail.com](mailto:tfspq@protonmail.com)
Github: [@thloyi](https://github.com/thloyi)
Name: Saullary
Role: Core Team Developer|Front End Developer
Email: [saullarytzc94@gmail.com](mailto:saullarytzc94@gmail.com)
Github: [@saullary](https://github.com/saullary)
* If your project was created as part of an event or hackathon:
NO
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.

**Comment by ErinOCon** [comment]
Hi @4everlandorg, Thank you for the submitted proposal! The progress of your work appears to have passed the intended scope of this grant type. The microgrant program is generally intended for early stage projects by independent developers, small studios, non-profits, activists, and researchers.

To explore future opportunities for support, please stay in touch with our team!

**Comment by 4everlandorg** [comment]
Hi, about our project is it possible to try to apply for open grants?

**Comment by ErinOCon** [comment]
Hi @4everlandorg, it sure is! To learn more about our Open grants, check out our [Github Repo](https://github.com/filecoin-project/devgrants).  When you're ready to submit a proposal, be sure to use the relevant [template](https://github.com/filecoin-project/devgrants/issues/new/choose) to create a new issue.
