### ISSUE TITLE
Next Step Microgrant: <TheWeb3Portal from Web3DAO>

### ISSUE THREAD

**Issue by TheWeb3DAO** [ipfs/devgrants#163]
### 1. What is your project? (max 100 words)

TheWeb3Portal is a Web3 navigation site for all users and Web2 web developers. It is released by the Web3DAO. Organization members will help the front-end deployment of traditional Web2 websites on IPFS to achieve decentralization and integrate the deployed websites into TheWeb3Portal website for users to search and access. 

  https://github.com/Web3-Portal/TheWeb3Portal

https://www.web3-portal.org/
### 2. How are you planning to improve this project? (max 200 words)

 1. Building a more reliable server.
 2. Do brand promotion and expand our influence.
 3. Bookmark more sites and set them up on IPFS.
 4. Hire more Development Engineers.

### 3. Will the work be Open Source?

YES
### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

YES
### 5. Does your proposal comply with our Community Code of Conduct?

YES
### 6. Links and submissions

  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
NO
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
YES
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Name: Saullary
Role: Core Developer
Github: [@saullary](https://github.com/saullary)
Email: [saullarytzc94@gmail.com](mailto:saullarytzc94@gmail.com)
* If your project was created as part of an event or hackathon:NO
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.

**Comment by ErinOCon** [comment]
Hi @TheWeb3DAO, Thank you for submitting this proposal! Can you provide more detail regarding the next steps you will be taking over the next three months with this specific grant?

**Comment by TheWeb3DAO** [comment]
Thank you for your reply, the improvements we are currently implementing include improvements to the PORTAL website, wallet login, cid addressing etc. We are planning to create a separate website on IPFS nodes, which is in progress and will take up 50% of the grant, the other 50% will be used to build our community and run the marketplace. Eventually we plan to create a community of developers and members where everyone can contribute ideas to the development of Web3 and we will vote on quality projects in the form of DAO's to develop them together. Of course, IPFS will be a very important part of this, and we believe that there will be many projects related to IPFS in the future. So we hope that we can reach a consensus with IPFS at an early stage of community building.
