### ISSUE TITLE
[MICROGRANT] Vortex ✨

### ISSUE THREAD

**Issue by jgarciajovel** [ipfs/devgrants#165]
### 1. What is your project? (max 100 words)
**Vortex** it’s the **first** platform that allows business and influencers to create custom contests, promotions and giveaways in the form of a functional NFT using Web3.Storage (IPFS).

Github
https://github.com/jgarciajovel/vortex
  
Demo
https://vortex-app.herokuapp.com/

### 2. How are you planning to improve this project? (max 200 words)
A Food Delivery Startup and Papa John's are very interested in giving NFT's as a loyalty method for their customers and give rewards in Filecoin. At the moment our platform is working perfectly but we have found clients in El Salvador who are willing to use this type of service and we want the payment method within our platform to be Filecoin.

 
### 3. Will the work be Open Source?
Yes, we want anyone anywhere in the world to be able to use our technology in their projects.

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Yes, we agree. We will create a work roadmap and we are also willing to show a weekly progress.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes it does.

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
Yes 🙌
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
**Juan Carlos García Jovel** / CEO and Backend Deverloper / https://github.com/jgarciajovel
**Jaime Roberto Chávez Lorenzana** / CTO and Frontend Developer / https://github.com/jchavezjs

* If your project was created as part of an event or hackathon:
  * What was the name of the event? / **Faber Web3 Hackathon**
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize. / https://devpost.com/software/vortex-kr7z1v

**Comment by ErinOCon** [comment]
Hi @jgarciajovel, thank you for submitting this proposal! Can you provide more detail on the next steps you will take using this microgrant specifically?

**Comment by jgarciajovel** [comment]
Hi there, sure 👋

1. We are going to use part of the money to hire one more developer. This person will help us create a landing page and add more features to the web app.

3. We are planning to add Filecoin as the only way to pay for our services. So we have to make the proper changes in order to show that in our
Web.

4. A small marketing campaign. It's very important to show what we and how we do it to the public, so we are going to create a marketing campaign so we can attract more clients.

Please if you need more info just let me know 👏

**Comment by ErinOCon** [comment]
Hi @jgarciajovel, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by ErinOCon** [comment]
@jgarciajovel Can you provide an email address to receive payment instructions?

**Comment by ErinOCon** [comment]
Thank you!
