### ISSUE TITLE
[MICROGRANT] Caste

### ISSUE THREAD

**Issue by TheGodOfAwesome** [ipfs/devgrants#166]
### 1. What is your project? (max 100 words)
Caste https://caste.vercel.app/  
A Trading Card Game (T.C.G.) with an emphasis on a caste magic system and an environment magic system in a constant state of flux ("The Shift"). A unique card acquisition system that is based on accomplishing raids and challenges to acquire key items and cards which can only be otherwise acquired through PvP combat.

Play to earn without any of the grind. We accomplish this by allowing the players to create, contribute and share art and assets for these game and sell these new player generated assets and through a marketplace and esports ecosystem built on IPFS.

https://github.com/TheGodOfAwesome/Caste
https://github.com/Psychographics
  

Caste https://caste.vercel.app/

### 2. How are you planning to improve this project? (max 200 words)

We intend to  
i. Implement Game Mechanics.   
ii. Improve Game Asset Creation, Management and Sharing on IPFS.
iii. Implement Seamless Game Asset equips from IPFS network.  
iv. Improve game board.  
v. Implement more sound effects and asset animations.  
 
### 3. Will the work be Open Source?

Yes

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions

  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:  
    #### EthGlobal BuildQuest Multiplayer Award Winner (project: [showcase.ethglobal.com/buildquest/caste-m7bgy](https://showcase.ethglobal.com/buildquest/caste-m7bgy))

  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)?  
    #### Yes
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Kuzivakwashe Muvezwa Lead Developer:  
i: https://github.com/TheGodOfAwesome   
ii: muvezwakuzivakwashe@yahoo.com

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.

#### EthGlobal BuildQuest Multiplayer Award Winner (project: [showcase.ethglobal.com/buildquest/caste-m7bgy](https://showcase.ethglobal.com/buildquest/caste-m7bgy))

**Comment by TheGodOfAwesome** [comment]
Update:
I have created an organisation for the project and added more repos for the site, unity project, web project, game design and  lore

**Comment by ErinOCon** [comment]
Hi @TheGodOfAwesome, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by TheGodOfAwesome** [comment]
Thanks Erin
