### ISSUE TITLE
[MICROGRANT] Time Limited Tokens Specification and Web3BnB Reference Implementation

### ISSUE THREAD

**Issue by rhdeck** [ipfs/devgrants#167]
### 1. What is your project? (max 100 words)
Time is the ultimate scarce resource. We have less of it every second. Time slicing is critical to ideas of fractional possession - allocating rights for a finite period allows resources to generate more value for more humans without requiring their growth or change.

However, ERC721 and related standards do not provide the functionality to enable the leasing of NFTs or other assets for a specific period.

That's why we devoted our hackathon period to defining a simple, supple interface for time-slicing assets and expressing who has possession as a lessee at which point in time. We want to take the next step!

[Github monorepo](https://github.com/rhdeck/time-limited-tokens)
  

### 2. How are you planning to improve this project? (max 200 words)
We want to finish the EIP for leasing tokens and create a robust reference implementation as a Dapp that shows how much leverage one can get from these assets through efficient, atomic leasing. The original version was limited to leasing days and now we are targeting being able to transfer assets for seconds or blocks, as well as implementing a more robust authorization (approve, transferFrom, approveForAll) scheme that parallels ERC721. Basically, we think there's a big opportunity to make NFT-type assets much more flexible.

The reference implementation will show how easy it is now to create assets and store them using nft.storage or web3.storage - the whole idea is shifting from "how do I get these up" to "how to I put them to work for me." The leasing interface will let people see assets of which they are the possessor, or the future possessor through leasing or pending unleases. The vision is to be like your NFT collection site but with a view to time, and a focus on enabling time-limited transactions: rentals, leases, loans, etc. 
 
### 3. Will the work be Open Source?
Yes, our work is open-source (see GitHub repository above) and a major goal is an EIP that might get accepted, and a library to make it easy to build on top (distributed via NPM, OpenZeppelin style). The reference implementation is part of the monorepo, and to the extent it generates useful tooling, we would want to put that up via npm as well. 

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Yes, that would be great. For the regular reports, video summaries based on our zoom meetings where we do most of our work. A way to show the process and get everyone's participation. And why not put them on web3.storage? (And maybe make them lease-able?)
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions

  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  Yes, we submitted for web3con and won 3rd prize IPFS/FileCoin bounty ($750 in FIL) along with the recommendation we submit here. 

* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
Yes! 
  
#### For each team member(s), please list name, email, Github account, and role in the project.
1. [Ray Deck](https://github.com/rhdeck), developer
2. [Akshay Rakheja](https://github.com/akshay-rakheja) developer
3. [Robert Reinhart](https://github.com/robertreinhart) developer
(Can send email addresses privately)

#### If your project was created as part of an event or hackathon:
  * What was the name of the event? Web3Con
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize. 
  1. [Github](https://github.com/rhdeck/time-limited-tokens)
  2. [Video](https://www.loom.com/share/6992b9306f134e9fa19ab62bac53c79c?sharedAppSource=personal_library)

This was great to hack on and we think there's a lot of value we can create for the community at large with another month of progress. Hoping to get to work with you!

**Comment by ErinOCon** [comment]
Hi @rhdeck, This microgrant has been approved! Can you send your preferred email address to discuss the payment process?

**Comment by rhdeck** [comment]
Sure thing. My email is ray at raydeck dot com.

**Comment by rhdeck** [comment]
Hey @ErinOCon I didn't see an email come through - if you sent before, could you send one more time and let me know what domain it would come from so I can make sure to rescue?

**Comment by ErinOCon** [comment]
Hi @rhdeck! This email has been sent. Please be in touch if there is any trouble receiving the payment instructions.
