### ISSUE TITLE
[MICROGRANT] <Lucky You>

### ISSUE THREAD

**Issue by B-Venkatesh7210** [ipfs/devgrants#168]
### 1. What is your project? (max 100 words)

Lucky You - Your one golden way to create and participate in giveaways of MATIC tokens where you can also mint NFT of the giveaway you've won. Lucky You provides the users with trust and they cannot be scammed by any means as observed in Web2 giveaway websites. We used CHAINLINK, GELATO, IPFS for this Dapp for various purposes.
Please refer to the below submission link for more details :-
https://devfolio.co/projects/lucky-you-430d

https://github.com/B-Venkatesh7210/lucky-you-webapp
  

https://luckyyou-69f3c.web.app/

### 2. How are you planning to improve this project? (max 200 words)

We want to improve the quality of NFT, make it more unique to grab attention of more users, we want to integrate this dapp with numerous social platforms for the benefit of the creator of the giveaway.
 
### 3. Will the work be Open Source?

Yes the work will be Open Source.

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

Yes.
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes it is.

### 6. Links and submissions

https://devfolio.co/projects/lucky-you-430d
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
We won the Protocol Lab prizes worth $1500.
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
Yes
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Team Member 1 :-
Name - B Venkatesh
Email - venkumj1234gmail.com
Github - https://github.com/B-Venkatesh7210
Role - Smart Contract Developer, Frontend Developer

Team Member 2 :-
Name - Rohit Kumar
Email - rohitduhan2301@gmail.com
Github - https://github.com/Rohit2301
Role - Smart Contract Developer, Frontend Developer

* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
  Ethernals 2022
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.
  https://devfolio.co/projects/lucky-you-430d

**Comment by B-Venkatesh7210** [comment]
Microgrant Done

**Comment by ErinOCon** [comment]
Hi @B-Venkatesh7210, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by ErinOCon** [comment]
Hello @B-Venkatesh7210! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!
