### ISSUE TITLE
Next Step Microgrant: IPFS-DROP

### ISSUE THREAD

**Issue by vasanthsteve23** [ipfs/devgrants#171]
### 1. What is your project? (max 100 words)
IPFS- drop makes sharing files very simple as you can just share the hash and others can access the file using the hash instead of you spending your internet and Users can still access the files through the file hash or the unique link generated. IPFS-DROP can also be integrated as a browser extension where you can hash your files to a decentralized storage and access whenever you are in need while browsing.

We provide a decentralized platform for file storage using IPFS as the power house.

https://github.com/vasanthsteve23/IPFS_DROP
  

### 2. How are you planning to improve this project? (max 200 words)
Creating a micro-startup by hiring two web3 developers, one marketing lead and thereby proceeding to release the application with browser integration in two months.
 
### 3. Will the work be Open Source?
Yes, All the work will be fully open source.

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Yes, I will update with the report every week with complete status of the development .
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions
https://github.com/ipfs/community/blob/master/projects/IPFS-Drop.md

* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
Yes

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Team Member : Vasanth Steve 
Email : vasanthsteve23@gmail.com

**Comment by ErinOCon** [comment]
Hi @vasanthsteve23, thank you for submitting this proposal! Can you provide more detail on how this specific microgrant ($5,000 USD) will be applied in your next steps over the next several months?

**Comment by vasanthsteve23** [comment]
@ErinOCon Hello,

I intend to hire two web3 developers to work on further improvements to this project, as well as to purchase various resources for the application's  deployment.

**Comment by ErinOCon** [comment]
Hi @vasanthsteve23, This microgrant has been approved! Look out for an email to submit payment details.
