### ISSUE TITLE
[MICROGRANT] PropKoin

### ISSUE THREAD

**Issue by HaliSyed** [ipfs/devgrants#174]
### 1. What is your project? (max 100 words)

PropKoin is a UAE-based firm dedicated to empower the real estate industry and embrace the next wave of digital platform consolidation. Our focus is to help entities with a high dependency on Illiquid Assets and dormant cashflows, maximizing their potential through the adoption of disruptive tokenization solutions.
PropKoin sees a future powered by blockchain technology, Innovation, and financial transparency.

https://github.com/HaliSyed/PropBlock
  

http://www.propkoin.com/

(A semi-working MVP of the solution is not hosted on URL, The frontend is developed using MongoDB and Node, Some of the smart contracts code and utilization of IPFS tested on solidity playground is in repo)

### 2. How are you planning to improve this project? (max 200 words)

The aim is to prepare a solution for tokenization as a service. This will be used for our platform real estate tokenization solution intially.  Our roadmap is metaverse. 

We are aiming to solve the 6 main issues including of global economy with the help of this 
1- Long Horizen for the returns
2- Low liquidity
3- Geographical and legal issues in cross-border investment (We are working with DIFC-Dubai international financial center)
4- High Entry barriers and slow administrative processes
5- Lack of diversification
6- Lack of Transparency

 
### 3. Will the work be Open Source?

We are open to offering opensource code
### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

  Agreed
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions

Yes
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
 
 It began for the hack but we were not able to complete
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
Yes I have filled it and my contact details are haider@aitropolis.com
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Haider Ali Syed haider@aitropolis.com https://github.com/HaliSyed/
Seddik https://github.com/seddik11
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
Anglehack
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.
 The project was incomplete as two team members left a week before the submission due to personal/family emergencies. It was covid peek days.
 I am available to continue with the new team. I also do the design and some coding of software and blockchain-based solutions. I am also well connected with developers and I have delivered a large number of software solutions to the market.

**Comment by HaliSyed** [comment]
Hi ErinCon
Let's initiate our discussion.
Haider

**Comment by ErinOCon** [comment]
Hi @HaliSyed, thank you for submitting this proposal! What are the specific next steps for your project? How will the $5,000 microgrant be used to meet your end objectives?

**Comment by HaliSyed** [comment]
Hi @ErinOCon 
Our cost estimate is below
1- Software development 12500$ for Web Version +5000$ USD for Mobile App
2- Business Development + Global Reach (Phase 1 5000$, Phase 2 10000$)
3- Operational Infra and Licensing with Regulator 5000$

We will utilize grant funding and additional we will invest (Bootstrapping) 

Thanks

**Comment by HaliSyed** [comment]
To be more precise we will utilize this for the software development phase 1

**Comment by ErinOCon** [comment]
Hi @HaliSyed, thank you for confirming the funds will be applied towards software development. Can you briefly describe the objectives you aim to achieve over the grant period (three months)? This information will help us with our grant reporting. 

Also, please note that open source work is a key criteria point for our microgrant program. If you have any questions regarding this requirement, please let me know!

**Comment by HaliSyed** [comment]
@ErinOCon 

I can work with you to show our pitch. The on-chain and off-chain steps are following.

Off-chain
Validate the commodity
etc
Onchain activities
1- Tokenize the commodity/Property
2- Strip the tokens to an agreed value (Let's say 2000AED)
3- Verified (KYC/AML) users to purchase the token(Stripes)
4- Once the Token (stripes) cap is reached, it will initiate the token/stripes transfer.
5- Transaction through Escrow account will be initiated by smart contract 
 
 Question...
  Is 5000$ is the cap or we can go for a higher value. The minimum cost of software development is hitting 22K USD..

**Comment by HaliSyed** [comment]
Hi @ErinOCon 

What we provided is a plan of complete development (All phases)
Can we still get the microgrant and the rest we will bootstrap?

Haider

**Comment by HaliSyed** [comment]
Hi Eric,

We are still on phase 1. Can we still apply for microgrant ?
