### ISSUE TITLE
[MICROGRANT] M-NFT

### ISSUE THREAD

**Issue by senitskiy** [ipfs/devgrants#175]
### 1. What is your project? (max 100 words)
"M-NFT" is a modified smart contract (M-NFT) technology for NFT tokens. Tokens created and transferred to M-NFT can place an additional layer (mask) on top of the original image. The technology will allow NFT to be modified to meet the demands of the advertising business, and can also be used in crypto gaming, collective creativity and copyright protection. NFT Tokens can be both created and transferred to M-NFT using the service of the same name.

[github.com/M-NFT](https://github.com/M-NFT/M-NFT)
[app.mnft.company](https://app.mnft.company/)

### 2. How are you planning to improve this project? (max 200 words)

 To transform the marketing sphere with our new tool, which gives the opportunity for income to several participants at once. Take 20% of the crypto advertising market during the first year

### 3. Will the work be Open Source?

Yes, our project will be Open Source (MIT).

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Yes, we agree.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes.

### 6. Links and submissions
![Our Pitch Deck: ](https://bafybeibcl524mfxvsjerqlcg63ord44vo3jlugfmtiushcq3hz4rjliepu.ipfs.dweb.link/0)
![Our roadmap: ](https://bafybeiabpwqp4b47smwd5poybutvtc3sx7yg2brj6zqh5z5pal2hlpmnhu.ipfs.dweb.link/0)
![Our team: ](https://bafybeidfakpovmqvmg6a2np7gupf2pcritm4j2kywr6twsimf22fzi3bu4.ipfs.dweb.link/0)

**Comment by ErinOCon** [comment]
Hi @senitskiy, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by senitskiy** [comment]
Ok. Very good!

**Comment by ErinOCon** [comment]
Hi @senitskiy, can you outline the specific steps your team will take with this grant to meet the objectives stated in item 2? This should roughly cover a 3 month timeline. 

Also, it looks like your links do not currently lead to a repo or page with content. Is this in progress?

**Comment by senitskiy** [comment]
Links updates.
[github.com/M-NFT](https://github.com/M-NFT/M-NFT)
[app.mnft.company](https://app.mnft.company/)
![Our Pitch Deck: ](https://bafybeibcl524mfxvsjerqlcg63ord44vo3jlugfmtiushcq3hz4rjliepu.ipfs.dweb.link/0)
![Our roadmap: ](https://bafybeiabpwqp4b47smwd5poybutvtc3sx7yg2brj6zqh5z5pal2hlpmnhu.ipfs.dweb.link/0)
![Our team: ](https://bafybeidfakpovmqvmg6a2np7gupf2pcritm4j2kywr6twsimf22fzi3bu4.ipfs.dweb.link/0)

**Comment by ErinOCon** [comment]
Hi @senitskiy, thank you for sending the updated links! It looks like the budget for this project is much larger than the grant value. Can you confirm how the funding for this $5k microgrant will be used?

**Comment by senitskiy** [comment]
Hi @ErinOCon! This presentation and roadmap is more for big investors. Some of it will go to support the team or marketing.

**Comment by senitskiy** [comment]
> Hi @senitskiy, thank you for sending the updated links! It looks like the budget for this project is much larger than the grant value. Can you confirm how the funding for this $5k microgrant will be used?

We plan to get the team together in one place and have a mini-hackathon. Presumably in late June or early July in Dubai.

**Comment by ErinOCon** [comment]
Hi @senitskiy, thank you for your reply. Microgrants are generally intended for early stage projects that have received minimal funding (less than $30,000 USD). Would this be the case for the described project?

**Comment by senitskiy** [comment]
Hi [ErinOCon](https://github.com/ErinOCon)! Yes. We haven't received any grants yet. We do for fun, what is interesting to us and in parallel moves WEB3/Blockchain in our free time. The current grant is considered as an additional motivation of the team. For full-time we will need other grants. At the current stage and for new investors in the future, this grant will be indicative. We are showing consistent realization and implementation of the project. We are already preparing a concrete and new use case that allows us to use our technology for cryptans.

**Comment by ErinOCon** [comment]
Thanks, @senitskiy! Can you briefly describe the next steps you will take with this grant over the period of the grant (three months) and how IPFS/related tech will be utilized? These final details will help us complete our review!

**Comment by senitskiy** [comment]
[ErinOCon](https://github.com/ErinOCon), we want to implement avatars that will work for Web3. We will use IPFS to store jpeg/png pictures or gif/mkv videos.

**Comment by ErinOCon** [comment]
Hi @senitskiy, thank you for the information provided. Your grant has been approved! Can you confirm the preferred email address for discussing payment details?

**Comment by ErinOCon** [comment]
Thank you!
