### ISSUE TITLE
[MICROGRANT] Photogrammetry.wiki

### ISSUE THREAD

**Issue by yosun** [ipfs/devgrants#177]
### 1. What is your project? (max 100 words)
 
Photogrammetry.wiki is a new decentralized autonomous platform for teleporting real objects in reality into the metaverse - that anyone can edit.

Photogrammetry is a method for turning 2D photography into a 3D model, which is a metaverse native content format that can also be a NFT. Effectively, this lets any user with a smartphone "teleport" any real object into the metaverse as a 3D object simply by taking many photos of it! We use IPFS web3.storage for storing "forever" photogrammetry data, including all photography and the resulting generated 3D model. We also allow users to upload their own generated 3D models for each data set, as different algorithms can produce different 3D mesh results from the photography. 

In the near future, GANs will be able to create even better 3D models from sparse photography! 

[Link to Github repo](https://github.com/yosun/Photogrammetry_wiki)
  
[Link to temp website and demo](https://devpost.com/software/photogrammetry-wiki)

### 2. How are you planning to improve this project? (max 200 words)

Currently, the project is a last minute hackathon submission that works but is perhaps a bit fragile and needs quite a bit of proper architecting for public production. For example, I had followed a tutorial on proto.school for implementing a tagging system - however, that apparently does not scale for a large data set. 

I'd like to wrap this project up so that it's ready for a marketing blast public beta testing. 
 
### 3. Will the work be Open Source?

Yes, it's a wiki! Open to licensing discussion. 

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

Yes, as I am still quite new to filecoin / IPFS, I would also appreciate the mentorship! (I have actually been meaning to find someone to discuss the proper way to architect this project.)
  
### 5. Does your proposal comply with our Community Code of Conduct?
 YES

### 6. Links and submissions

  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: I'm not sure about the Protocol Labs prize, but this won several prizes at the Faber Hackathon. See devpost link above. 
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? Yes
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
    **   yosun chang: everything, everywhere, all at once! / yosun at areality3d dot com / github.com/yosun
   
* If your project was created as part of an event or hackathon:
  * What was the name of the event? Faber Hack
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize. https://devpost.com/software/photogrammetry-wiki

**Comment by ErinOCon** [comment]
hi @yosun, thank you for submitting this application! We will be in touch with an update or questions once we have completed our initial review.

**Comment by ErinOCon** [comment]
Hi @yosun, thank you again for the proposal! Can you briefly describe the next steps you will take with this microgrant?

**Comment by yosun** [comment]
Bug fixes and I'd like to wrap this project up so that it's ready for a marketing blast public beta testing.

Right now, tagging isn't exactly scalable, since it is using the chaining method in proto.school

**Comment by ErinOCon** [comment]
Hi @yosun, This microgrant has been approved! Look out for an email to submit payment details. I will also include some connection resources that may help you explore your scalability options.
