### ISSUE TITLE
Next Step Microgrant: Mintable Blocks 

### ISSUE THREAD

**Issue by Adithya-adi-Menon** [ipfs/devgrants#181]
### 1. What is your project? (max 100 words)
The use of payments in real world are much more higher, everything is gone digital . After the years in the era of Blockchain payments time will be an important factor in payments and the payments should will be p2p in nature. I propose an application where crypto payments can be done much faster the features include

*  A decentralised Payment Application in the world of  E-commerce 
*  Pay easily to merchants with a single qr 
*  Each user can be added as friend and the token transfer can happen within a click 
*   Transfer any currency within a single click 
*   Send payment qr to qr 
*  Transfer to each unique payment interface with     least gas fees 
*  Store NFTs and also Transfer easily 

https://github.com/Mintable-Blocks

### 2. How are you planning to improve this project? (max 200 words)

This idea needs to me scaled  higher and started as a startup company. This is the next futuristic blockchain based application where decentralised p2p payments are used . The application will be developed. Developers and Marketing teams need to be hired . 
 
### 3. Will the work be Open Source?
Yes, The work will be open sourced 

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Yes , I agree to complete the work and give weekly updates 
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes 

### 6. Links and submissions

No
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
  
  Yes
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Adithya MENON S 
Blockchain Developer 
Adithyamenons17@gmail.com

**Comment by Adithya-adi-Menon** [comment]
@ErinOCon Thank you for reviewing my proposal. Actually there are no repositories created , the proposal is currently outlined and the development will be started as soon as the grant is approved. Thank you !

**Comment by ErinOCon** [comment]
Hi @Adithya-adi-Menon, thank you for the update! Microgrants are generally intended for projects that have already started the building process. Do you have any links or documents available that can represent the work completed thus far (website, demo, etc.)?

**Comment by Adithya-adi-Menon** [comment]
@ErinOCon Thank you ,I thought I could start my work after receiving the grant, so I could use the provided resources to build the entire application. I will begin work immediately.

**Comment by Adithya-adi-Menon** [comment]
@ErinOCon Hi, So ill be concentrating on three phases ,
* Creation of team : As the development is already in progress , I'll hire one web3 developer and a marketing lead for further enhancements of this project 
* Launching Beta version : The next process is to launch beta version and to test the product.
* Marketing : A Stable version of the product will be released and the product will be further enhanced with new updates and features

**Comment by ErinOCon** [comment]
Hi @Adithya-adi-Menon, thank you for the additional information. This project is currently a better fit for [a hackathon](https://hackathons.filecoin.io/) as it is in the beginning stages of building. Please feel welcome to re-apply once a prototype is available!
