### ISSUE TITLE
Next Step Microgrant: P2P Social Network Over LoRa

### ISSUE THREAD

**Issue by ki4jgt** [ipfs/devgrants#182]
### 1. What is your project? (max 100 words)
Social networks could easily take the blame for the current state of the geopolitical climate. The dissemination of accurate news, and clear communication should be a high priority for users, but that isn't the case. Users are at the mercy of the whims of their network providers.

Because networks can't authenticate posts fast enough, you have completely accurate information being taken out of the hands of the people who need it most. Or, due to faulty design, no one can see the information at all. Just today, I responded to a post on antidepressants, and created a thread of comments which referenced links to the NIH, psychology magazines, and MIT. Users were replying that my assertions were incorrect, but were unable to see any of my reference links, because Facebook defaults to "Most Relevant," instead of, "All Comments."

I'd also like to mention the memorial page to a dear family friend, where every post is blocked, because most of it is dark humor which Facebook deems inappropriate.

My desire is to put the power of the network into the hands of the user.

[https://github.com/ki4jgt/parcel](https://github.com/ki4jgt/parcel)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
The content of user posts are submitted to the IPFS network. Then the resulting CID is appended to a signed block on the user's own personal chain -- along with the CIDs of their current profile and friends' list. Their friends' list containing current CIDs for all of their followed accounts.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
As a user adds to the network, the CID for their most recent block is constantly changing. As my project is built over js-ipfs, the ability to publish names to IPFS has been broken for a long time. And I'm no longer sure that's the route I wish to take. I need a way to propagate current CIDs between users, without being dependent on central servers which can easily be taken down. Wifi and Bluetooth are short-ranged. My solution is LoRa. Users will periodically broadcast the CID of their most current block. People in their community can subscribe to their accounts, view their posts, comment, traverse their friends' list for updates on other users, etc. And this circumvents the FCC's restriction on store-and-forward systems, as the user is only transmitting their own personal CID.

To do this, I need 2 laptops, and 2 LoStiks for testing. I also need to pay myself.
 
### 4. Is this project open source?
The current project is licensed under GPL-3, but can be changed to meet whatever qualifications you guys desire.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Jesse Cox
ki4jgt@gmail.com
ki4jgt
Primary Developer

* How did you learn about our microgrant program?
Searched Google for IPFS grant

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
N/A

  * Please link to your hackathon submission
N/A

**Comment by ki4jgt** [comment]
@ErinOCon I apologize for my earlier submission. I've never written for a grant before. After reviewing some of the other applications, I redrafted mine.

**Comment by ErinOCon** [comment]
Hi @ki4jgt, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by ErinOCon** [comment]
Hi @ki4jgt, thank you again for this proposal! Do you have a plan in place for gaining traction and growing a user base for this project?

**Comment by ki4jgt** [comment]
@ErinOCon, I was hoping to split the project into a couple of different things:

- Broadcast server
- Local user interface

The user interface would contain the core project, while the broadcast server could be swapped out to interact with various modes of communication (email, WAN/LAN, RF), and broadcast a signed beacon containing the user's current CID.

My plan is to target the ham radio community, as their digital modes are very slow. Many of their systems are already patched into the Internet. I think they'd enjoy a social network built over the protocols they've already developed. IPFS handles the data transfer, while their beacon only transmits a small amount of metadata. Perfect for low bandwidth situations.

The FCC forbids store and forward over the ISM bands, so LoRa alone isn't an option. But neither is IPFS, as people cannot discover peers locally. LAN and Bluetooth are too localized. Any network built over them would be limited. Requiring people to have direct interactions in their communities.

By bridging IPFS and RF, users may subscribe to and discover each other more locally (organically). Communities can spring up between people with common interests. The town square disappeared after the 90s. I'd like to bring it back. I believe IPFS can assist in this.

**Comment by ErinOCon** [comment]
Hi @ki4jgt, thank you for your time providing additional information. This microgrant has been approved! Look out for an email to submit payment details.
