### ISSUE TITLE
Next Step Microgrant: CC0 Music Metadata on IPFS

### ISSUE THREAD

**Issue by morestatic** [ipfs/devgrants#183]
### 1. What is your project? (max 100 words)
disc3 is a project to host the major CC0 music metadata collections (discogs.com, musicbrainz, etc) directly on IPFS. Music is a key element of many people's lives and discovering new music and artists brings joy to those people. Currently, apps wanting access to music metadata must use web2 api access keys. While some metadata is managed by open organizations, some is managed by private or closed organizations. Losing access to this data would be loss for music lovers. disc3 aims to make this (CC0) music metadata available to all via free web3 (IPFS/Filecoin) based access.

https://github.com/morestatic/disc3
https://www.disc3.xyz (portal onto the existing IPFS node currently containing approx 30M json music metadata docs)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
IPFS and Filecoin are at the heart of the project and are to host all data

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
The primary goal will to fully automate making the music metadata available on IPFS. Including the following tasks:
- Automate the steps to load a new discogs drop (monthly) to IPFS
- Improve recovery on IPFS node failure
- Add additional dedicated servers for IPFS nodes hosting the data
- Add Filecoin archiving of all data
- Significantly improve documentation for data use + data loading
- Add support for musicbrainz.org metadata
- Commission and implement a better disc3.xyz website design
- Initial PR to promote the availability of the data on IPFS
- Add a simple client side SDK (ipfs based) to make the data even easily to load for web3 developers
- Add additional indexes for metadata discovery
- Improve test code coverage
- General code improvements & refactoring
 
### 4. Is this project open source?
Yes, MIT license - can switch to Creative Commons Legal Code if preferred

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes it does

### 7. Links and submissions
Project didn't start as a hackathon.
(project links listed under 1.)

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Robin Shorrock, morestatic00@gmail.com, https://github.com/morestatic, developer

* How did you learn about our microgrant program?
Via the IPFS web site but maybe discord initially

* If your project was created as part of an event or hackathon:
Not created as part of event or hackathon.

**Comment by ErinOCon** [comment]
Hi @morestatic, This microgrant has been approved! Look out for an email to submit payment details.
