### ISSUE TITLE
[MICROGRANT] <Dynamic Drops>

### ISSUE THREAD

**Issue by rdz108** [ipfs/devgrants#184]
### 1. What is your project? (max 100 words)
Dynamic Drops  is a web app allowing creators to deploy ERC-721 contracts with dynamic pricing of tokens.
_When minting is slow, prices go low; when minting’s on fire, prices go higher!_

[](https://github.com/ClockworkOrange605/build-quest)
Landing page: https://DynamicDrops.xyz
Demo (in progress): http://demo.dynamicdrops.xyz/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
Creators will be offered to upload metadata to IPFS within our app. This makes it user-friendly for non-technical people to deploy collections and decentralize their metadata with IPFS.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Our next step is building an open beta app. 
We will cover costs of DigitalOcean servers, contract a UI designer, and retain Andrey Kochkin as lead developer to focus on this. 
With a microgrant we can build open beta within 2-3 months.
We will go live on Ethereum and Rinkeby testnet, with the ability to add further EVM blockchains later.
 
### 4. Is this project open source?

Yes, open source. Drawing on open source work from Paradigm.xyz team.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, happy to share grant reports, code base, results, and final report.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
We started at ETHGlobal hackathon and applied to prizes for this. https://showcase.ethglobal.com/buildquest/dynamic-drops-a3tpt
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Andrey Kochkin | kochkin.andrey@gmail.com | https://github.com/ClockworkOrange605 | Lead Developer
Rafael Hoekstra, PhD | rafael.hoekstra@gmail.com | https://github.com/rdz108 | Product Lead

* How did you learn about our microgrant program?
Karola Kirsanow at Protocol Labs recommended this to us

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
ETH Global BuildQuest hackathon https://showcase.ethglobal.com/buildquest/dynamic-drops-a3tpt

**Comment by ErinOCon** [comment]
Hi @rdz108, This microgrant has been approved! Look out for an email to submit payment details.
