### ISSUE TITLE
Next Step Microgrant: IPFS Stat Viewer v2

### ISSUE THREAD

**Issue by noryev** [ipfs/devgrants#186]
### 1. What is your project? (max 100 words)
 IPFS Stat Viewer is a Chrome Extension that visualizes the files stored on an IPFS Node with D3.js using the file_type and file_size as the sources of data to create a treemap. Our end goal with a collection of added features is to tell stores through art and data, providing meaningful information to anyone using IPFS.

Github: https://github.com/galaxyxone/IPFS-Stat-Viewer

[Try Our Tool in the Chrome Webstore!](https://chrome.google.com/webstore/detail/ipfs-stat-viewer/leoogniilogpecgamlbafoajfcaoddja/related)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
Our app pulls data from a users local IPFS node. With larger amounts of data being saved on IPFS, having tools that help users understand what is saved on local IPFS nodes is crucial. 

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Building off of our previous grant, there are three big features we would like to add. Firstly, we will add another visualization technique such as a Donut Plot comparing the file-type and file-size of a users stored IPFS data. Second, we would like to spend time improving our treemap visualization by adding more supported file-extensions and making it prettier. Lastly, giving users the ability to visualize what is saved on their IPFS Node even when their node is off by saving the stats of their IPFS stored files in the users app extension. There is much more we would like to add that we have outlined in our Github repo as well. The features listed here are the minimum additions we are looking to complete in this micro-grant. Our team is excited to finish the first iteration of our IPFS statistical data viewer and I am looking forward to showing it off at Filecoin Austin in a lightning talk soon.  
 
### 4. Is this project open source?
Yes, MIT, APACHE2

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes

  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
- Have you added your project to the IPFS Ecosystem Directory? -  [YES](https://github.com/ipfs/community/discussions/757)
- [Galaxyx Github](https://github.com/galaxyxone)
- [Galaxyx.io](https://galaxyx.io/)
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Logan Lentz - Lead Developer/Project Manager 
- [Email](llentz@galaxyx.io)
- [Github](github.com/noryev)
 
Alex Mirran - Junior Dev/Project Manager
- [Email](amirran@galaxyx.io)
- [Github](github.com/galaxytwo)  

* How did you learn about our microgrant program? -At the NFT.Storage Austin SXSW Event(2022)

**Comment by ErinOCon** [comment]
Hi @noryev, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by galaxyxtwo** [comment]
Hello! To anyone interested, here's (https://github.com/galaxyxone/ipfsStatViewerChrome/blob/main/stat-viewer-grant-report.md) a grant report/update on IPFS Stat Viewer. There are many updates we plan to add as we continue to support IPFS Stat Viewer!

**Comment by ErinOCon** [comment]
Thanks, @galaxyxtwo! Can you also provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!

**Comment by galaxyxtwo** [comment]
Submitted. Thank you for the support as this project evolves!
