### ISSUE TITLE
[MICROGRANT] Juice

### ISSUE THREAD

**Issue by zdenham** [ipfs/devgrants#187]
### 1. What is your project? (max 100 words)
Juice is a no-code NFT contract deployment platform based on EIP-2535 Diamond Standard

https://github.com/zdenham/diamond-nft

https://juicelabs.io/app

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

We upload NFT metadata / assets to IPFS on behalf of users.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- Improve the user experience of the DApp (this was a hackathon project and is a bit rough around the edges)
- Future proof and deploy facet contracts to mainnet Ethereum to support common NFT contracts
- Implement ERC1155 support in addition to ERC721
- Implement Bulk Metadata Upload To IPFS / Minting functionality 
- Automatic Contract Verification via Etherscan
- Continue to develop new sales mechanics / features (e.g. allowlist support, refundable auctions etc...)
- (Maybe) Implement Marketplace features so customers can host secondary sales on their website

 
### 4. Is this project open source?

The idea is to turn this product into a business, so some of the website / off-chain stuff might not be open sourced in the future, but for now everything is MIT licensed.

The contracts will be MIT licensed.

The product will always be free to use for small artists and creators.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes!
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes!

### 7. Links and submissions

https://showcase.ethglobal.com/hackmoney2022/juice-i6t7q
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Its just me, zdenham1@gmail.com, zdenham, developer

* How did you learn about our microgrant program?

Hack Money 22

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  
Hack Money 22

  * Please link to your hackathon submission

https://showcase.ethglobal.com/hackmoney2022/juice-i6t7q

**Comment by ErinOCon** [comment]
Hi @zdenham, thank you for your microgrant proposal! Will the specific work this microgant supports remain open source?

**Comment by zdenham** [comment]
Hey! Apologies just seeing this--been traveling to some conferences and missed the github notification. We can make the scope of this micro-grant open sourced forever

* 1155 implementation for the diamond standard
* Bulk upload metadata 
* Script to automatically verifiy contract with etherscan
* New Sales mechanics (new contract facets)
* marketplace contracts (the idea is to fork Opensea's seaport)


All of this which falls in scope for the microgrant can be open sourced forever.

**Comment by ErinOCon** [comment]
Hi @zdenham, this grant has been approved! We have sent you an email to proceed with payment details.

**Comment by zdenham** [comment]
Awesome! I'll follow up on the email steps later tonight.
