### ISSUE TITLE
Next Step Microgrant: HouseSec

### ISSUE THREAD

**Issue by Freakytedy18** [ipfs/devgrants#188]
#### HouseSec is a decentralized application to store documents related to the house such as bills and validate them in the background. It uses algorithms to verify the documents and gives transparency in the chain. Application has the capability of storing any type of documents and makes the work easy when someone is not physically present at the house.

 <href> https://github.com/Freakytedy18/HouseSec </href>

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
     **N/A**  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
           **Name**: **Keerthana K**
           **email**: **keerthana18kumaran@gmail.com**
           **Github**: **Freakytedy18**
           **Role** : **FullStack Developer**
* How did you learn about our microgrant program?
     **IPFS Community**
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  **NA**
  * Please link to your hackathon submission
    **NA**

**Comment by ErinOCon** [comment]
Hi @Freakytedy18, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by ErinOCon** [comment]
Hi @Freakytedy18, I hope you are doing well! Can you provide a final grant report for this microgrant? The report template is [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
