### ISSUE TITLE
Next Step Microgrant: Rocket

### ISSUE THREAD

**Issue by Adithya-adi-Menon** [ipfs/devgrants#189]
### 1. What is your project? (max 100 words)
Just like how rockets connect different planets - 'Rocket for IPFS' is a browser extension which connects to the IPFS across different browsers with a dozen of amazing features. Rocket is completely dependency free and works in most of the browsers even without the IPFS client installed on your device!

With Rocket, you can seamlessly make use of the immutable and censorship resistant file system by uploading images from the web to the web3 in just one tap. You can also host your websites, mint NFTs, save media and much more - everything with just a click on your browser extension.

https://github.com/hackyguru/Rocket-IPFShttps://github.com/hackyguru/Rocket-IPFS

https://youtu.be/21zEqOe6FLQ

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

Rocket relies on ipfs-http-client for pushing files into the Inter Planetary File System. We built the browser extension with ReactJS with manifest v2. The media to be uploaded into IPFS can be selected by the user in many ways - you can simply right click on the image/video and press upload to Rocket IPFS or alternatively, goto the browser popup and select the media right from there. The unique CID, the IPFS CDN link and the QR codes are displayed automatically once you select an image. You can share the immutable image along with your friends or even save/bookmark it for later reference with the functionality that we provided. We also added features to mint NFTs by using nft.storage, to backup webpages (webpage archives) using IPFS and to host multi-page static websites using IPFS with a custom domain using decentralized domain providers like Unstoppable Domains, Handshake Domains and ENS.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
*Funding and marketing 'Rocket' as a startup.
*Hiring Experts For Further Enhancements.
*Listing our extension in Chrome Web Store.
*Improving functionalities and adding more features.
 
### 4. Is this project open source?
Yes, The project is completely open source

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes , The report will be produced upon request 
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes, The proposal complies to the Community Code of Conduct.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* Yes , https://devpost.com/software/rocket-for-ipfs
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Member 1: Adithya Menon S
* Email : adithyamenons17@gmail.com 
* Github : https://github.com/Adithya-adi-Menon
* Member 2: Kumaraguru T
* Email : Kumaragurut7@gmail.com
* Github: https://github.com/hackyguru

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Browsers 3000 Hackathon
  
  * Please link to your hackathon submission
  * https://devpost.com/software/rocket-for-ipfs

**Comment by ErinOCon** [comment]
Hi @Adithya-adi-Menon, This microgrant has been approved! Look out for an email to submit payment details.
