### ISSUE TITLE
[MICROGRANT] DStack Protocol

### ISSUE THREAD

**Issue by stackprotocol** [ipfs/devgrants#191]
### 1. What is your project? (max 100 words)
Open Source AWS Standard Decentralized Storage Protocol Built For Developers. DStack is an open source decentralized storage protocol that supports the AWS Standard. DStack will distribute data stored based on the AWS S3 standard in IPFS. It supports IPFS mainet and private networks by the deployment of IPFS nodes. Our goal is to make the life of a developer easier

Github: https://github.com/stackprotocol/DStack
Website: https://dstack.webflow.io

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
DStack Protocol is powered by IPFS
Current use cases of IPFS for Solace are as follows:

*1. Decentralized storage - Store and access data across several servers without a hitch*

*2.  Storing metadata - Your contact list, file sizes, and directory structure can never be seen, even by us*

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

If DStack receives the grant the team will begin working towards the completion of our roadmap which involves:

1. IPFS Enhance security measures (25th June, 2022)
2. E2E Testing (July 15th, 2022)
3. Code Audit (July 30th, 2022)

Since we are working full time and have other responsibilities as well we are actively looking to hire developers to work with us and would also be looking to seek guidance on our project from team Filecoin as we are building directly to promote IPFS culture amongst developers.

Any financial aid from Filecoin/IPFS would allow us to devote more time to continue building DStack.

### 4. Is this project open source?
DStack Protocol is a completely open source project.
The project has license for content (MIT).

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes indeed!, We have also published a road-map (https://github.com/stackprotocol/DStack/blob/main/README.md) which throws light on the product timeline.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes! DStack Protocol complies with the Filecoin Community Code of Conduct. We have experience in building for Web3.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
The project began after seeing the reliance on centralised storage solutions around me. / NOT a part of a hackathon

Twitter - https://twitter.com/DStackprotocol
  
### Additional questions:

Alex Ferguson - Head Of Tech
Contact - dtsackcto@gmail.com
Github - https://github.com/stackprotocol

Gauri Dogra- Head Of Product
Contact - gauridogra2@gmail.com
Github - https://github.com/gauritech

How did you learn about our microgrant program?
Briefing session - Superteam DAO (Bangalore)
Piyush Maheshwari - Dev Advocate (Protocol Labs) encouraged us to pursue this project with full force.

**Comment by ErinOCon** [comment]
Thanks, @stackprotocol! This grant is being reviewed [here](https://github.com/filecoin-project/devgrants/issues/665). We will follow up with you shortly at the linked proposal.

**Comment by stackprotocol** [comment]
@ErinOCon Alright got it! Thank you for informing us.
