### ISSUE TITLE
[MICROGRANT] NFTix - the Eventbrite of blockchain

### ISSUE THREAD

**Issue by jpmonette** [ipfs/devgrants#192]
### 1. What is your project? (max 100 words)
A decentralised event organizing app, for selling NFT-based tickets & enabling a secure resell market - to make it simple - the Eventbrite of blockchain.

https://github.com/jpmonette/nfthack-nfttix
https://showcase.ethglobal.com/nfthack2022/nftix

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
  
IPFS is used to store the metadata of the events created, as well as the image used for the tickets (exposed as NFTs).

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

I would like to achieve the following:

- Support additional features:
  - Upload personalised artwork to be used as NFT image
  - Set total amount of tickets available
  - Custom ticket price
  - Prevent reselling of tickets
- Support the main EVM-compatible chains (Avalanche, Polygon, BSC & Ethereum)
- Make the existing code stable / production ready
- Get a dedicated domain + release to mainnet
 
### 4. Is this project open source?
MIT

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
Yes - https://showcase.ethglobal.com/nfthack2022/nftix
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  - Jean-Philippe Monette, @jpmonette, Engineer
* How did you learn about our microgrant program?
  - Was notified by Jenks Guo
* If your project was created as part of an event or hackathon:
  - NFTHack - Yes - https://showcase.ethglobal.com/nfthack2022/nftix

Thanks!

**Comment by ErinOCon** [comment]
Hi @jpmonette, this microgrant has been approved! Look out for an email to submit payment details.

**Comment by ErinOCon** [comment]
Hi @jpmonette, the kick off email has been sent to the address we have on file. Please feel welcome to reply with any questions.
