### ISSUE TITLE
[MICROGRANT] ORB  (Lensed-In at the GraphHack 2022)

### ISSUE THREAD

**Issue by kkpsiren** [ipfs/devgrants#193]
### 1. What is your project? (max 100 words)

We are building a platform, Orb, on top of Lens Protocol where one can build and connect their digital professional identities. Not only will this help to create communities around work, but it will also allow connection between people and jobs and proof of merit.
We have created a mobile app prototype with On-chain User profiles, Content feed, Jobs, and Learning. The data lives in IPFS/ Filecoin, web interface utilizes fleek. Our positioning with this product is to build something for the community to embrace and start to use daily (with phones) and target new-to-web3 users to enter the ecosystem.

GraphHack:  
https://github.com/Lensed-In/
https://devpost.com/software/lensed-in  
Walkthrough:  
https://www.youtube.com/watch?v=ZVh-hml5EpQ

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

We will use IPFS to host the users profile’s data and metadata, user created content and the jobs created by recruiters or companies, data which we can query via the smart contracts, as well as to hosting our web app via fleek.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

 
We plan to write new Lens modules around it to allow a user to apply/submit and post jobs and gain/show merit that gets stored via Filecoin/IPFS. We need grant to support us building new smart contract modules to efficiently interact with IPFS. This will allow us to publish, store and query data as well as build a smart contract logic to update / "remove" jobs.  Furthermore as we anticipate the data requirements will scale in the future, we will need to find the most efficient way of storing and updating this data using IPFS. We first plan to research how others do these efficiently using IPFS but if needed we plan to build something similar to what Fleek is doing with websites. Currently we are leveraging on pre-existing solutions made by Lens Protocol but we need to add our own functionality to new modules inside it hence the request for grant support.

### 4. Is this project open source?

It is not yet sure whether the whole project gets released as open source. However the smart contract side and the data storage side will be released open source (most likely following the MIT licence).

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes we agree.
 

### 6. Does your proposal comply with our Community Code of Conduct?

Yes it does.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
We met at GraphHack and got the Filecoin/IPFS: Bonus Challenge - Daily Hack prize with https://devpost.com/software/lensed-in

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Nilesh Rathore: Builder/Product Designer/Web3 & Mobile App Developer. 2x former co-founder of web2 startups, served around 100K+ orders. Side project/app has 70K+ downloads.
LinkedIn: https://www.linkedin.com/in/nileshrathore
Twitter: https://twitter.com/nileshrathoree
Github: https://github.com/nileshrathore
nileshrthr@gmail.com

Kimmo Sirén:  Builder / Smart contract / Full-Stack Dev, PhD-level Data Wizard, Bounty Hunter
LinkedIn: http://www.linkedin.com/in/kimmo-siren-ml
Twitter: https://twitter.com/kiptowallet
Github: https://github.com/kkpsiren
kkpsiren@gmail.com

Rohit Kumar: Filmmaker/Content Creator/Growth Hacker/Business Analyst. The combination of engineering and designing has helped Rohit aggregate science and art.
LinkedIn: https://www.linkedin.com/in/rohit-kumar-0443b3183/
Twitter: https://twitter.com/anywayrohu
workwithrohitkr@gmail.com

* How did you learn about our microgrant program?

Via the email from Protocol Labs Prizes, and from Ally Haire(Developer Advocate @filecoin @ipfs)

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
 
 Graph Hack 2022

  * Please link to your hackathon submission

https://devpost.com/software/lensed-in

**Comment by ErinOCon** [comment]
Hi @kkpsiren, thank you for your proposal! Can you confirm that work funded by this microgrant will be open source?

**Comment by kkpsiren** [comment]
Hi @ErinOCon, yes I can confirm that the work funded by this microgrant would be open source.

**Comment by ErinOCon** [comment]
Hi @kkpsiren, this grant has been approved! We will send an email to confirm payment details.
