### ISSUE TITLE
[MICROGRANT] Permanent voting system with partial vote delegation

### ISSUE THREAD

**Issue by SeeeRGo** [ipfs/devgrants#196]
### 1. What is your project? (max 100 words)
 Project is a voting system with delegation, where each voter can choose multiple delegates to represent said voter on per issue basis. Voting per issue is continued while the issue is relevant and done on-chain. Keeping track of who's represented by who is done using OrbitDB 

 https://github.com/SeeeRGo/chainlink-hackathon-project
 https://youtu.be/SJp-EdJQEDE

### Minimum goals:
- Deploy working site for the project
- Add functionality to create issues for voting
- Add basic issue explorer
- Work on the UI and achieve "production ready" quality instead of "napkin drawing"

### Maximum goals:
- Re-implement smart contracts on Solana blockchain
- Work on issue tagging system for future ability to create issues for voting inside smaller groups
- Sorting and filtering for issues
 
### 4. Is this project open source?
 YES

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
 YES
  
### 6. Does your proposal comply with our Community Code of Conduct?
 YES

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* I did, even won one of them apparently, that's how I discovered those initially
  https://devpost.com/software/permanent-voting-with-fractional-vote-delegation?ref_content=user-portfolio&ref_feature=in_progress
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Sergey Mizin, seeergo@yahoo.com, https://github.com/SeeeRGo/, one-man orchestra for now 
* How did you learn about our microgrant program?  - After hackathon there was an email to me saying that I won one of the runner up pooled prizes and there was a link about microgrants as a possible next step and some encouraging words to take that step
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) - ChainLink Spring Hackathon 2022
  * Please link to your hackathon submission - https://devpost.com/software/permanent-voting-with-fractional-vote-delegation?ref_content=user-portfolio&ref_feature=in_progress

**Comment by SeeeRGo** [comment]
@ErinOCon Hi I haven't had any updates from this yet and today I pancked when I couldn't find this at filecoin devgrants page
So I created another one one thinking that I didn't submit this one initially
Here's the new one https://github.com/filecoin-project/devgrants/issues/743
Which one should I keep open then. Also would you be so kind to share any updates on the review status?

**Comment by ErinOCon** [comment]
Hi @SeeeRGo, thanks for checking in! I have provided an update [here](https://github.com/filecoin-project/devgrants/issues/743).
