### ISSUE TITLE
[MICROGRANT] <Naksh - NFT Marketplace integrating NFT.STORAGE for EVM Integration>

### ISSUE THREAD

**Issue by tcsrilakshmi96** [ipfs/devgrants#198]
### 1. What is your project? (max 100 words)
Naksh is an NFT Marketplace that is currently built on NEAR protocol but we are working on an EVM Integration for the marketplace to make it multi-chain. For the NEAR protocol we have used IPFS (Pinata) to store the NFTs and for the EVM integration we will be using NFT.STORAGE. We are using IPFS/NFT.STORAGE for storing all the NFT's Images and the Metadata

 https://github.com/NakshOrg/naksh-marketplace-react 
 https://naksh.org/ 

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
We are using IPFS/NFT.STORAGE for storing all of the NFT's Images and Metadata, as IPFS is a decentralised storage system, it will be very helpful for us to keep our NFT's data forever. We decided to use IPFS because of it being a decentralised storage solution, we are a NFT Marketplace and the most important thing for us is to store our NFT Data securely and it should be available forever not controlled by single entity and IPFS provides all of that. Also it is more decentralised and permission less than any solution that exists in the market, so it was an obvious choice for us to use IPFS with NFT.STORAGE. 
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We are seeking the grant to integrate the EVM chains onto our platform and use NFT.STORAGE to store the images and metadata for all of the EVM Integrations. 
We are working on the designs for secondary marketplace and wallet Integration to make the platform multi-chain. 
Our testnet with EVM integration will be launched by the first week of July. 
We are going to have 100 users test the testnet for 2 weeks. 
We will incorporate the changes and work on launching the main net by the first week of July. 
 
### 4. Is this project open source?
At the moment the project is partially open sourced we are working towards a full open source project and obtaining a licence for the same. We will update it once we receive the licence. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, we are open to give a detailed report milestone to milestone and a final report at the end of the timeline.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes, the project is compliant to Filecoin's code of Conduct.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  Yes, our project began at a NEAR Hackathon that happened on May 2021.
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
 - Srilakshmi TC , srilakshmi@naksh.org, Tcsrilakshmi96 , Co-founder. 
 -Nivedita Vivek, Nivedita@naksh.org, nivedita2208, Co-founder. 
 -Abhishek Venunathan, abhishek.venunathan@gmail.com, AbhishekVenunathan , Lead Back End Engineer. 
 - Hemanth Kumar, hemanthkumaran007@gmail.com , Hemanthkumaran , Lead Front End Engineer.
 - Satyam Kulkarni, punekar.satyam@gmail.com , sk1122 , Full Stack Develooper. 
* How did you learn about our microgrant program?
- Through a team member of IPFS Filecoin team. 
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  - NEAR Hackathon - 2021
  * Please link to your hackathon submission
https://github.com/NAKSH-ORG/NAKSH-INITIAL

**Comment by tcsrilakshmi96** [comment]
@ErinOCon Hey Erin, how are you doing? 
Just wanted to know if the proposal is being reviewed and what about be the expected timeline for response ?

**Comment by ErinOCon** [comment]
HI @tcsrilakshmi96, thank you for this proposal! Open source work is a key criteria point of this proposal. Can you confirm the work outlined in this proposal will be fully open source?

**Comment by tcsrilakshmi96** [comment]
Hey @ErinOCon, Thank you so much for your response. Yes, our product is fully open source right now, but we haven't obtained a licence yet, we are working on obtaining it.

**Comment by ErinOCon** [comment]
Hi @tcsrilakshmi96, this grant has been approved! We will send an email to confirm payment details.

**Comment by tcsrilakshmi96** [comment]
@ErinOCon Thank you for the approval. Looking forward to the email :)
