### ISSUE TITLE
[TRACKING] IPFS mobile design research and guidelines

### ISSUE THREAD

**Issue by parkan** [ipfs/devgrants#20]
Tracking issue for 

https://github.com/ipfs/devgrants/blob/master/targeted-grants/IPFS-mobile-design-research.md

and

https://github.com/ipfs/devgrants/blob/master/targeted-grants/IPFS-mobile-design-guidelines.md

**Comment by Schwartz10** [comment]
Hey @parkan, I noticed Molly made a suggestion for grant proposal formatting: https://github.com/ipfs/devgrants/pull/18#discussion_r375524431

Since the PR was already merged, do you want me to submit another with the format updates?

**Comment by parkan** [comment]
@Schwartz10 I can just update the formatting if that's ok with you

**Comment by parkan** [comment]
(deleted comments above as they are attached to the wrong issue)

**Comment by mishmosh** [comment]
Doing a bit of issue cleanup. @autonome or @jessicaschilling do you know if this project has been completed?

**Comment by autonome** [comment]
Can close!

Published:

* https://blog.ipfs.io/2020-04-10-ipfs-mobile-design-research/
* https://blog.ipfs.io/2020-04-24-ipfs-mobile-design-research-findings/
