### ISSUE TITLE
Gideon Association 

### ISSUE THREAD

**Issue by GideonAssociation** [ipfs/devgrants#205]
### 1. What is your project? (max 100 words)

Our project is Gideon, a streaming voting, and gaming platform for the battle rap industry. We solve the problem of there being no fair voting mechanism for the entire battle rap industry to fairly decide the outcome of rap battles. We solve that problem by providing a decentralized voting mechanism using DLT to battle rap leagues worldwide via our platform. With these fair votes and statistics, we can now introduce betting and fantasy gaming online to the battle rap industry. 

IPFS will be the storage system used to store the videos on our platform which is the core content of our application. IPFS will also be used to store our in-app NFTs that represent battle rappers to be used in our fantasy gaming portal.

 https://github.com/GideonAssociation
 

https://www.figma.com/proto/ke1gjWSQR4M446ixf3mT2g/Gideon?node-id=7818%3A0&scaling=min-zoom

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

We will use IPFS/web3.storage for decentralized cloud storage of our still assets. Those still assets are currently videos, NFTs, and merchandise. All of which can be stored on IPFS and accessed via a simple API call. This would enable our application to run much more efficiently. 

IPFS also provides a safe and secure way to store our videos which are the core content of our platform,  as well as remotely store thousands of NFTs from our fantasy gaming portal that will have monetary value, so it is necessary to be in a safe, secure and accessible place.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

In the Hedera Hackathon 22, we built several contracts, one being our decentralized voting contract where votes are recorded on a distributed ledger and another being an NFT contract wherein the metadata is stored on IPFS. For the sake of IPFS, we will be building out the NFT contract into a full fantasy gaming portal wherein users can buy, sell, and trade NFTs with the goals of acquiring the best performing set of NFTs to win a prize from our weekly, monthly, or annual competitions. These NFTs represent active battle rappers. 

With this grant, we will be able to devote full-time to; build out web3.storagebof our videos, build out the web3.storage for the NFT based fantasy gaming portal of our application as well, develop the front end UX/UI of the fantasy gaming portal, cover the costs of hosting and maintenance of the software, purchase laptops to upgrade our organizational operations, cover any licenses or legal fees that may be applicable to operating a fantasy gaming or sports betting platform. We look to immediately partner with battle rap leagues to test our product upon completion. 

We are asking for a grant of $50,000 USD in Filecoin. 

### 4. Is this project open source?

Yes, MIT.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
 Yes. 
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes. 

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

Yes. We placed as a finalist. 
https://devpost.com/software/gideon-zqxfaj

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Jahmeke Rodriquez
[thegideonassociation@gmail.com](mailto:thegideonassociation@gmail.com)
Founder/CEO
https://github.com/GideonAssociation

Stephen Segun
[ogarstephen98@gmail.com](mailto:ogarstephen98@gmail.com)
Programmer/Developer
https://github.com/stevegee1

* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

We learned about the microgrant program directly through Protocol Labs when they informed us on how to claim our prize from the Hedera Hackathon.
"Hedera Hackathon 22" 
https://devpost.com/software/gideon-zqxfaj

**Comment by ErinOCon** [comment]
HI @GideonAssociation, thank you for your proposal. Do you have an open repo with code for this project?

**Comment by ErinOCon** [comment]
Hi @GideonAssociation, thank you for your reply! Can you try sending a new link? Unfortunately, this link is not working.

**Comment by ErinOCon** [comment]
Hi @GideonAssociation, I hope you are doing well! Any new updates on the link?

**Comment by ErinOCon** [comment]
Hi @GideonAssociation, do you expect an updated link will be available this week?

**Comment by GideonAssociation** [comment]
Hey Erin,

I just tried this link and it should work.

https://github.com/GideonAssociation/Hedera22_hackathon_Gideons_Streaming_and_Gaming_DApp

Let me know if it doesn't.

JR

**Comment by ErinOCon** [comment]
Hi @GideonAssociation, unfortunately, this link does not work.

**Comment by GideonAssociation** [comment]
Hey,

Sorry for that. My back end developer was able to fork a copy of the repo.
Please let me know if this works.

https://github.com/stevegee1/Hedera22_hackathon_Gideons_Streaming_and_Gaming_DApp

SN: Just to add, we have been working on this company for over 3 years.
We've tried venture capital, crowdfunding, NFT launches, angels,
accelerators, etc. And for some reason, we keep being denied access to
funding.

Blockchain and crypto paved the way to empower the startup in face of the
incumbents. And I strongly believe that with funding from IPFS... that we
can show the power of the space in face of what may be unfair denial of
access to funding. We have a quality project and would appreciate any level
of funding but ideally, a seed stage amount. We have more documentation if
needed.

Best,

JR


https://github.com/stevegee1/Hedera22_hackathon_Gideons_Streaming_and_Gaming_DApp

**Comment by ErinOCon** [comment]
Hi @GideonAssociation, thank you for the additional background! Unfortunately, the link is still not working. Is this a public link?

**Comment by GideonAssociation** [comment]
Hey,

I just made it public. Hopefully that solves it.

Please let me know.

**Comment by GideonAssociation** [comment]
Hey, following up to see if you were able to access the repository.

Best,

JR

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by GideonAssociation** [comment]
Thank you very much!

We greatly appreciate it. We will be sure to follow up within the 3 month
timeline.

However, when I log in to accept the funds, the option isn't there. Only
the request from the Hedera Hackathon.

**Comment by GideonAssociation** [comment]
Greetings Erin,

I am following up about our dev grant. We proceeded with the payment portal
and were wondering when we could expect the payment? We are eager to get
started.

Best,

JR

**Comment by GideonAssociation** [comment]
Hi Eric,

thank you so much for responding.

I reached out to GitHub and they have updated the flag on the account. It
should work now. In regards to the amount, we were applying for $50,000
grant for the Gideon project.

We are grateful that you would consider us.

Best,

Jahmeke



https://github.com/GideonAssociation/Hedera22_hackathon_Gideons_Streaming_and_Gaming_DApp

**Comment by GideonAssociation** [comment]
Greetings Erin,

We are following up about our micro grant. We still have not received the
payment in our crypto account. I believe it said it would arrive by the
19th of October.

We are eager to get started as soon as possible! If you could please check
on this for us, would be great.

Best.

**Comment by GideonAssociation** [comment]
Please get in touch with me Sir. We are waiting to start our project to
complete the micrograms in time but have not received the funds yet.

**Comment by ErinOCon** [comment]
Hi @GideonAssociation, I am currently reviewing the delayed payment and will be in touch with an update by tomorrow. In regards to your previous comment, can you confirm where you are applying for the $50k grant?

**Comment by GideonAssociation** [comment]
Thanks so much. Looking forward to your message. And yes, we were applying
for the $50k grant originally.

**Comment by GideonAssociation** [comment]
Hey Erin,

I am following up about the update on the delayed payment, you said you
would reply today.

Only reason I’m pressing the issue is because I was personally invited to
the IPFS conference in Lisbon and was going to use some of this payment to
fund the trip.

I do not want to miss out on such a great opportunity, especially one where
your fellow IPFS members took the liberty to invite me. If there is anyway
you can expedite the process, it would be extremely helpful right now!

Best,

JR
