### ISSUE TITLE
[MICROGRANT] Discharge: Free, secure and unlimited data storage

### ISSUE THREAD

**Issue by pythonicode** [ipfs/devgrants#207]
### 1. What is your project? (max 100 words)
My project is a cross platform desktop application designed to put the power of Filecoin and IPFS in the hands of the everyday person. The application is similar to other data storage applications like Dropbox or Google Drive and allows anyone to easily upload documents, folders, videos and other content to IPFS. The content is thoroughly encrypted before being uploaded so people can store private data on the network.

https://github.com/pythonicode/discharge

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

I used Estuary to upload encrypted files to IPFS and store them in organized collections. Everything in the application interacts directly from the client to Estuary does not use a 3rd party server to store any information so it is completely decentralized.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Currently the version on GitHub has a few bugs, mainly concurrency issues that have to do with dealing with the user's filesystem. Using the microgrant I would like to fix these bugs and finally release the application to the public for free so that anyone can start storing files for free, directly from their desktop. Then, if time permits, I want to migrate the application from Electron to a Rust app so that it runs way faster and, uses fewer resources in the background.
 
### 4. Is this project open source?
Yes it is open source. More information on the GitHub page.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes, it is in compliance.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes, I won a prize in the Chainlink hackathon:
https://devpost.com/software/discharge

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Just 1 team member for now: Anthony Riley (pythonicode) 

* How did you learn about our microgrant program?
via email after hackathon.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
Chainlink

  * Please link to your hackathon submission
https://devpost.com/software/discharge

**Comment by ErinOCon** [comment]
Hi @pythonicode, this grant has been approved! We will send an email to confirm payment information.
