### ISSUE TITLE
Next Step Microgrant: Free-Dao Tooling

### ISSUE THREAD

**Issue by Free-Dao** [ipfs/devgrants#209]
### 1. What is your project? (max 100 words)
Free-Dao is a Dao tool for implementing POAP based gating for DAO's.
The vision for this project is very straightforward and utilitarian
1. DAO's should be easily be able to gate their communities using POAP's / NFT's
2. Discord Admins can mint NFT's for their DAO's on an IPFS hosted website
3. These POAP's / NFT's can be used to unlock specific discord memberships and features
4. Free-Dao Dashboard can be used to do community airdrops as per the membership declared by the POAP/NFT

https://github.com/Free-Dao/Free-Dao
Prototype - https://drive.google.com/file/d/1zehkrw39y8EguJUI6W9FaCZbK2l91Ax6/view?usp=sharing

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
1. All POAP's and NFT's are stored on NFT.storage and any relevant DAO related documentation will be stored on Web3.storage
2. DAO level data, including UX related data for DAO's are stored on Tablelands (Migration is complete)
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. Things `TODO` are marked on our repository - https://github.com/Free-Dao/Free-Dao
2. Work on smart-contracts to enable more control to DAO admins
3. Integrate with more chains
 
### 4. Is this project open source?
Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, we do
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
*Ramiza Shaikh* - Web3 Developer - ramiza.shaikh.95@gmail.com 
*Sara Ali* - Web3 Fullstack Developer - imsaraali1992@gmail.com
Team Email - free.dao.community@gmail.com

* How did you learn about our microgrant program?
ETHGlobal Hackathon
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @Free-Dao, thank you for our proposal and for your patience with our review. This grant has been approved! We will send an email to confirm payment information.

**Comment by ErinOCon** [comment]
Apologies, @Free-Dao! The final report can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
