### ISSUE TITLE
[MICROGRANT] A social app to connect crypto people

### ISSUE THREAD

**Issue by jeff0723** [ipfs/devgrants#211]
### 1. What is your project? (max 100 words)
I am building a web3 social app for crypto people to connect with each other. I use IPFS for media file and web hosting, and we will have more advanced use case if the traffic increase.

[Github](https://github.com/jeff0723/Tind3r)
[DEMO](https://ethglobal.com/showcase/tind3r-i7rtt)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
I use ipfs for storing user profiles and for content user posts including photos, videos, and potentially streaming videos.
Also libp2p might be used for message feature.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
The improvement with the grant will be:
1. Develop a mobile version : develop react native mobile app and integrate with IPFS tech stack
2. Advance recommendation system: develop recommendation system with constant synchronization with all potential user lists. 
3. Message: remove xmtp for message and use libp2p for messaging.
 
### 4. Is this project open source?
Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:[Hackfs 2022](https://ethglobal.com/showcase/tind3r-i7rtt)
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
1. Jeffrey Lin, jeffreylin0723@gmail.com, @jeff0723, PM and developer
2. Justa Liang, justaliang@protonmail.com, @JustaLiang, smart contract & backend developer
3. Greg Shen gregshen0925@gmail.com, @gregshen0925, researcher
* How did you learn about our microgrant program? From hackathon 
* If your project was created as part of an event or hackathon:
  * What was the name of the event? Hackfs2022
  * Please link to your hackathon submission: [Hackfs 2022](https://ethglobal.com/showcase/tind3r-i7rtt)

**Comment by ErinOCon** [comment]
Hi @jeff0723, it looks like this proposal is a duplicate with this [item](https://github.com/filecoin-project/devgrants/issues/836). This issue has been closed.
