### ISSUE TITLE
[MICROGRANT] DriveClean.io

### ISSUE THREAD

**Issue by billzhengC** [ipfs/devgrants#215]
### 1. What is your project? (max 100 words)

We are building DriveClean, a play-to-earn lifestyle app that incentivizes climate-positive behaviors. 

Users can bring their qualified real-world action on chain as climate credentials, while earning tokens and enjoying benefits from brand partners.

We are starting with charge-to-earn for electric vehicle drivers, with additional rewards for clean energy charging. Currently on Solana + IPFS. Overtime, we will incorporate different types of on-chain and off-chain climate credentials. Read our [whitepaper](https://whitepaper.driveclean.io/) for more.

Github: https://github.com/driveclean/driveclean-ipfs
Website: https://driveclean.io/
Whitepaper: https://whitepaper.driveclean.io/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

The entire climate credentialing layer will be built on IPFS. Specifically, users' climate-positive actions will be recorded on IPFS (e.g., stats on EV charging). 

This ensures the project's interoperability - any climate or credential project can directly access these data and build atop.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

This grant will help us go live on Solana mainnet in 3 months (currently on devnet). 

Specifically, we'd like to complete the following:
- Robust charge-to-earn mechanism for Tesla drivers
- NFT airdrops for early users
- Working prototype of climate credentialing system
- Extensive testing before releasing on mainnet

### 4. Is this project open source?

Yes. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
 
This project started at Sustainable Blockchain Hackathon and won IPFS Runner-up prize.
https://gitcoin.co/hackathon/sustainable/projects/16159/driveclean

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Bill Zheng, b@driveclean.io, https://github.com/billzhengC, co-founder
Liu Yang, bb@driveclean.io, https://github.com/ffy, co-founder

* How did you learn about our microgrant program?

Got an email after winning the hackathon prize.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

Sustainable Blockchain Hackathon
https://gitcoin.co/hackathon/sustainable/projects/16159/driveclean

**Comment by billzhengC** [comment]
Hello @ErinOCon I'm wondering if there's any update on our application? Thanks.

**Comment by ErinOCon** [comment]
Hi @billzhengC, thank you for your patience with our review! It looks like the source code for this project is under a different handle. Can this handle comment on this issue with a quick description of your affiliation with the work?

**Comment by driveclean** [comment]
> Hi @billzhengC, thank you for your patience with our review! It looks like the source code for this project is under a different handle. Can this handle comment on this issue with a quick description of your affiliation with the work?

Hi @ErinOCon, this handle is created by @billzhengC for works related to DriveClean. Thanks

**Comment by billzhengC** [comment]
@ErinOCon Done

**Comment by ErinOCon** [comment]
This microgrant has been approved! Look out for an email to confirm payment details. 
 
Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
