### ISSUE TITLE
Next Step Microgrant: literals

### ISSUE THREAD

**Issue by hfccr** [ipfs/devgrants#217]
### 1. What is your project? (max 100 words)

Literals is a protocol to create and distribute provable facts to enable trust. It uses IPFS, NFT.Storage, Lit Protocol and Covalent to allow
* anyone to publish a set of rules or access control conditions
* any web3 platform to choose, discover and select relevant rules
* any user to generate, refresh and store proofs for each rule
* any user or platform to retrieve and verify proofs for any rule for any user

https://github.com/hfccr/literals

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
IPFS through NFT.Storage will act as the sole storage for access control conditions which are the rules against which users can get verified. This information will be linked through CIDs in a separate document to aid discovery. Proofs against an access control condition, once generated will be published on IPFS through OrbitDB.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

* Storing access control conditions document only on IPFS using NFT.Storage. Currently, IPFS is used as a backup.
* Linking CIDs of all access control conditions to enable discovery. Currently there is not mechanism for discovery.
* Storing proofs against an address only on IPFS using OrbitDB
* Creating a way to obtain all proofs for an address. Currently, proofs are not discoverable by any entity as the CIDs are random.
* Creating an incentive based platform for users to refresh their tokens
* Creating a platform for platform owners to discover and choose access control conditions to use on their site
* Creating a React SDK for displaying literals on a platform
* Creating an extension to enable retrieving all verifying all proofs for an address and injecting it in the webpage
 
### 4. Is this project open source?
Yes. Literals is and will be completely open source.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes. Reports will be shared periodically, upon request and at the end of the three month period.

  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes it does and will throughout the lifetime of the project.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
This project began at ETHGlobal HackFS 2022 and it was submitted for IPFS & Filecoin prizes. It can be found at https://ethglobal.com/showcase/literals-v22zq. It won the IPFS daily hack prize and Covalent best use prize.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
hfccr, hfccr@outlook.com, https://github.com/hfccr, Solo Founder & Full Stack Developer
* How did you learn about our microgrant program?
I learnt about the microgrant program through the email I received for the prize distribution.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
   ETHGlobal HackFS 2022
  * Please link to your hackathon submission
   https://ethglobal.com/showcase/literals-v22zq

**Comment by ErinOCon** [comment]
Hi @hfccr, thank you for your proposal! This grant has been approved. We will send an email to confirm payment information.
