### ISSUE TITLE
[MICROGRANT] dotAlgo

### ISSUE THREAD

**Issue by IKalonji** [ipfs/devgrants#219]
### 1. What is your project? (max 100 words)

dotAglo is a human-readable NFT domain and profile avatar creator, indexer and resolver for Algorand blockchain accounts using IPFS for storage, built for developers to easily integrate into their applications. Making it easier for users to use the address domain extenstions instead of long and unreadable account addresses.

The project is in the process of being updated to include Decentralized Indentity in the NFT mint so that 
users/resolvers can use their dotAlgo address to provide proof of humanity in gated communities.

[Github-repo](https://github.com/IKalonji/DotAlgo)
[Hackathon-demo](https://www.youtube.com/watch?v=GOsnMrG4cBE)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

IPFS through Web3.Storage is used for the storage of the users profile avatar, metadata. The addition of the Decentralized Indentity will also require the metadata of the DID to be stored on IPFS. We will however be changing from Web3.Storage to NFT.Storage since we realized that this is more suited for NFT's
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

I am working on implementing the following features to the dApp:

- Adding Soulbound DID support to the NFT domain minted by allowing users to verify humanity prior to minting and storing the metadata so that when dotAlgo address is resolved users can also prove humanity without disclosing personal information.

- Removing transferrability of the minted domain token so that it cannot be traded.

- Adding support for multiple addresses so that users with more than one Algorand address can link all their addresses to a single DID if they would like to.

- Improved UI/UX for the minting process. 
 
### 4. Is this project open source?

The project is open sourced under the MIT license, [here](https://github.com/IKalonji/DotAlgo/blob/main/LICENSE.txt)

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

I agree to provide the required updates on the progress of the application and report after the grant period.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes, the application complies with the Community Code of Conduct 

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

The project was a runner up at the L2 Rollathon hackathon hosted by Gitcoin and I submitted for the prize:

Gitcoin bounty https://gitcoin.co/issue/28834
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Developer: Issa Kalonji
Email: IKalonji@student.wethinkcode.co.za
Github: https://github.com/IKalonji
Role: Solo hacker, I built the project on my own as part of the hackathon.

* How did you learn about our microgrant program?

In the IPFS bounty managers mentioned in the prize announcement that we could apply for the Next Steps Micro Grant when adding additional features to our dApps.

* If your project was created as part of an event or hackathon:

 Built as part of the L2 Rollathon by Gitcoin

  * Please link to your hackathon submission

Hackathon submission:
Gitcoin: https://gitcoin.co/hackathon/Rollathon/projects/15245/dotalgo
Github: https://github.com/IKalonji/DotAlgo

**Comment by ErinOCon** [comment]
Hi @IKalonji, thank you for your patience with our review. This grant has been approved! Look out for an email to confirm payment details.

**Comment by IKalonji** [comment]
Thank you @ErinOCon

**Comment by ErinOCon** [comment]
Hi @IKalonji, I hope you are doing well! Will the report for this project be available soon?
