### ISSUE TITLE
Next Step Microgrant: Polydocs Immutable Dynamic Documents EIP

### ISSUE THREAD

**Issue by rhdeck** [ipfs/devgrants#223]
### 1. What is your project? (max 100 words)
Smart contracts are increasingly used for managing the allocation of digital assets. These assets are more complex than the cash or deeds we sometimes use for analogies. Intellectual property involves rights and responsibilities. Financial instruments require acceptance on both sides. Communities need agreement on government by norms and rules.

The articulation and acceptance of these terms should be a first-class consideration for those creating digital assets and services. That's why we made Polydocs.

https://github.com/statechangelabs/polydocs
https://polydocs.xyz

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

The core insight of Polydocs is at the intersection of the decentralized ledger and decentralized storage. Every smart contract should go with a smart document that regulates the responsibilities of parties involved in it.

The purpose of the Polydocs EIP is to standardize the way these are connected, and to demonstrate IPFS CIDs as the best practice for defining immutable, trustable documents. 
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We created the Polydocs technology and some template contracts, but to make this truly useful it should be a standard that everyone can incorporate into their smart contracts. We want to submit this as an open-source Ethereum Improvement Proposal so that this functionality can be composed into others. Our Polydocs contracts would be offered as a reference, but be open-source so everyone can use this technology without concern for their intellectual property rights. 
 
### 4. Is this project open source?
Yes, Polydocs code is under MIT License, and the EIP is definitely open-source

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes. We plan to complete this work in October. 
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes. 

### 7. Links and submissions
We submitted to HackFS 2022 and placed as a finalist https://ethglobal.com/showcase/polydocs-1oas6. 
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
   1. Ray Deck ray@raydeck.com  @rhdeck Developer
   2. Akshay Rakheja rakheja.akshay@gmail.com @akshay-rakheja Developer
 
* How did you learn about our microgrant program?
We participated in an earlier hackathon with a different team where we won an IPFS prize and participated in the next-steps program. We are really excited about the potential for extending our work on this on the open-source side to make a difference for the web3 community

* If your project was created as part of an event or hackathon:
We submitted to HackFS 2022 and placed as a finalist https://ethglobal.com/showcase/polydocs-1oas6.

**Comment by rhdeck** [comment]
Is this in the correct place? Based on action I saw elsewhere I posted this same request in filecoin devgrants. We can close it here if it is more appropriate there: https://github.com/filecoin-project/devgrants/issues/917

**Comment by ErinOCon** [comment]
Hi @rhdeck, thank you for your patience with our review! I have closed this item as it is currently being reviewed [here](https://github.com/filecoin-project/devgrants/issues/917).
