### ISSUE TITLE
[MICROGRANT] Decencol, a decentralize collaboration tool for teams

### ISSUE THREAD

**Issue by Cuttlas90** [ipfs/devgrants#224]
### 1. What is your project? (max 100 words)

The goal of project is to build a decentralize collaboration tool for teams. Using this project, a team can create a file and share it with other teammates teammates can add their notes to the file and save it, owner will have the ability to see the changes and who did that. Owner can consider the change and apply it to the file or delete it. For login and sharing file team members just need a Metamask and Ethereum address.
[Github Repository](https://github.com/Cuttlas90/decencol)
[Demo Website](https://decencol.cuttlas.app)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
IPFS is core of this project, decencol will store every file on IPFS network, after changing or modifing the file, it will be replace with older file, project file will only save ipfs address in database not the main file. because some file are important for their owner, in next version project can use filecoin network for pinning the files. at the end for full decentralization the database can migrate to orbitDB.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

These changes will be applied to project:

- multi-share: the current version gives owner the ability of sharing his/her file with one co-worker, multi-share feature will give owner ability of sharing the file with more people, it means bigger teams can collaborate on file at the same time.
- Adding comparison feature (v.1): owner and his/her co-workers can work on a same document. After a co-worker made some changes and save the file, the original and modified files are compared line by line for finding changes, found changes will be added to the original file as a text, after that owner can see the file and its change, owner can modify the document based on proposed changes and save the file as a final version. In this version only text differences can be found.
- migrating from web3.storage to ipfs.js: to build the MVP we used web3.storage but for further development we need to interact with IPFS directly.
 
### 4. Is this project open source?

yes this project will be released under GPL license for code.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

yes, I agree to share grants reports upon requests.

### 6. Does your proposal comply with our Community Code of Conduct?

yes, it does.

### 7. Links and submissions

no, its not related to a hackathon
  
#### team members:

- mohsen, Product Manager, mohsenbarekati@gmail.com, https://github.com/Cuttlas90
- Ali, Backend Developer, ali.mhossaini@gmail.com, https://github.com/amhossaini
- Shahed, FrontEnd Developer, shahedmoez@gmail.com,https://github.com/shahedmoez

#### How did you learn about our microgrant program? 

I was reading about ipfs and find out about grant program.

#### If your project was created as part of an event or hackathon? 

No It is not part of an event

**Comment by ErinOCon** [comment]
Hi @Cuttlas90, thank you for your proposal! This grant has been approved. Look out for an email to confirm payment details.

**Comment by Cuttlas90** [comment]
Hi @ErinOCon , thanks
Of course, we are in last steps, I will provide final report and the lunched product very soon.
