### ISSUE TITLE
Next Step Microgrant: <KEZAYYA - Web3 File storage and sharing platform> 

### ISSUE THREAD

**Issue by holyaustin** [ipfs/devgrants#228]
### 1. What is your project? (max 100 words)
Data is now a technological resource as crude oil or gold is a natural resource. Everyday, internet users create and generate data on the fly. These data are usually in files of various formats and they need to store them safe and securely. Web2 has such services as Google Drive, One drive, dropbox,  Tresorit, Pcloud etc. As the Blockchain ecosystem continues to grow and gain adoption, there is a need for a web3 version of file storage and sharing for clients and organizations. This is where KEZAYYA comes to play. KEZAYYA is a web3 project with the aim of helping users store files and share them in a user-friendly manner. Files can be made private or public so you can share them with others.

[Link to public Github repo](https://github.com/holyaustin/kezayya) 
[Link to website, if applicable](https://kezayya-nnb3b.spheron.app/) and  (https://youtu.be/4hIymL5lCs0)
[Link to video demo, if applicable](https://youtu.be/4hIymL5lCs0)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
The front-end was designed with Next.js framework. IPFS / Filecoin was the principal technology used in this project due to its nature as a file storage platform. Users' profile are stored on IPFS using NFT.Storage. Users' metadata and profile images will be stored in a decentralized manner using NFT.Storage. Files are also stored on IPFS using NFT.storage. Metadata URI is stored on-chain. ERC721 standards were used.  Coinbase wallet and Wallet connect were integrated with metamask to give users a wide variety of wallets to connect with. The project was designed to be responsive so that whichever device you connect with, you will have a great user experience.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
* Writing better metadata for users' profiles and storing with nft.storage.
* Migrating to ERC721a for lower gas consumption.
* Cleaning up the NFT smart contract and optimizing the smart contract for better performance
* Working on the folder upload so that file uploaded can be viewed also from the dashboard
* Integrate Coinbase wallet and Wallet connect to increase the variety of wallets 
* Improve the frontend to a better user interface
 
### 4. Is this project open source?
Yes, MIT+Apache.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
Web3 Infinity Hackathon
*  https://devpost.com/software/kezayya
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Augustine Onuora, holyaustin@yahoo.com, @holyaustin – Sole developer.
* How did you learn about our microgrant program?
I was emailed about it after the hackathon
* If your project was created as part of an event or hackathon:
[Devpost Web3 Infinity Hackathon](https://web3infinityhackathon.devpost.com/)
https://devpost.com/software/kezayya

**Comment by ErinOCon** [comment]
Hi @holyaustin, thank you for your proposal! Before proceeding with our review, the following information is needed:

- **Additional detail regarding the next steps of your project.** Please go into more detail with each of the provided points and briefly explain the end impact it will bring to your project. 
- **A final report for each of your previously approved projects.** I have provided the reporting template in each project issue. 

Please let me know of any quesitons!

**Comment by holyaustin** [comment]
Hi, Eric

I once asked if there is no way to show that I have completed my project with the grant. i will immediately use the template to report on the previous project. 

Secondly, I didn't understand what you meant by "Additional detail regarding the next steps of your project. Please go into more detail with each of the provided points and briefly explain the end impact it will bring to your project."

Can you break it down to how you want me to answer the additional details?

I am already working on the previous reports.



thanks

Augustine







On Friday, October 7, 2022 at 06:25:16 PM GMT+1, ErinOCon ***@***.***> wrote: 







Hi @holyaustin, thank you for your proposal! Before proceeding with our review, the following information is needed:

     
    * Additional detail regarding the next steps of your project. Please go into more detail with each of the provided points and briefly explain the end impact it will bring to your project.
    
    * A final report for each of your previously approved projects. I have provided the reporting template in each project issue.
    

Please let me know of any questions!

**Comment by holyaustin** [comment]
Additional detail regarding the next steps of your project.

I don't know if I understood what you meant by the next step of my project but let me answer that Kezayya is a project that intends to help users store their files in a user-friendly manner like that of web2 counterpart (Like dropbox, google drive, etc).  A subscription service for large data cap will be introduced in the DApp so users can subscribe for large data storage.

**Comment by ErinOCon** [comment]
Thanks, @holyaustin! Below are more specific questions that may be helpful: 

- How will you improve the metadata for user profiles?
- How will the smart contract performance improve?
- How will you improve the user interface?

Please let me know if you have additional questions!

**Comment by holyaustin** [comment]
Hi,

Thanks for reaching out. To answer your question, 
1. Users profile is paramount to this DApp. Storing these profile details on-chain will be costly as the project grows. This is why IPFS/Filecoin was used to make store users' metadata. We will add more profile fields to collect more user data.

2. We shall be cleaning up the smart contract and optimizing the code for efficiency. Secondly, The smart contract should be able to track individual files stored and when it was stored which is currently not supported right now. Furthermore, the smart contract will integrate the ability to receive payment for premium subscribers who would like to exceed the free cap. This is not currently supported now.

3. The user interface and user experience will be worked upon. We shall make sure the Dapp is responsive and mobile compliant as most users will be accessing the DApp with their mobile gadgets. 

4. Finally, I am asking the filecoin team if there is a way I can replace the file URL stored on filecoin with a custom URL. if that is possible, it would be implemented so that when you share a file, it carries the domain URL. 

I would gladly answer any further questions. 

Thanks


Augustine








On Thursday, October 20, 2022 at 02:01:23 PM GMT+1, ErinOCon ***@***.***> wrote: 







Thanks, @holyaustin! Below are more specific questions that may be helpful:

     
    * How will you improve the metadata for user profiles?
    
    * How will the smart contract performance improve?
    
    * How will you improve the user interface?
    

Please let me know if you have additional questions!

**Comment by ErinOCon** [comment]
Hi @holyaustin, thank you for your patience with our review. We will not be moving forward with a grant for this project, but wish you the best as you continue building!
