### ISSUE TITLE
On-Boarding Medium Blogging for IPFS 

### ISSUE THREAD

**Issue by ARUNMANNURU** [ipfs/devgrants#230]
# Open Grant Proposal: `Create a Medium Blogging Account for IPFS`

**Name of Project: On-Boarding IPFS into Medium**

**Proposal Category:**  `devtools-libraries`, `integration-adoption` , `docs` , `community`

**Proposer:** `[https://github.com/ARUNMANNURU]`

**(Optional) Technical Sponsor:** `N/A`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Please respond with either "Yes" 

# Project Description

As IPFS is growing and there are lots of applications being on-boarded under IPFS. To have enough documentation for products adoption, its always good to have Medium blogging which gives enough documentation with necessary steps to adopt IPFS. It also gives additional advantage for the contributors to share their thoughts and ideas via medium blogging platform. If we can maintain IPFS specific medium account and we can request contributors to start writing medium blogs and share it across different social networking platforms. 

## Value

Contributors can have additional option to share their views and steps to adopt via this platform. It's easy to advertise medium blogs in any social media platforms to promote the capabilities of FileCoin or IPFS platform.

## Deliverables

- Creating medium account for IPFS/FileCoin org. 
- Maintaining the medium account and sharing the posts on social medium platform.

## Development Roadmap

- Milestone 1: Understand different Medium accounts and compare the best features useful for IPFS/FileCoin Org. 
- Milestone 2: Creating medium account for IPFS/FileCoin.
- Milestone 3: Maintaining and sharing the medium blog posts on social media platforms. 

## Total Budget Requested

There is some issue with medium pricing. If there is any interest on this task.., I will get back with more details once they resolve the issue. It might cost few hounders of dollars I guess. 

## Maintenance and Upgrade Plans

We need to maintain the medium account and some support also needed to share the postings on social media platform. 

# Team

## Team Members

`Arun Mannuru`

## Team Member LinkedIn Profiles

[](https://www.linkedin.com/in/arunmannuru/)

## Team Website

`N/A`

## Relevant Experience

I write medium blogs for the work and the problems which I solve and share it on social media platform. 

## Team code repositories

N/A

# Additional Information

I have been to dWEB 2022 conference, and I met few people who had got grants approved. 
Here are my details: 
email: arunm057@gmail.com

**Comment by ErinOCon** [comment]
Hi @ARUNMANNURU, thank you for your proposal. We will not proceed with a grant for this project as it does not closely align with our program criteria. Wishing you all the best with this documentation work!
