### ISSUE TITLE
Next Step Microgrant: Storz

### ISSUE THREAD

**Issue by anomic30** [ipfs/devgrants#231]
### 1. What is your project? (max 100 words)
Storz is an advanced decentralized file storage and sharing application that is built using IPFS. The current storage giants do not ensure privacy and delete files that appear suspicious. Therefore, we set out to create an application that would enable users to save and share any kind of media with others for easy access. Hence it ensures complete privacy for the user. 

![Landing Page-min](https://user-images.githubusercontent.com/63467479/191007745-70b6fc45-8707-4b11-8150-ea8173cf8f2a.png)

#### Features:
- Store unlimited files.
- Share your files with anyone.
- Ability to make the file public or private.
- All the files are encrypted using the AES-256 Algorithm.
- Files are stored in IPFS, a high-performance distributed server network protocol.
- Passwordless Authentication.
- Fast, Reliable, and Secure.

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
We have used Infura's IPFS hosting service as the sole storage provider. Each file uploaded by the user is encrypted using the AES-256 algorithm and then uploaded to IPFS. The CID of the file along with other metadata is currently being stored in a free-tier MongoDB server, but we plan to shift it to OrbitDB very soon. 
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
- Shifting from INFURA's free gateway plan to a dedicated gateway plan. 
- Buying domains & renting dedicated servers to host our frontend web app.
- Migrating from a free Heroku server to a paid dedicated instance to host our backend.
- Hiring dedicated developers to improve the project further.
- Shifting from MongoDB to OrbitDB to store user metadata.
- Build a mobile version of the web app.
- Advertisement and marketing of this project to attract users.
 
(We are expecting to have a large number of valuable contributions in the upcoming months due to Hacktoberfest)
### 4. Is this project open source?
Yes. This project is completely open-source. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?
Yes. We agree to share the grant reports upon request.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
We developed this application during the [Web3 Infinity Hackathon](https://hackathon.fil-singapore.io/) which was organized by FIL-Singapore, Protocol-labs & Force Web3 Community. We are glad to share that we have won the Decentralized Storage Infrastructure and the Community Choice award of the hackathon. 
Hackathon submission link: https://devpost.com/software/storz-advance-web3-file-sharing-and-storing-application
  
### Additional questions:
* For each team member(s), please list name, email, GitHub account, and role in the project.
#### Member 1:
- Name: Anom Chakravorty
- Email: anomchakravorty3008@gmail.com
- GitHub: [anomic30](https://github.com/anomic30)
- Role: Frontend & Backend developer
#### Member 2:
- Name: Aditya Mondal
- Email: aditya4161@gmail.com
- GitHub: [Sneakad](https://github.com/Sneakad)
- Role: Frontend developer & UI/UX designer

* How did you learn about our microgrant program?
After completing the hackathon, we received an email from hackathons@protocol.ai to apply for the microgrant program.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? [Web3 Infinity Hackathon](https://hackathon.fil-singapore.io/)
  * Please link to your hackathon submission: [Devpost submission link](https://devpost.com/software/storz-advance-web3-file-sharing-and-storing-application)

**Comment by anomic30** [comment]
Hi @ErinOCon, if you and your team have any queries, we would be happy to discuss them here.

**Comment by ErinOCon** [comment]
Hi @anomic30, thank you for your proposal! Can you briefly describe the anticipated impact of the provided next steps? What are the end results you expect to see three months from now?

**Comment by anomic30** [comment]
Hi @ErinOCon, thanks for responding.

Here are the things that we look forward to seeing in the coming months:

**1)** Producing reliable production-ready frontend and backend through research and development. 
**2)** In order to scale, we will rent dedicated servers to deploy both our frontend and backend. 
**3)** Buying domains and other services (INFURA API) .
**4)** I intend to hire dedicated web3 developers to work on further improvements.

**End result:** Expect to release an alpha version of the product and a minimum of 1000 users.

**Comment by anomic30** [comment]
Hi, @ErinOCon I'm wondering if there's any update on our application? Thanks.

**Comment by ErinOCon** [comment]
Hi @anomic30, thank you for your patience with our review. This grant has been approved! Look out for an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by ErinOCon** [comment]
Hi @anomic30, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!
