### ISSUE TITLE
[MICROGRANT] MeDo

### ISSUE THREAD

**Issue by vadkutsen** [ipfs/devgrants#232]
### 1. What is your project? (max 100 words)

MeDo is a decentralized freelance platform where users can post paid tasks and others can earn Matic by executing those tasks.

https://github.com/vadkutsen/medo

https://medo-5jefp3.spheron.app/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
Users who are assigned tasks can upload their execution results to web3.storage. The task authors can access the submitted results on the web3.storage
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1. Add new features such as milestones, the ability for executors to rate authors, change requests, and reward negotiation.
2. Improve UI by adding in-app notifications and improving UX. 
3. Add escrow contracts and the ability of third-party users to validate results.
4. Start community building process in socials.
 
### 4. Is this project open source?

Yes.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

 Yes.
 
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  Yes for Filecoin/IPFS Prizes. https://devpost.com/software/medo-gyc5ha

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Vadym Kutsenko, vadkutsen@gmail.com,  https://github.com/vadkutsen, full stack developer, I work solo on the project

* How did you learn about our microgrant program?
Email from the IPFS & Filecoin team.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  Polygon BUIDL IT : Summer 2022

  * Please link to your hackathon submission
https://devpost.com/software/medo-gyc5ha

**Comment by ErinOCon** [comment]
This microgrant has been approved! Look out for an email to confirm payment details. 
 
Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by ErinOCon** [comment]
Hi @vadkutsen, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!
