### ISSUE TITLE
[MICROGRANT] Map3 Protocol

### ISSUE THREAD

**Issue by Erriccc** [ipfs/devgrants#233]
### 1. What is your project? (max 100 words)
Map3 Protocol improves p2p transfer of Erc20 tokens. Map3Pay uses outsourced Defi liquidity to mitigate p2p cryptocurrency payments, giving the sender and recipient the flexibility to decide what currency they prefer, while  Map3 is a web Dapp that helps users find businesses that accept cryptocurrency payments.
Together, bothtools create an ecosystem that connects cryptocurrency users within their local community, promotes the use of cryptocurrency as a means of payment, and encourages adoption by real vendors.

[Demo Video](https://www.youtube.com/watch?v=zl-VL5Xolx4)
Url to the Demo video: https://www.youtube.com/watch?v=zl-VL5Xolx4

[Map3 Demo Site](https://map3.vercel.app/appvendors?map3Querry=*)
URL to Map3 Demo site: https://map3.vercel.app/appvendors?map3Querry=*

[Map3Pay Demo Site](https://map3.vercel.app)
URL to Map3Pay Demo site: https://map3.vercel.app

[GitHub repo](https://github.com/Erriccc/Map30)
URL to GitHub: https://github.com/Erriccc/Map30

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
Currently, Web3 Storage plays a vital role by simplifying the upload and retrieval of user profile images to IPFS. By saving the hash rather than the file, we substantially minimize the cost and size of user data stored on the blockchain. While this model has worked on a small scale, we intend to further reduce the size of data stored on the blockchain and establish a more scalable architecture by utilizing Ipfs and Ipns to store and retrieve all necessary user information. Using IPFS also means user data becomes cross-platform, cross-chain, and available for other teams to build on.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

The Map3 mvp will not be complete until it receives direct feedback from the users for whom it was designed. We have decided to prioritize user testing and feedback as an efficient way of determining the progress and effectiveness of the tool we are building. As a result, our tasks for the upcoming months include:
	Frontend:
Creating a landing page, an about/faq page, and a contact modal for feedback.
	Content: 
writing blogs, and instructional guides that help a complete beginner to get set up.
	Backend/SmartContract:
modifying the AccountManagerContract.sol by letting ipfs do more of the data heavy lifting.
	Brand:
Create awareness in the cryptocurrency community and among local retail/small businesses.( This could require Consulting professionals to let our team focus on code)
	Maintenance:
Maintain the codebase and debug or improve performance based on feedback.

 
### 4. Is this project open source?
Yes MIT
### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
YES
  
### 6. Does your proposal comply with our Community Code of Conduct?
YES

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
[Submission link](https://devpost.com/software/map3-protocol)
Submission URL: https://devpost.com/software/map3-protocol
Filecoin/IPFS Prizes | Pool Prize
  
### Additional questions:
* For each team member(s), please list name, email, GitHub account, and role in the project.

Member One:
Name - Osborn Ojure
Email - [ozyjunks@gmail.com](mailto:ozyjunks@gmail.com)
Github - https://github.com/Erriccc
Role - FullStack Developer and Smart Contrct Developer

Member Two:
Name - Jide Abatti
Email - oa_jide@protonmail.com
Github - https://github.com/Huncho-J
Role - Smart contract security analysis

* How did you learn about our microgrant program?
	Email from the IPFS & Filecoin team at Protocol Labs.
* If your project was created as part of an event or hackathon:
   Yes
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
Polygon BUIDL IT : Summer 2022
  * Please link to your hackathon submission
[Submission link](https://devpost.com/software/map3-protocol)
Submission URL: https://devpost.com/software/map3-protocol

**Comment by ErinOCon** [comment]
This microgrant has been approved! Look out for an email to confirm payment details. 
 
Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by Erriccc** [comment]
Hey sorry for the late response. I lost access to my accounts I will send a
final report if that is still necessary.
