### ISSUE TITLE
Next Step Microgrant: DeAudit

### ISSUE THREAD

**Issue by priyansh71** [ipfs/devgrants#234]
### 1. What is your project? 

Owing to the immutable nature of blockchain technology, it is impossible to update the code after its deployment. Placing smart contracts without adequate audits could lead to undesirable situations like differences in the contract's intended performance, gas leakage, and more.

Auditing isn't an easy process. Auditing wait times on top audit firms are 9-12 months and are expensive. We need something that is more participative and allows for new and yet-unproven security auditors. This is the motivation behind building DeAudit, a decentralized audit marketplace that turns the auditing process into a prediction marketplace.

Link to Github repo: [DeAudit](https://github.com/deaudit/deaudit)
Link to demo or website, if applicable: [DeAudit](https://bafybeihfjcyld4ogrkrbeciasfhtooewkqyrvaa6lmmi77w3627aydwlu4.ipfs.gateway.valist.io/)

### 2. How will IPFS, Filecoin, or related technology be used for this project?

Our application plans to help contract creators, security auditors and bug hunters as a whole with the help of a single platform by creating a profile for them. It acts as a user's wall for showing his proof of work in audit creation, bug hunting or audit judging. Here, users can upload profile or cover images for themselves, which are hosted on IPFS using web3.storage. Moreover, we have also hosted the project on a decentralised infrastructure (IPFS) using [Valist](https://www.valist.io/).
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective?
Currently we are based on the Mumbai Testnet. We plan to on-board a lot of users, both as security auditors and audit creators. Hence, the grant money would be allocated for Smart Contract Auditing and Marketing of the product. to reach more potential customers for whom the product would prove worthwhile. Moreover, we'd require a Pitch Video and a better dApp design. 
Also would be used to hire more devs to scale it with new features for our frontend, backend and the Polygon contract.

 
### 4. Is this project open source?
Yes, License: GPL-License.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, no worries.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes, it does.

### 7. Links and submissions
We submitted our project to [Polygon BUIDL IT 2022](https://buidlit.polygon.technology/) and included it to the relevant filecoin pool prize.  

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

1. [Priyansh Vyas](https://github.com/priyansh71)
- I wrote the whole frontend in NextJS, designed it and hosted it on IPFS using Valist.
- I also used [wagmi hooks](https://wagmi.sh/) based on ethers for configuring the frontend with the contract.
- Full-Stack Developer. Building in Web3. Contact me at priyansh710@outlook.com
- Built and maintained full-stack production apps i.e. [Transcript Grade-sheet Portal](https://augsdtranscripts.bits-goa.ac.in/) & [Course-Feedback Software](https://feedback.bits-goa.ac.in/) for [AUGSD](https://github.com/arc-bits-goa). 
- Find more about me [here](https://priyansh71.github.io/profile/).

2. [Arihant Bansal](https://github.com/arihantbansal/)
- Worked on Chainlink VRFs, Keepers and additional features on the contract. I also wrote the backend for managing off-chain user data.
- A builder. I was the lead dev at [Cryptocase](https://cryptocasehq.com/). Contact me at arihant.bansal@gmail.com.
- At [Cryptocase](https://github.com/Cryptocasehq), I built the payments and investing infrastructure from the ground up. 
- It led to raising a pre-seed round of $100k. 
- I've also won prizes at Harmony DeFi and Chainlink hackathons.

3. [Ameya Deshmukh](https://github.com/ameya-deshmukh)
- In the project's contract, I helped manage payment streaming on liquidation of the bug pools.
- I'm a Web3 developer and analyst. Contact me at f20200139@pilani.bits-pilani.ac.in.
- I've previously worked on building India's first crypto index, CRE8, at [CoinSwitch Kuber](https://coinswitch.co/crypto-index) and with Hummingbird Ventures as a VC fellow. 
- I also research blockchains. Find me at LinkedIn [here](https://shorturl.at/ipuxz).

* How did you learn about our microgrant program? Via the Filecoin website.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? Polygon BUIDL IT : Summer 2022.
  * Link to the hackathon submission : [DeAudit](https://devpost.com/software/deaudit)

**Comment by ErinOCon** [comment]
Hi @priyansh71, thank you for your proposal! I have closed this issue and will provide an update [here](https://github.com/filecoin-project/devgrants/issues/959).

**Comment by priyansh71** [comment]
Alright, looking forward to it.
