### ISSUE TITLE
[MICROGRANT] Deqity

### ISSUE THREAD

**Issue by MaximilianFullStack** [ipfs/devgrants#238]
### 1. What is your project? (max 100 words)

Deqity allows private business owners to tokenize their companies and sell their equity in a decentralized manner. It is built with IPFS and Web3.storage to allow business owners to market their companies to potential investors. It aims to make company ownership more secure, trustless, and equitable than it has been traditionally. With Deqity, we can create a more connected world and, by extension, generate more wealth generation possibilities for people with fewer opportunities.

Github: [https://github.com/Deqity](https://github.com/Deqity)

Demo: [https://www.youtube.com/watch?v=w7OCmQtcZmk](https://www.youtube.com/watch?v=w7OCmQtcZmk)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
IPFS is used to store marketing data about each tokenized companies. (E.G. Images, description, and due diligence information) Thus allowing these organizations to attract investors and have a higher chance of obtaining funding.

  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

With this grant, I plan on improving the overall user interface and user experience of Deqity. To execute this, I will implement a search function that allows investors to discover more companies. I will also implement a better data management system to reduce load times and allow for scaling. To achieve this, I will use The Graph or another indexing protocol. I will add more information on the company info page, which increases legitimacy and the chance of ROIs. This update will include an overhaul of the tokenize page form and a way for owners to update their company information. I will implement a verification system for listed companies to decrease the chance of bad actors. Lastly, I will implement a system that requires the owners to sign a legal document upon the tokenization of their company (to legally bind the tokens to the corresponding equity).
 
### 4. Is this project open source?

Yes, GPL-3.0

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes

  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
```
https://devpost.com/software/deqity
```

  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
```
Maximilian Mathews
mmillionam@gmail.com
https://github.com/MaximilianFullStack
Solo Founder and Developer
```
* How did you learn about our microgrant program?
```
Hackathon
```

* If your project was created as part of an event or hackathon:

  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
```
2022 Polygon Buidl It 
```

  * Please link to your hackathon submission
```
https://devpost.com/software/deqity
```

**Comment by ErinOCon** [comment]
Hi @MaximilianFullStack, thank you for your proposal! This grant has been approved. Look for an email to confirm payment details.

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by ErinOCon** [comment]
Hi @MaximilianFullStack, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!

**Comment by MaximilianFullStack** [comment]
Submitted the final report!
