### ISSUE TITLE
Next Step Microgrant: Openlinks.io

### ISSUE THREAD

**Issue by noryev** [ipfs/devgrants#239]
### 1. What is your project? (max 100 words)
Openlinks.io is a Link in Bio app built on IPFS. With a super fun UI, you can easily create your own webpage using IPFS! We are using Web3.Storage to serve users the webpages and Filecoin is used to backup webpages long term. We are implementing IPNS to make human-readable-links for our users and Auth0 to implement SSO.
- Login with an E-Mail using SSO (Simple-Sign-On) and produce a self sovereign, decentralized webpage within a few clicks. 
- Once they launch the webpage, users are automatically given a gateway link that they can put in any bio/profile online. 
- The webpage can be updated by going to the main links page, inputting new links, and exporting a new webpage. 
- Openlinks can be used for e-commerce, community engagement, or just censorship-resistant fun!
- [openlinks.io](https://openlinks.io/)
- [openlinks Github](https://github.com/galaxyxone/openlinks)

![Openlinksflow](https://user-images.githubusercontent.com/90220293/193981467-ec1fc4c3-53f1-4945-ad0f-0773fd7894a6.png)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
 As mentioned in the description, Openlinks uses Web3.storage to ensure a simple UX. IPFS and  Filecoin are both central components of why Openlinks works and why it makes sense. Firstly, users are getting the ability to display their digital self in a self-soverign way! In addition, the negative scaling benefit of IPFS is ideal for microsites hosting and is one of Openlink's main advantages! 
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
  - Homepage rework + other page additions
  - IPNS integration & related research - Default IPNS link using w3name 
  - Exported webpage themes (light, dark, purple) & page preview when building webpage
     - Frontend reads previews from /themes/previews lambda which fetches data from S3.
  - Theme selection components on frontend (Most of the work on backend was done for this)
     - Exported pages use selected themes from frontend.
  - Terms and service 

 
### 4. Is this project open source? 
Yes- MIT, APACHE2

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
- [openlinks.io](https://openlinks.io/)
- [openlinks Github](https://github.com/galaxyxone/openlinks)
- [Example openlinks page](https://bafybeidqlaf4jkw7nfaqqgymuyahlwh4uyf7ewgzhigd3bet4mveynkbt4.ipfs.dweb.link/My-Openlinks.html)
- [Web3 Infinity Hackathon](https://devpost.com/software/openlinks?ref_content=my-projects-tab&ref_feature=my_projects)
 
### Additional questions: 

Logan Lentz - Lead Developer/Project Manager
- [Github](https://github.com/noryev)
- Email -> loganl@galaxyx.io

Alex Mirran - Junior Dev/Project Manager
- [Github](https://github.com/galaxyxtwo)
- Email -> alexm@gmail.com

### How did you learn about our microgrant program?
- Filecoin Dev Advocate- Ally Haire [@DeveloperAlly](https://github.com/DeveloperAlly)

As we were not sure the best route for the grant process, Ally suggested that we submit this microgrant along with an Opengrant for this project. This microgrant represents a small first part of our Openlinks roadmap. The Opengrant has the bulk of the upgrades we are implementing over the next coming months.

**Comment by ErinOCon** [comment]
Hi @noryev, thank you for your proposal! Does this work build on your previous projects? If so, can you provide a brief explanation?

**Comment by noryev** [comment]
Openlinks is separate and does not use any of the same code or elements as IPFS Stat Viewer. Our ability to work in the browser is improved due to the work we have completed within the Stat Viewer Grants and that project will continue to receive updates from us and the outside community.

**Comment by galaxyxtwo** [comment]
Hi @ErinOcon,

We meant to include the [Openlinks.io twitter account](https://twitter.com/Opnlinks) in our microgrant above. Check it out to learn more about [Openlinks.io!](https://openlinks.io/)

**Comment by ErinOCon** [comment]
Hi @noryev, thank you for your patience with our review! This grant has been approved. I will send you an email with next steps.

**Comment by noryev** [comment]
Thank so much! We appreciate you<3

**Comment by galaxyxtwo** [comment]
@ErinOCon we submitted the microgrant project report. All work has been completed and our IPNS integration is live on Openlinks.io! Thank you for the support! You can find more here: https://twitter.com/Opnlinks/status/1630232997441179648.
