### ISSUE TITLE
[MICROGRANT] Vue and React IPFS Components

### ISSUE THREAD

**Issue by filipesoccol** [ipfs/devgrants#240]
### 1. What is your project? (max 100 words)
Vue and React IPFS components

Load any IPFS content from the fastest gateway available just passing a valid path. It accept any kind of link containing an IPFS CID in it. The plugin itself verify for you the fastest suitable gateways from the Protocol Labs public gateways. My idea is to create fully functional components to show media and fetch JSON objects from IPFS Public Gateways.

[Vue IPFS Components Github REPO](https://github.com/filipesoccol/vue-ipfs-components)
[Vue IPFS Component NPM Package](https://www.npmjs.com/package/vue-ipfs-components)
[Vue IPFS Components DEMO](https://filipesoccol.github.io/vue-ipfs-components-demo/)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
Any project could use the power of multiple IPFS public gateways even if the content is already using a fixed path for it. In case your firewall is blocking the gateway used by an NFT image for example, it will look for another gateway succesfully connect to your machine and grab the image there.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
I still have to finish documentation and resolve small bugs from the Vue implementation. After that I will work on a React version of it, with Repository, NPM package and Demo page. 
 
### 4. Is this project open source?
MIT

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Sure. Absolutelly.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
Web3RP - Winner of the Filecoin prize during Ethereum SP Hackaton
[Web3RP REPO](https://github.com/doiim/web3RP)
[Web3RP Demo](https://web3rp.doiim.com/)
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Filipe Soccol (Lead Programmer)
[Twitter](https://twitter.com/filipesoccol)
[Github](https://github.com/filipesoccol)
[Email](mailto:filipe.soccol@gmail.com)

* How did you learn about our microgrant program?
Via Protocol Labs website

* If your project was created as part of an event or hackathon:
No, it had started after a lot of people had issues with firewalls during Ethereum SP hackaton.

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by filipesoccol** [comment]
Thank you so much Erin. Will be waiting for the e-mail contact. 😄

**Comment by filipesoccol** [comment]
@ErinOCon Still not receive any contact from IPFS/Filecoin team. Is that something missing?

**Comment by ErinOCon** [comment]
Hi @filipesoccol, circling back on this thread to confirm the email was sent to your team in November. Thanks for reaching out to us!
