### ISSUE TITLE
Open Grant Proposal: universaldot.me

### ISSUE THREAD

**Issue by JosephKnecht-lab** [ipfs/devgrants#241]
# Open Grant Proposal: universaldot.me IPFS Integration

**Name of Project**: universaldot.me

**Proposal Category**: `app-dev`

**Proposer**:@josephknecht-lab

**(Optional) Technical Sponsor**:N/A

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** "Yes" (Apache 2.0 License)

# Project Description

[Universaldot.me](https://universaldot.me/) is a freelancing decentralized application (dApp) that allows individuals to create/complete tasks and organize themselves by creating geographically distributed organizations. As such, it intends to simplify the way people and organizations create contracts with one another. It has been developed using Substrate blockchain framework, but it requires off-chain decentralized storage for large information and files. 

Currently, on the market, there are a plethora of open-sourced and closed-source solutions for decentralized data storage. IPFS is one of the leading open-source peer-2-peer decentralized storage solutions. As such, we have chosen to integrate with the most suitable and mature technology stack that solves the problem of storing large files in a decentralized system.

This grant will enable the project to implement the needed integration with IPFS. The planned integration is described in detail in the following [document](https://drive.google.com/file/d/1ov7jfAPMTuotbHRwTMIRvLKomt1c1e3f/view?usp=sharing).

## Value

- The Foundation intends to Run several IPFS nodes which will provide for wider storage capacity and use of the IPFS network.

- We will provide complete integration of React application with IPFS. This can later be used as a reference implementation for other web developers using IPFS.

- Provide basic integration with Substrate Node. 

- If the case that the freelancing application becomes widely successful, it will add additional exposure to IPFS.

## Deliverables

Milestone 1
1. Design Document for IPFS Integration
2. Initial integration of [ipfs-http-client](https://www.npmjs.com/package/ipfs-http-client)
3. Dockerize the complete deployment

Milestone 2.
1. Complete integration of the IPFS API with [ipfs-http-client](https://www.npmjs.com/package/ipfs-http-client).
2. Storing IPFS CID documents in blockchain storage
3. Retrieving IPFS documents from blockchain storage
4. Run IPFS Nodes with Docker on a cloud provider

## Development Roadmap

| Milestone | People | Funding | Period |
| :------: | :------: | :------: |  :------: |
| Milestone 1 | 4 | $12000 | 20.10.2022 - 01.01.2023 |
| MIlestone 2 | 4 | $15000 | 01.01.2023 - 01.03.2023 |

## Total Budget Requested

$27000

$20,000 will be used for Research and Development
$7,000 will be used for purchasing Linux machines to run IPFS on Cloud providers

## Maintenance and Upgrade Plans

# Team

## Team Members

Igor Stojanov (Founder): https://github.com/JosephKnecht-lab 
Juby Joseph Ninan (Business Lead): https://www.linkedin.com/in/juby-j-ninan-73813a55/ 
Slave Atanasov (Front-end Developer): https://github.com/slaveatanasov 
Slave Mitev (Front-end Developer):  https://github.com/smitev
Felix Gate (Substrate Developer):  https://github.com/felixgate13 

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/igor-stojanov-96364ba 
https://www.linkedin.com/in/juby-j-ninan-73813a55/  
https://www.linkedin.com/in/slaveatanasov/ 
https://www.linkedin.com/in/smitev/
https://www.linkedin.com/in/felix-gate-121907189/ 

## Team Website

https://www.universaldot.foundation
https://www.universaldot.me/

## Relevant Experience

Igor Stojanov is a software architect with 7+ years experience in designing and developing software applications. He has worked at Philips, Signify in the domain of software engineering. Also, has worked for a Dutch blockchain start-up TYMLEZ, which created a proprietary blockchain platform on top of [BigchainDB](https://www.bigchaindb.com/). For universaldot.me, his main focus will be on creating the overall solution architecture and developing pallets in Substrate.

Felix Gate is a substrate developer who is contributing to several substrate based project. For universaldot.me, his main focus will be to implmenent and design additional substrate pallets.

Slave Atanasov is a front-end developer that currently works for a Italian subcontracting company Be. He is building application using React, Angular and other javascript based libraries. For universaldot.me, his responsibilities will be to create the App.js skeleton, React Components and improving User Experience.

Slave Mitev is a front-end developer that currently works for Philips. He has vast experience in front-end development, and for this project, he will work on the IPFS integration. 

## Team code repositories

https://github.com/UniversalDot
https://github.com/UniversalDot/universal-dot-node
https://github.com/UniversalDot/front-end
https://github.com/UniversalDot/compose-service

# Additional Information

How did you learn about the Open Grants Program? 
Web Search

Contact: info@universaldot.foundation

**Comment by realChainLife** [comment]
Hi @JosephKnecht-lab thanks your patience with our feedback here. How many cloud instance will you need for this architecture workflow? Have you explored other IPFS / Filecoin integration pathways like [web3.storage](https://web3.storage/) that could eliminate this additional cost for the project?

**Comment by JosephKnecht-lab** [comment]
Hi @realChainLife. Thank you for the response and the questions. I have provided answer below.

> How many cloud instance will you need for this architecture workflow?

We intent to start with 4 VPC instances running on a cloud provider and managed through a personal host. Please refer to the following [diagram](https://i.imgur.com/VEFhQVt.png) regarding the initial setup.


> Have you explored other IPFS / Filecoin integration pathways like [web3.storage](https://web3.storage/) that could eliminate this additional cost for the project?

Yes, we have looked at many different IPFS service providers but have decided against using them. Our application [architecture](https://github.com/UniversalDot/documents/blob/master/designs/architecture/IPFS%20Diagram.drawio.png) intents to connect directly with IPFS through publicly available [APIs](http://docs.ipfs.tech.ipns.localhost:8080/reference/js/api/#javascript-libraries). 

Let me know if more details are needed.

**Comment by ErinOCon** [comment]
Hi @JosephKnecht-lab, thank you for your reply! I have sent an email to discuss the next steps for this grant. Please let me know of any questions.
