### ISSUE TITLE
[MICROGRANT] Metadrive

### ISSUE THREAD

**Issue by skulltech** [ipfs/devgrants#242]
### 1. What is your project? (max 100 words)

Metadrive is a decentralised platform for uploading and sharing encrypted files. It rests on top of two successful technologies, IPFS and Polygon, and overcomes the transparent nature of IPFS by providing an encryption layer on top of it using smart contract. You can think of it as Google Drive for Web3. It's also designed with composability in mind, so that other dApps can easily use this as a service and build on top of it.

- Github: https://github.com/0xMetadrive
- Project's hackathon submission: https://devpost.com/software/metadrive-zbc738
- Testnet deploy: https://metadrive.vercel.app/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

IPFS is a core part of Metadrive, in fact Metadrive can be described as an encryption layer upon IPFS. It uploads encrypted files to IPFS and uses it as a decentralized storage service.
 
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

My primary objective will be launching Metadrive in a polished form to the general public, live on mainnet. The steps I'll do are
- Put more dev hours on improving the UX and UI, possibly hiring contractors to help me with it.
- Add developer docs for onboarding other products to use Metadrive as their encrypted storage layer.
- Create a Twitter account and do marketing around the product to gauge user interest.
- Run a small closed beta of the project on testnet.
- Improving the website and docs around user feedback.
- Launch on mainnet.
 
### 4. Is this project open source?
Yes it's open source and MIT licensed.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes I agree.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

- Name: Sumit Ghosh
- Email: sumit@sumit-ghosh.com
- Github: https://github.com/skulltech
- Role: Lead developer, frontend and smart contract.

* How did you learn about our microgrant program?

From the email I got after I won the hackathon.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

- Hackathon name: Polygon BUIDL IT 2022
- Hackathon submission: https://devpost.com/software/metadrive-zbc738

**Comment by ErinOCon** [comment]
Hi @skulltech, This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by skulltech** [comment]
Hi @ErinOCon. Thank you! I haven't received any email so far though, letting you know in case you // your team missed something.

**Comment by ErinOCon** [comment]
Hi @skulltech, apologies for missing this message. It looks like we sent you an email on November 21st. Were you able to find it?
