### ISSUE TITLE
[MICROGRANT] Dehitas - A decentralised hiring & talent assessment platform

### ISSUE THREAD

**Issue by Hirangi5** [ipfs/devgrants#246]
### 1. What is your project? (max 100 words)
Hiring is one of the most complex issues to tackle in a company’s growth cycle. It’s unpredictable, it’s expensive, and it’s crucial to get it right.

💻𝗧𝗵𝗲 𝗳𝘂𝘁𝘂𝗿𝗲 𝗶𝘀 𝗱𝗲𝗰𝗲𝗻𝘁𝗿𝗮𝗹𝗶𝘇𝗲𝗱 𝗵𝗶𝗿𝗶𝗻𝗴

With Dehitas…

✔️ Companies can attract the right candidate, brand themselves, and hire & retain the right people

✔️ Candidates can stand out in a highly competitive environment and impress the recruiters in Hireverse

✔️ Creators can create assessment tests and own their expert work, receive royalties & monetize their skills

Link to public Github repo: https://github.com/Lampros-Tech/hireverse/tree/development 
Link to demo or website: https://demo.dehitas.xyz/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

IPFS/Filecoin is used to store sensitive data of companies that are using Dehitas for hiring. Also, any personal data of the candidates will be kept private and safe by storing it on IPFS using CID.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

💻Future versions & roadmap

-    Adding various Assessment Capabilities - Listening Assessment, Interactive Assessment, Audio-Visual Assessment, Story Retelling

 -   Multiple test selections for a job post. e.g. Round 1,2 &3

 -   Adding features to Hireverse

 -   Improvements in UI/UX

 
### 4. Is this project open source?
Yes, this project is open source and any work done with the grants received will remain to be open source.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, we agree to provide timely grant reports whenever requested will submit a final grant report with a comprehensive description of our experience building on Filecoin.

### 6. Does your proposal comply with our Community Code of Conduct?
Yes, our project is in compliance with the Community Code of Conduct.

### 7. Links and submissions
Yes, our project was built during the ETHGlobal's ETHOnline2022 hackathon. Here is a link to our project and all our prizes.

https://ethglobal.com/showcase/dehitas-qqoqw
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Hirangi Pandya - Product & UI/UX Designer - https://github.com/Hirangi5
* Harshil Patel - Product Manager - https://github.com/HarshilPatel02
* Akash Palan - Blockchain Developer - https://github.com/akash1114/
* Bhumi Sadariya - Blockchain Developer - https://github.com/Bhumi18
* Rahul Rajan - Front-End Developer - https://github.com/RahulAtLamp/

* How did you learn about our microgrant program?
* Through internet

* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
  * ETHGlobal ETHOnline2022
  * Please link to your hackathon submission
  * https://demo.dehitas.xyz/

**Comment by ErinOCon** [comment]
Hi @Hirangi5, thank you for your proposal. We will not be proceeding with a grant at this time. Wishing you the best as you continue to build!
