### ISSUE TITLE
[MICROGRANT] <Myrtle Finance>

### ISSUE THREAD

**Issue by Nwosu-Ihueze** [ipfs/devgrants#248]
### 1. What is your project? (max 100 words)
I am working on a non-collaterlaized digital asset rental marketplace which would support multiple blockchains that are EVM compatible. 

https://myrtle.finance

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

IPFS would be used in storing these assets. The marketplace has two options of listing with the primary option being catered to the new users on the space. This option automatically mints and saves these assets to IPFS making onboarding for new users easier knowing that their asset is safe.

IPFS would also be used together with The Graph for data retrieval functions in the application.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

This project would be documented with each user testing and improvements iterated and this grant would facilitate this process.
 
### 4. Is this project open source?
Yes, it is.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Absolutely
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Rosemary Nwosu-Ihueze
nwosunneoma@gmail.com  https://github.com/Nwosu-Ihueze
Owner

* How did you learn about our microgrant program?

* Our project was nominated for the hall of fame after ETHGlobal HackFS hackathon by an IPFS member

* If your project was created as part of an event or hackathon:
  * What was the name of the event? ETHGlobal HackFS

  * Please link to your hackathon submission
  https://ethglobal.com/showcase/muse-qn40r

**Comment by ErinOCon** [comment]
Hi @Nwosu-Ihueze, thank you for your proposal! Can you provide a link to the project repo for this project? Also, can you provide more detail on the steps you will take over the next several months with this microgrant?

**Comment by Nwosu-Ihueze** [comment]
https://github.com/Nwosu-Ihueze/Myrtle

**Comment by ErinOCon** [comment]
Hi @Nwosu-Ihueze, thank you for your reply. The link provided currently is not working. Is this repo open to the public? Also, is there a demo or prototype available to review for this project? It looks like the website is still in the early stages of development.

**Comment by ErinOCon** [comment]
Hi @Nwosu-Ihueze, this item has been closed. Please feel welcome to reapply when all requested information is available.
