### ISSUE TITLE
Open Grant : Third Storage

### ISSUE THREAD

**Issue by hackyguru** [ipfs/devgrants#249]
# Open Grant Proposal: `Third Storage`

**Name of Project: Third Storage**

**Proposal Category:** `devtools-libraries`, `integration-adoption`

**Proposer:** `hackyguru`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

Most of the self-proclaimed web3 applications use centralized databases behind the hood and nullify the whole concept of decentralization by putting the privacy and security of user's data at risk. Confidential user data such as passwords, emails, KYCs and other critical information are often stored without encryption and are vulnerable to data breaches. Further, the developers can also access the private data of their users since the whole data is custodial to the developer without access control limitations.

The biggest problem with the currently used web3 data storage solutions is that they lack composability, performance and scalability. Additionally, developers have a steep learning curve to get started with web3 data storage mechanisms and will have to spend a lot of time in setting up their development environment and storage nodes. The only positives of web2 databases is that they are easily scalable and can be used by web2 developers without any prerequisite knowledge about web3 jargons. But, web2 databases can not be ideal in a decentralized and privacy-preserving web. Migrating between two web3 databases can consume immense amount of time and the lack of data composability can sometimes make it an impossible task to automate. Developers are required to setup their own nodes on different geographical locations to boost their data-availability, performance, Geo-redundancy and decentralization. Further,
all these nodes are 'stand alone' and developers will have to manually sync in all the nodes. The whole web requires a new generation standard to build and use data storage. The new standard should value the privacy and self-soverignity of data more than any other aspect. Developers will have to spend hundreds of hours just to create an infrastructure that can meet all their production requirements.

In most of the cases, web3 data storage options are not 'batteries ready'. This demotivates the developers to take up web3 options and finally the end up using low-code web2 alternatives that seem to do the job but compromise the data privacy that web3 offers.

## Value

Developers usually face the following problems in web2 and web3 databases repectively,

|                          | **Web2 Databases** | **Web3 Databases** |
|--------------------------|--------------------|--------------------|
| **Data sovereignty and ownership**     |                    |        ✅          |
| **Access control**       |       ✅           |                    |
| **Scalability**          |       ✅           |                    |
| **Speed and perfomance** |       ✅           |                    |
| **Costs**                |       ✅           |  Cheaper than Web2 (Filecoin and IPFS)                |
| **Data composability** |                  | Still in early stages                   |

Third Storage solves all the above highlighted problems by providing mutant databases that leverage the pros from both web2 and web3 databases in the following ways :

**Data soverignity :**
All the user data is self soverign and hosted on Filecoin. The data can not be tampered by external sources. The user has the governing power over his data whereas web2 data governance is external. 

**Access control :**
Decentralized access control is faciliated by using cryptography and lit protocol. Third Storage divides the user data into public and private based on the preference of user and developer.

**Scalablity :**
Third Storage can be scaled horizontally and vertically based on the preference of the developer. The infrastructure can be deployed into distributed and geo-redundant infra with minimal costs.

**Speed and perfomance :**
Third Storage does not compromise speed and perfomance in the name of 'decentralization'. We use caching mechanisms to make sure data retrival and writing is as fast as possible.

**Costs :**
A big misconception about web3 is 'Storage is very expensive'. But surprisingly, storage on Filecoin and other web3 native solutions are cheaper than centralized web2 solutions. Third Storage also facilitates 'perpetual file storage'.

#### Data composability

Data composability is one of the crucial elements that was missing in web2. For example, if you hosted a file in AWS - it is not possible for **content addressing** it on another storage provider. 

Revolutionary technologies like IPFS can enable content addressing and data composability in web3. Third Storage leverages this capability to enable data composability between different [storage paradigms](getting-started/storage-paradigms.md). For example, if you wish to migrate from one storage paradigm to another in the future, you can do it without much hassle.

#### Decentralized hosting

You can seamlessly host your dapps on web3 native hosting options with Third Storage. Decentralized hosting only available in [Third Storage Cloud](https://thirdstorage.com/cloud). We provide multiple cloud deployment options which include :
- IPFS Hosting : Hosting static web content on Filecoin and serving over IPFS.
- Cloud Hosting : Third Storage also facilitates Cloud hosting for dynamic dapps. You can opt to host using our native cloud hosting solution or alternatively use third-party providers.

#### Multi-node scaling

With multi-node scaling you can boost data redundancy, data availability, vertical and horizontal scaling and level of decentralization. Multi-node scaling is only available for [Third Storage Cloud](https://thirdstorage.com/cloud) users.

## Deliverables

We will be launching Third Storage Localhost as the core deliverable of this open grant. More information about Third Storage Localhost can be found [here](https://thirdstorage.com/localhost)

## Development Roadmap

![Roadmap](https://thirdstorage.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Froadmap.32aa8a8e.gif&w=3840&q=75)

**Q4 2022 :**

October :
- Hiring developers and expanding team
- Ship Third Storage SDK
- Ship Third Storage CLI
- Ship Third Storage Client

November:
- Ship examples on React and NextJS
- - Hiring developers and expanding team

December :
- ETHIndia Launch
- Work on branding

Q1 2023 : 
- Launch stable version of Localhost
- Setup managed IPFS Nodes with Web3.storage
- Start the work on [Third Storage Cloud](https://thirdstorage.com/cloud)
- Product monetization

The product roadmap and timelines can be found on [Third Storage website](https:/thirdstorage.com)

## Total Budget Requested

| Milestone    | Summary                                                                                                                            | Funding requested (USD) |
|--------------|------------------------------------------------------------------------------------------------------------------------------------|-------------------|
| Milestone #1 | Launching beta of SDK, CLI and Client. Expanding the team and setting up workspace                                                 | 70,000            |
| Milestone #2 | Research and define technical specifications on decentralized K8 containers, hosting and multi-node scaling. Expanding devops team | 80,000            |
| Milestone #3 | FVM Integration and getting started with Third Storage Cloud                                                                       | 30,000            |

Total budget requested :  180,000 USDC

## Maintenance and Upgrade Plans

We are looking to continue this project and fundraise from VCs and angels by this quarter to support further growth. We are expecting to hire a team to take care of the development cycle.

# Team

## Team Members

**Point of contact :**

Kumaraguru T - Founder of Third Storage
[LinkedIn](https://linkedin.com/in/kumaraguru7) | [Email](mailto:guru@thirdstorage.com)

## Team Website

Website : https://thirdstorage.com
Docs : https://docs.thirdstorage.com
Github : https://github.com/hackyguru
Discord : https://discord.thirdstorage.com
Brand : https://thirdstorage.com/brand

## Relevant Experience

Our team successfully completed all the milestones in the previous iteration of this project. More details can be found [here](https://github.com/filecoin-project/devgrants/issues/518)

## Team code repositories

Github Organization : https://github.com/thirdstorage
Developer documentation : https://docs.thirdstorage.com

# Additional Information

We are expecting to complete our seed round by Q4 2022. We already completed a successful iteration of this project previously and are looking for more funds to scale up.

**Comment by hackyguru** [comment]
@ErinOCon @realChainLife The above proposal is a follow up of [this open grant application](https://github.com/filecoin-project/devgrants/issues/518). We're ideally eyeing to launch the product by ETHIndia :)

**Comment by ErinOCon** [comment]
Hi @hackyguru, thank you for the follow up proposal. We will not be awarding this grant at this time, but are glad to see you are participating in an accelerator program. Wishing you all the best!
