### ISSUE TITLE
Next Step Microgrant: <Streamharbour>

### ISSUE THREAD

**Issue by kmadorin** [ipfs/devgrants#250]
### 1. What is your project? (max 100 words)
Streamharbour is all-in-one tool for streamers to monetize their content, accept donations and communicate with their fans. 

Website: https://streamharbour.com/ 
Demo: https://streamharbour.vercel.app/ (Mumbai testnet)
Github: https://github.com/kmadorin/streamharbour

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
For now we use IPFS to allow fans to attach messages to donations (via transaction data or smart contract events) to leave a feedback to streamer or ask a question. Later we want to add NFT streamer profiles (using NFT.Storage and Tableland) that will contain name, bio, links to .lens and .ens profiles and any additional data streamer would like to display on his page. We also want to host streamer's pages on IPFS and allow them to customize their design and content
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We want to:

1. Add donations history page. On each donation transaction our smart contract emits events which we want to index using the Graph or retrieve via Covalent API and display on a donations history page for every streamer
2. Add streamer's NFT profiles which will contain their info and donation settings. We want to make these NFT dynamic using Tableland
3. Add real-time donation alerts via Covalent or Alchemy websockets API or custom back-end
4. Make the app multi-chain. Add donations on Polygon, Ethereum mainnet, Filecoin (try to implement the same logic on FVM) at least

### 4. Is this project open source?
GPL license for code and CC-BY-SA 3.0 for content

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes!
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
We submitted to Ethonline 2022 hackathon https://ethglobal.com/showcase/streamharbour-h1uqk and were in Protocol Labs Prize Pool
  
### Additional questions:

* For each team member(s), please list name, email, Github account, and role in the project.
	Kirill Madorin, madorinkv@gmail.com, https://github.com/kmadorin/, Developer, Product
	Artem Bryzgalov, abrizgalov@gmail.com, https://github.com/artbreez, UX/UI, Product

* How did you learn about our microgrant program?
	An email from Protocol Labs team after the hackathon

* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
  	EthGlobal Ethonline 2022

  * Please link to your hackathon submission
  	https://ethglobal.com/showcase/streamharbour-h1uqk

**Comment by ErinOCon** [comment]
Hi @kmadorin, thank you for your proposal! Can you briefly describe how this integrates with streaming platforms?

**Comment by kmadorin** [comment]
Hi @ErinOCon 

It can be done in streaming software like [OBS Studio](https://obsproject.com/). Streamers can add overlays over their video stream and add any web page inside an overlay. So we'll provide them a link to the page which will listen to the donation events from our smart contracts via Covalent/Alchemy websocket API. When a particular event emits, this page will display a donation alert over the stream and it will be seen on any platform.

Also we want to provide streamers integrations with existing services they use for fiat donations like [Streamlabs](https://streamlabs.com/). In such case our backend will listen to events from smart contracts and send notifications about donations using Streamlabs API. So streamers will be able to use the design of overlays provided by Streamlabs

**Comment by ErinOCon** [comment]
Hi @kmadorin, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!

**Comment by kmadorin** [comment]
Hi @ErinOCon, thanks for the reply. 👍  Not so good news for me :) But I'll try to finish the project anyway
