### ISSUE TITLE
Open Grant: Non-technical Educational Material on IPFS, Filecoin, and NEAR

### ISSUE THREAD

**Issue by sgarcia22** [ipfs/devgrants#251]
# Open Grant Proposal: `IPFS+Filecoin x Anza Academy x NEAR`

**Name of Project:**
[Anza Academy](https://anza.academy)

**Proposal Category:**
`integration-adoption`  `community`

**Proposer:**
@sgarcia22

**(Optional) Technical Sponsor:** 
Tkachuk Konstantin @tkkonstantin

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:**
No, the source code for the Anza Academy website is private, however the courses will be free and public to access through our site.

# Project Description

Anza Academy is an education-as-a-service platform designed to onboard the next generation to web3 with confidence. We currently have a live site at https://anza.academy/, and have a set of NEAR introductory courses for non-technical users. We previously received a $50K grant from NEAR to help develop the site and NEAR courses. We have written, visual content, quizzes, and will be introducing video content. At Anza we want to encourage a hands-on approach, a vital way to help students retain the information they are being presented. While gathering user feedback being the primary focus of Anza's beta phase, we are iterating rapidly to ensure users are provided the platform they want. This includes adding NFT badges, user profiles, videos, and more.  

There is a major opportunity in the **NEAR** ecosystem to grow the understanding and usage of IPFS.  Additionally, many have heard of _Filecoin_, but do not understand how it relates to IPFS, nor how IPFS can positively impact a digital environment without ever seeing the Filecoin name.  The problem to solve is a lack of non-technical content regarding IPFS in general and on NEAR, a look at what dApps are using IPFS, and an easy to understand explanation on IPFS’ general benefit and use case within web3.

Our solution will adequately solve this problem because currently there are no other projects tackling the lack of IPFS exposure to the average NEAR user.  We have already successfully built non-technical courses for general blockchain topics, as well as more specific NEAR content.  We can spend all our time on curating an easy-to-understand breakdown of technical IPFS/Filecoin topics immediately, without further technical development.  

## Value

With a series of easy to understand non-technical courses on IPFS and Filecoin, more general and NEAR users will understand and appreciate how essential Filecoin and IPFS are as a decentralized storage backbone of web3. This will lead to more adoption and users on IPFS and Filecoin, and encourage the use of IPFS as the main decentralized storage system for Dapps.

NEAR is a fast-growing L1 chain with extremely low fees, fast transactions, composability and scaling through shading, and carbon neutrality. They recently surpassed over 19 million accounts in September 2022 and have over 800+ projects, 200M+ transactions, and $600M+ in TVL. There is an extreme lack of IPFS on NEAR content, and at Anza we want to onboard more users onto IPFS and Filecoin in a streamlined and accessible fashion.

The biggest risk associated with education in the current market environment is less overall activity in the space, especially for non-technical users who might follow the crowds. However, when adoption picks up again in the next cycle, Anza will be the place where new web3 and NEAR users will go to learn about IPFS and Filecoin.

## Development Roadmap

<html>
<body>

Timeline | Milestone | Cost | Curriculum High Level Overview
-- | -- | -- | --
December | Introduction to IPFS Course | $5000 | <ul><li>Overview</li><li>What is IPFS?</li><li>Why does IPFS matter?</li><li>The Beauty of Content Addressing</li><li>IPFS vs. HTTP</li><li>The Decentralized Web</li><li>NFT Badge as Proof of Learning</li></ul>
January | IPFS on NEAR Course | $5000 | <ul><li>Overview</li><li>Why does NEAR need storage?</li><li>Why use IPFS?</li><li>Useful storage providers</li><li>Blogchain.app case study</li><li>NEAR dApps using IPFS</li><li>NFT Badge as Proof of Learning</li></ul>
February| Introduction to Filecoin Course | $5000 | <ul><li>Overview</li><li>What is Filecoin?</li><li>Filecoin and IPFS</li><li>Decentralized Storage</li><li>Filecoin vs. Google Drive</li><li>Filecoin x NEAR</li><li>Proving the data</li><li>NFT Badge as Proof of Learning</li></ul>
_ | Total | $15000 | 

</body>
</html>

*Courses subject to edits (module titles, # of modules, chronology, order, etc.)

## Total Budget Requested

$15,000 - Funds will be spent on non-technical course content creation, quiz development, NFT badge development.

## Maintenance and Upgrade Plans

If any changes are made regarding our courses, we will be sure to update them to accurately reflect the current state.

# Team

## Team Members

Sam Garcia - Founder and Lead Developer
Alex Wonnell - Content Creator
Liam Wood - Developer
Paul Burgermeister - Creative Director

## Team Member LinkedIn Profiles

**Sam Garcia**
https://www.linkedin.com/in/samanthagarc/
**Alex Wonnell**
https://www.linkedin.com/in/alexander-wonnell-46ba4949/
**Liam Wood**
https://www.linkedin.com/in/liam-wood-abb160154/
**Paul Burgermeister**
https://www.linkedin.com/in/paulburgermeister/

## Team Website

[https://anza.academy](https://anza.academy)

## Relevant Experience

Our team has over a decade of combined educational experience and experts at breaking down complicated concepts in easy to understand and engaging content. Team experience includes MANGA, Fortune 500 companies, educational institutions, awards and certifications in major blockchain initiatives.

**Sam Garcia**
Founder and Lead Developer of Anza Academy. Former Google Software Engineer and teaches game development for Unity at [https://youtube.com/samyam](https://youtube.com/samyam). Has over 30K subscribers, 2+ million views, and has been sponsored by Unity in many videos. Recently won 1st place at the [NEARCON 2022 IRL Hackathon](https://devpost.com/software/litmus-8iuxwb), was a Finalist at [ETHMexico2022](https://ethglobal.com/showcase/kiwik-9x206), and has won first place awards at [ETHNY](https://ethglobal.com/showcase/he-art-cs85k) and [ETHAmsterdam](https://ethglobal.com/showcase/the-daoverse-o8g12).
https://samgarcia.xyz/
https://twitter.com/samangarc22
 
**Alex Wonnell**
Alex is a UX/UI designer (Deep Work Studio) and former high-school teacher immersed in the blockchain education space.  He has demonstrated Proof of Learning through certificates from Coinbase, Unit Masters, and currently with the Global Blockchain Initiative (GBI).
 
**Liam Wood**
A Software Engineer at Microsoft and has significant experience developing blockchain applications such as [Discover DaVinci](https://youtu.be/7_tjO9_DAzQ), a gamified blockchain learning app.
 
**Paul Burgermeister**
Currently a Senior Product Manager at Kongregate working on [Bitverse](https://www.thebitverse.io/). He previously worked as a Creative Director in education and at the University of Florida for over a decade.
[https://www.paulburgermeister.com/](https://www.paulburgermeister.com/)
## Team code repositories

Sam Garcia
https://github.com/sgarcia22?tab=repositories
Liam Wood
https://github.com/liamvwood?tab=repositories

# Additional Information

Referral - Tkachuk Konstantin @tkkonstantin

Contact -> sam@anza.academy

**Comment by sgarcia22** [comment]
In addition, we can also provide videos for each main section in conjunction with the course contents to help increase engagement and gamification of the course. In terms of experience with video production, I run a [YouTube channel](https://www.youtube.com/c/samyam) with over 30K subscribers teaching game development for Unity. We've also previously done a ["What is web3?" video](https://twitter.com/anzaacademy/status/1559717096195592194) for Anza Academy. For video production we would request the full grant size of 30K instead of 15K, as producing videos takes a considerable amount of time and effort. Looking forward to hearing back :)

**Comment by sgarcia22** [comment]
Would love any feedback on our proposal @realChainLife . Thank you!

**Comment by ErinOCon** [comment]
Hi @sgarcia22, thank you for your proposal. If you have an interest in this project being considered in the future, please feel welcome to re-open the item.
