### ISSUE TITLE
[MICROGRANT] HealthWallet - private data silo for medical records

### ISSUE THREAD

**Issue by alpotapov** [ipfs/devgrants#252]
### 1. What is your project? (max 100 words)
HealthWallet is a private data silo for personal medical records. The vision is to have a complete medical history owned by the patient.
For the MVP I am partnered with a hardware startup that builds devices for blood tests. Those devices will make test results accessible to the patient by uploading them to IPFS through the API that HealthWallet provides.

### 2. Project links
  
Link to Github repo:
github.com/alpotapov/hewa_app
github.com/alpotapov/hewa_service
Link to demo or website, if applicable: see link to hackathon submission below
License: GPL License
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
Blood test results will be stored in IPFS through the Lighthouse to ensure that the medical history remains preserved forever.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
I am focusing on the blockend + IPFS part of the project and would like to delegate the task of developing the frontend. This includes improving the user interface as well as improving the React application.
The grant will be used to pay for UI/UX designer and React developer efforts.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, I publish short weekly updates and a demo video with new features every 2 weeks. Please let me know if additional progress information should be included.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

https://ethglobal.com/showcase/healthwallet-ze6ae
https://github.com/alpotapov/healthwallet
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project:
	* Alexander Potapov, full-stack developer (React, NodeJS, Solidity). https://github.com/alpotapov
* How did you learn about our microgrant program?
	* Announcement in the hackathon discord.
* If your project was created as part of an event or hackathon:
  * HackFS 2022
  * https://ethglobal.com/showcase/healthwallet-ze6ae

**Comment by ErinOCon** [comment]
Hi @alpotapov, this microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by alpotapov** [comment]
Submitted grant report via AirTable
