### ISSUE TITLE
[MICROGRANT] <CHIRPING>

### ISSUE THREAD

**Issue by B-Venkatesh7210** [ipfs/devgrants#254]
### 1. What is your project? (max 100 words)
Chirping is a decentralised social media platform with a blend of gamification. In simple words, Chirping is not alike other social media platforms where the users don't have power, in this we have given power to users and their content by inducting levels into a social media, the first in its kind, where the users are promoted to new levels according to their content and the engagement with the audience which furthermore unlocks new feature and abilities for them which eventually segregates them from users at lower levels.
Moreover, this project was built during the POLYGON FELLOWSHIP OF CLASS 2022.

Link to public Github repo --> https://github.com/B-Venkatesh7210/Chirping
Link to demo or website, if applicable --> https://github.com/B-Venkatesh7210/Chirping

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
I have priorly used IPFS & Filecoin in this project for storing the user's data of their content, in the format of text, images and videos. I am retrieving post data from IPFS onto the frontend. For the Next Step, I need to use NFT.storage for minting NFTs to the users whenever they are promoted to a higher level, I am planning to add dynamic NFTs into the platform which will have the user's data, their total posts, their level etc. which would be changing over time.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
By using IPFS and Filecoin, I am planning to use the technology for applying the following features into Chirping :-
1) For storing the text in each post of a user, onto a IPFS link and retrieve back the information using the link onto the frontend. This will also work for images, videos, the display picture of the user etc.
2) For minting NFTs to each user as a badge of identity and will be dynamic in nature as it will have information which will change over time. Storing the NFTs using NFT.storage. Providing NFTs to the users whenever they are promoted to a higher level as a badge of achievement.

 
### 4. Is this project open source?
Yes the project is open source.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes I agree to share all the necessary details by the firm.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes it does comply with the Community Code of Conduct.

### 7. Links and submissions
I am a POLYGON FELLOW of CLASS 2022. I started the project during the fellowship and successfully presented my project in front of VC's on the demo day. The project links are provided below :-

Link to Devfolio Submission --> https://devfolio.co/projects/chirping-8b69
Link to Notion --> https://www.notion.so/CHIRPING-e2942c2f1b8b4f2bb594a8d3baaac7a1
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Name --> B Venkatesh
Email --> venkumj1234@gmail.com
Github Account --> https://github.com/B-Venkatesh7210
Role --> Founder & Developer

* How did you learn about our microgrant program?
During the fellowship, I came to know about it from mentors.

* If your project was created as part of an event or hackathon:
The project was created during POLYGON FELLOWSHIP CLASS of 2022.
  * Please link to your hackathon submission
  https://devfolio.co/projects/chirping-8b69

**Comment by ErinOCon** [comment]
Hi @B-Venkatesh7210, thank you for your proposal! I have reached out requesting a report on your previous projects. If you have any questions, please do not hesitate to be in touch!

**Comment by ErinOCon** [comment]
Hi @B-Venkatesh7210, do you have any questions regarding the final grant reports?

**Comment by B-Venkatesh7210** [comment]
Hello @Erin O'Connor ***@***.***>, sorry for late reply, I have submitted
the final reports for the previous projects.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
12/16/22,
01:04:04 PM

**Comment by B-Venkatesh7210** [comment]
I have submitted the final reports, could u please look into the grant for
ISSUE#254.

**Comment by B-Venkatesh7210** [comment]
I have submitted the reports, could you please look into the grant for
ISSUE#254. Its getting very late.




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
12/24/22,
04:28:51 PM

**Comment by ErinOCon** [comment]
Hi @B-Venkatesh7210, thank you for your patience with our review. We will not be proceeding with a grant at this time, but wish you the best as you continue building!

Since you have already received multiple grants from this program, please feel welcome to check out [other grant types](https://github.com/filecoin-project/devgrants/issues/new/choose)should the scale and scope of your future work align with the outlined criteria.
