### ISSUE TITLE
[MICROGRANT] Data DAO Hackathon  - Deep Diary Microgrant Application

### ISSUE THREAD

**Issue by max1015070108** [ipfs/devgrants#255]
### 1. What is your project? (max 100 words)
This is a personal decentralized data drive based on ipfs/filecoin/mcs We want to create such a platform where users can store their data like pictures/videos/notes etc on a decentralized blockchain network - ipfs/filecoin And users can own their data safely, Also users can choose to authorize 3rd party platform where they could use users personal data for data mining without letting out users' private data, 3rd party platforms could use users' data for AI training, Data mining, etc to explore commercial value. The rewards of commercials would be back to users who contribute the basic data

[github](https://github.com/0xWeb3Journey/DeepDiary)
[demo vedio](https://ipfs.io/ipfs/QmasXx8azzPPXNRif49RjYz7y6EyE1HeUDvukFae4bszPR)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
  We use IPFS/FILECOIN/FILSWAN to store and retrieve our data to make business and create a great user experience

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Next step 
1. we will improve our UI and performance and also add relationship extract feature 
2. use #bacalhau to run model trainning tasks

### 4. Is this project open source?
YES
prefer  MIT 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
YES 

  
### 6. Does your proposal comply with our Community Code of Conduct?
YES

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  YES
  https://dorahacks.io/zh/hackathon/27/
  https://dorahacks.io/zh/buidl/3443
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Max max1015070108@gmail.com  max1015070108 SmartContract coder
Blue deep-diary@qq.com                                            application and model coder

* How did you learn about our microgrant program?
From community info and dorahacks
* If your project was created as part of an event or hackathon:
yes Data DAO Hackathon

 * Please link to your hackathon submission
https://dorahacks.io/zh/buidl/3443

**Comment by ErinOCon** [comment]
Hi @max1015070108, thank you for your proposal! Can you confirm how your handle is affiliated with the provided project repo? I currently do not see you listed as a contributor - let me know if this is an oversight!

**Comment by max1015070108** [comment]
Hi. @ErinOCon  Thanks for your reply 
Actually, They had not involved me in the project repo
And now i am in ,Please check

**Comment by ErinOCon** [comment]
Hi @max1015070108, this microgrant has been approved! We will send an email to confirm payment details. Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). 

Please let us know if you have any questions!
