### ISSUE TITLE
Next Step Microgrant: <owlando.io IPFS-based Web3D UGC metaverse>

### ISSUE THREAD

**Issue by lazy1523** [ipfs/devgrants#256]
### 1. What is your project? (max 100 words)
Owlando is a UGC meta-universe built by the Web3d engine, where all users can build their own meta-scenes for free and make them into beautiful games.
We store all 3D models on IPFS and store scene data on IPFS.
The user's NFT metadata also exists on IPFS

https://github.com/TropIC-Labs

https://owlando.io
### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
We store the user's scene data, model data in IPFS and ensure that the meta-universe scene belongs to the user via NFT. Also NFT metadata is stored in IPFS

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
The vast majority of our functions are now complete,The grant will be used to reward the team of 3 to encourage them to continue building a more decentralised UGC game
 
### 4. Is this project open source?
MIT

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
zisu founder owlando.io , email:lazy1523@outlook.com
* How did you learn about our microgrant program?
Learn about the IPFS community through
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
https://dorahacks.io/zh/buidl/3500

**Comment by ErinOCon** [comment]
Hi @lazy1523, thank you for your proposal. Can you point to where IPFS, Filecoin, or closely related tech is being used in your code?
