### ISSUE TITLE
[MICROGRANT] Smart What ?! — A Google Translate for Smart Contracts

### ISSUE THREAD

**Issue by henriquemacedo** [ipfs/devgrants#258]
### 1. What is your project? (max 100 words)
We've created a Google Translator for Smart Contracts. The user can paste an URL referring to a smart contract and get a translation perfectly readable by someone that has code/math knowledge from the web2 world. Users are able to save their translations on local storage and will be able to save them on IPFS Storage after connecting their wallet.

Repo: [https://github.com/henriquemacedo/smart-what](https://github.com/henriquemacedo/smart-what)
Website: [https://smartwhat.xyz](https://smartwhat.xyz)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
In order to create ease of access, after connecting with their wallet, users will be able to save their translations on Filecoins’ IPFS instead of only in local storage.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We will use this grant to develop 3 additional features, listed below:
- Actual profile page [accessible via wallet on many pcs] - paywalled: after the payment of a fee (either related to the number of files or by time (weekly/monthly)), people will have the ability to use  IPFS storage for their translations/profile;
- Improve UX/UI;
- Improve the English version of the translation.
 
### 4. Is this project open source?
Yes.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
We applied for a Filecoin bounty _(Storage Wizard)_ during [ETH Lisbon 2022](https://www.ethlisbon.org) and won 2nd place.

- [TAIKAI project page](https://taikai.network/ethlisbon/hackathons/ethlisbon-2022/projects/cl9slqpm144092101zc25lw0c5j/idea)
- [Demo Video](https://youtu.be/kEaP7SXrYo4)
- [Presentation Deck](https://storage.googleapis.com/taikai-storage/others/47c5e950-583f-11ed-8c70-777dc05bd5f9Smart_what_-_Presentation.pdf)
  
### Additional questions:
* For each team member(s), please list name, email, GitHub account, and role in the project.
Henrique Silva, BD — [@henriquesilvaog](https://github.com/henriquesilvaog) / [email](mailto:henriquesilva@taikai.network)
Henrique Macedo, Developer — [@henriquemacedo](https://github.com/henriquemacedo) / [email](mailto:henrique@taikai.network)
João Gonçalves, Developer — [@moshmage](https://github.com/moshmage) / [email](mailto:moshmage@taikai.network)
Rodrigo Sousa, Designer — [@rodrigosous-a](https://github.com/rodrigosous-a) / [email](mailto:rodrigosousa@taikai.network)

* How did you learn about our microgrant program?
During ETH Lisbon.

* If your project was created as part of an event or hackathon:
  * What was the name of the event?
ETH Lisbon
  * Please link to your hackathon submission
[Smart What ?!](https://taikai.network/ethlisbon/hackathons/ethlisbon-2022/projects/cl9slqpm144092101zc25lw0c5j/idea)

**Comment by ErinOCon** [comment]
Hi @henriquemacedo, this microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
