### ISSUE TITLE
[MICROGRANT] DeCommerce

### ISSUE THREAD

**Issue by jozefpinter** [ipfs/devgrants#259]
### 1. What is your project? Decentralized ecommerce for Web3.

Basically currently it is a simple ecommerce for Web3. You can run a shop on IPFS and accept BTC, ETH, XMR payments for goods and services.

https://github.com/ivyca-com/decommerce
https://ipfs.filebase.io/ipfs/QmenhKTrYoAt1gxFqLy5LDSGtiCHJeinskV4RXRSYhsoSF/
https://www.ivyca.com/decommerce/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
It runs on IPFS. DeCommerce is the only ecommerce in the ipfs repository. Here: https://awesome.ipfs.io/apps/
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

I want to start working on the second version (v2). Currently it is not users friendly. I want to make an app which runs on IPFS.
 
### 4. Is this project open source?

GPLv3

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
No
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Jozef Pinter, jozefpinter@gmail.com, https://github.com/jozefpinter , software engineer
* How did you learn about our microgrant program?
Google
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
 No
  * Please link to your hackathon submission
No

**Comment by ErinOCon** [comment]
Hi @jozefpinter, since this project is being tracked [here](https://github.com/filecoin-project/devgrants/issues/1142), I have closed this issue.
