### ISSUE TITLE
Open Grants Proposal: Bringing Accountability and Ease of Use to Web3 Orgs using Soul Bound Tokens

### ISSUE THREAD

**Issue by lomads** [ipfs/devgrants#262]
# Open Grants Proposal: `Bringing Accountability and Ease of Use to Web3 Orgs using Soul Bound Tokens`

**Name of Project: Bringing Accountability and Ease of Use to Web3 Orgs using Soul Bound Tokens**

**Proposal Category:** `app-dev`

**Proposer:** `lomads`

**(Optional) Technical Sponsor:** 

**Name**: `Ryan Baumann` 
**LinkedIn**: https://www.linkedin.com/in/ryan-baumann-3823a753/?originalSubdomain=ca
**Twitter**: https://twitter.com/trdiscordian

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:**  "Yes" 

# Project Description

In the recent years Web 3 technologies have alleviated the importance of self sovereignty and is rapidly changing the makeup of the modern workforce: from the types of roles in high demand to the growth in independent workforce. The combination of the Metaverse and a Decentralized Web3 has the potential to radically transform operating models and the labour market. Today 7 out of 10 people worldwide are self-employed or independent and the number keeps growing. By 2028, there will be 90 million self-employed workers. The deregulation spearheaded by Web3 is empowering workers to turn towards self-employment

Managing this floating workforce in an organisation brings with it new challenges and problems, notably:

- **Context:** How to provide contributors with sufficient context to do their jobs well
- **Access Control:** How to manage access across different tools (Notion, Github, Google etc.)
- **Credibility:** How to gauge the credibility of individual contributors 

At Lomads we are trying to solve this problem through:

- A unified workbench that synchronises treasury management, operations and governance
- A Soul Bound Token (SBT) based system that:
    - Personalises the workbench as per as the role of the members
    - Acts as a single access token for various 3rd party tools
    - Immutable record of contributions (work history)

For this project we will be focussing on the SBT based system that will act as:

- An access card to the organisation workbench and and 3rd party tools
- User Digital identity (your own Web3 CV)

## Value

Majority of the workforce in Web3 organisations tend to be self employed independent workers. Working in such an environment can be challenging both for the employee and the employer. An employer(manager/admin) has to manage projects and tasks, give/revoke access to 3rd party tools and judge the competence of the applicants. An employee (contributor/worker) has to find the suitable tasks and the suitable information to complete the task, and provide a digital CV to showcase their work experience.

SBT system executed in the right way will help make the workflows seamless and automated which would reduce the administrative burden and human errors and also build accountability (as reputation is accumulated by the user through their work, they will be invested in keeping the reputation level high and not losing it with time (like reviews))

The key areas where execution is important and more attention will be paid are:
- Data storage and Data ownership
- SBT metadata update
- Contingency plan if someone looses their SBT (wallet lost)
- Web3 authentication layer for Web 2 applications

## Deliverables

The SBT system will be a web app with the following key deliverables:
- Smart contract to Create and Mint SBT
- Integration of the SBT with Lomads Frontend (web app) to:
   - Create SBT for the Organisation
   - Mint SBT to be part of the Organisation
   - Create SBT gated access control for Notion and Discord
   - Update of SBT data as work is completed

## Tech Stack

- IPFS + Filecoin + Web3storage for decentralised data storage solution
- IPNS to update data
- Metamask for authentication
- Reactjs and Nodejs

### Milestone 1:

- **Goal:** Soul Bound Token Smart Contracts
- **Time:** 2 weeks
- **Resources:**
    - Project Lead
    - Solidity Dev

### Milestone 2:

- **Goal:** SBT gated access control
- **Time:** 4 weeks
- **Resources:**
    - Project Lead
    - UI/UX designer
    - Full Stack Engineer Senior
    - Full Stack Engineer

### Milestone 3:

- **Goal:** UI and Integration
- **Time:** 4 weeks
- **Resources:**
    - Project Lead
    - UI/UX designer
    - Full Stack Engineer Senior
    - Full Stack Engineer

## Total Budget Requested

**Total Funding Amount**: $40,000

**Expenditure Breakdown**:

|                        | Project Lead           | Full Stack Dev Senior  | Full Stack Dev Junior | Solidity Dev  | UI/UX Designer | 
| ------------- |:-------------:| -----:|-----:|-----:|-----:|
| Milestone 1    | $ 3000  |              |            |$3000 |            |
| Milestone 2    | $ 6000  | $5000 |$3500 |            |$3000 |
| Milestone 3    | $ 6000  | $5000 |$3500 |            |$3000 |

## Maintenance and Upgrade Plans

Once the initial version of the SBT system is up and functional it will be tested with our community. We will be working on bug fixes and also user feedback to improve the app. 

Going forward the following features are planned to be built:
- User Profile Page to showcase their SBT (and related metadata). This would act like user Web3 LinkedIn Profile
- If user holds multiple SBTs from different organisations, they can create a Meta SBT to aggregate all their work experience 

# Team

|     Name         | Role           | LinkedIn  | Github  | 
| ------------- |:-------------:| -----:|-----:|
| Naman Negi    | Project Lead / Solidity Developer  | https://www.linkedin.com/in/namansnegi/             |  https://github.com/namansnegi          |
| Harish S N  | Senior Full Stack Web3 Developer  | https://www.linkedin.com/in/rish6ix/ |https://github.com/rish6ix |
| Zelie Dethorey    | UI/UX Designer  | https://www.linkedin.com/in/zélie-dethorey-8ab09669/ | |
| Zohaib Kibria    | Full Stack Developer  | https://www.linkedin.com/in/zohaib-kibria-221890137/ |https://github.com/zohaibkibria|
| Erwan Gour    | Solidity Developer  | https://www.linkedin.com/in/erwan-g-bb7a59178 |https://github.com/reptincel-cpu |

## Team Website

https://lomads.xyz/

## Relevant Experience

We're a squad of 5 with many years of experience in software development and with complimentary expertise in various domains. 3 members of the team have more than ten years of work experience in UX design, software design, coding and product development.

**Naman Negi:** CTO and co-founder of Lomads. Former Tech Lead at a startup in Paris called Tortoise. 10+ years of experience in Data Science, Machine Learning, AI applied to various fields like Automotive, Material Science and Healthtech. His main focus for the last couple of years has been blockchain technology.   

**Harish SN:** is an experienced Full stack developer with around 10 years of experience in web and mobile app development

**Zelie Dethorey:** is an experienced graphic designer with 10+ years of work experience and a strong passion for UI/UX

# Additional Information
Lomads is part of the IPFS Metaverse Bootcamp Acceleration program at Outlier ventures. While discussing with the Protocal Labs team involved in the program we were recommended to apply for the Open Dev Grants for the product development

**Comment by lomads** [comment]
Hello @realChainLife @ErinOCon. Any updates?

**Comment by ErinOCon** [comment]
Hi @lomads, thank you for all of your patience during our review process. In light of the macroeconomic climate, the review of our budget and priorities for the fiscal year has resulted in a much longer evaluation period for our grants program.

After much consideration, we have determined that we will not be moving forward with a grant at this time. We are wishing you all the best as you continue to build!
