### ISSUE TITLE
[MICROGRANT] Eth Transport

### ISSUE THREAD

**Issue by aspiringsecurity** [ipfs/devgrants#263]
### 1. What is your project? (max 100 words)

Monitoring tools for road incident management and reducing traffic congestion powered by IPFS. Crowdsourcing information sharing for better and safer roads.

How it works:

1. Camera Management: Add/edit/delete cameras for snapshots of road incidents.

2. Object Detection using OSS computer vision.

3. Video analytics configuration using IPFS.

4. Live streaming with Object Detection, Video Analytics using IPFS.

5. Alarm storage using Ethereum. Save/delete alarm metadata and image to/from IPFS. Store the hash returned from IPFS to Ethereum test network. Provide links to alarms and blockchain transaction details.

6. Alarm Viewer: Add alarms with a single touch. Open the Alarm Settings menu from the home page. Add an alarm, delete an existing alarm.

Github Repository: https://github.com/aspiringsecurity/EthTransport

Website: https://sites.google.com/view/aspiring-road-safety/home and https://sites.google.com/view/latcglobal/home (LATC for Road Safety)

Link to the Demo: Please visit the 3 demo videos at the link
https://drive.google.com/drive/u/3/folders/130gWNRVsPS9O7tUs0iAx-bolx2wyYCDU

1.  Screen Capture with Alarm Storage at IPFS: demo_screen capture.mov file
2. 2 minute demo of Road Incident and Investigative Case Management Solution: ICM Overview.mov file
3.  Detailed and complete solution (6 minutes)  with IPFS implementation:  ICM_demo.mp4 file 
 (The demo is also available at Youtube link: https://www.youtube.com/watch?v=4B2iYxQCuaI )

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

IPFS is the key backbone of our project as all the incident data is saved at IPFS. We are using IPFS for storing a variety of incident data like incident snapshots, alarm metadata and object types at the time of incident. Please find the video at  https://drive.google.com/drive/u/3/folders/130gWNRVsPS9O7tUs0iAx-bolx2wyYCDU (demo_screen capture.mov file). We are also storing Alarm metadata at IPFS. Also, Saving/deleting alarm metadata and image to/from IPFS. We are also storing the hash returned from IPFS to Ethereum test network. Further we are using IPFS for: Video analytics configuration; Camera Management: Add/edit/delete cameras with integration with video streaming, IPFS; Live streaming with Object Detection Video Analytics using video streaming solution, and IPFS for incident snapshots.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We will be focusing on the following objectives with the Microgrant:

1. We plan to decentralize key components, bottlenecks in our existing IPFS solution.

2. We wish to implement web3.storage developer platform to use decentralized protocols for enabling better citizen mobilization for creating incident data along with its relevant metadata.

3. For the police officer or admin role, we wish to store the relevant information on an incident at IPFS and enable investigative case management solution for early-stage detection and prevention of incidents.

4. Learning with ZF Mobility (https://www.zf.com/site/zms/en/zms.html): We are extending and adapting our platform for connected vehicles in Europe for sustainability and efficiency. We are currently working on a dataset of 15000 trips, 45+ trucks and 175+ drivers and enabling them to achieve better fleet management. We wish to use FEVM for compiling smart contracts. 
FEVM enables us to use composable and stackable building blocks and primitives exposed through standardized interfaces, enabling the construction of interconnected solutions, thereby improving better outcomes. We wish to spend quality time on understanding how we can utilize the strengths of FEVM in our smart contracts.

5. Development of Auto Repair Invoice, Vehicle Maintenance Planner using an OSS spreadsheet solution with Filecoin storage: We wish to develop Post PC applications namely Auto Repair Invoice and Vehicle Maintenance Planner for enabling repair shops to actively participate in improving the road conditions by providing instant maintenance to vehicles with breakdown or damage. We will extend and adapt EtherCalc for a Post PC interface with persistent file storage of Filecoin for data analytics. We also wish to explore IPFS integration with key open-source computer vision librariers like PyTorch, Tensorflow and analytics tools like R, Scipy, Matplotlib, Octave and Power BI. 

6.  We also wish to extend our project for reducing congestion at car parking slots in collaboration with Samsung. Our team member, Vibhor Bijoy, has developed a prototype with which we will be integrating our solution this fall. We wish to use FEVM for compiling our smart contracts for developing a DAO tool.

7.  Accessibility: Our team member, Vibhor, will enable us to develop solutions for citizens with disabilities and integrate them in Eth Transport application. He suffers from paralysis and wishes to contribute to improving the accessibility aspect of the solution. Some of his early efforts include developing a solution to prevent road rage by enabling drivers to detect and understand the traffic signals using road sign detection with OpenCV and Tensorflow, and a conversational interface.

 
### 4. Is this project open source?

Yes, the project is open source with license type: MIT License.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, definitely. We would share a final grant report at the end of 3 month period.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions
We participated at the Moralis Filecoin 1,2,3 hackathon (https://moralis.io/filecoin-hackathon/) and won multiple prizes (please watch the video at https://www.youtube.com/watch?v=a_2n0sEPuxc and visit the website at https://moralis.io/filecoin-hackathon/winners/ )

Hall of Fame URL: Please search for "Eth Transport" at https://airtable.com/shr2xqq48PEHWzSBu/tblCwc1GeUbvwVrmU

We won the filecoin prize for both our submissions: Eth Transport and Drone Monitor and received a sum of 1429 FIL. We learned about the Filecoin microgrant from the prize email as well as a memo from Niki Gokani, Eco System Growth at IPFS and Filecoin, who motivated us to scale up our project.  Wish to also share that we won best use of  Fluence prize, XMTP pool prize and Ledger Nano S Plus prize for the Eth Transport project.

  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Manu Sheel Gupta: Email (Email: manu@seeta.in , aspiring.investments@gmail.com ) (Github: https://github.com/seetadev )
Manu is the software architect and full stack engineer in the project. He is responsible both operationally and strategically to enable sustaining and scaling the project. He is also responsible for developing collaborations in the Blockchain eco-system and managing the project roadmap, milestones along with the feature spec and code freeze timelines.

Deepti Gupta: (Email: deepti.kotwal.2011@gmail.com ) (Github: https://github.com/aspiringsecurity/ )
Deepti brings years of experience of developing mobility solutions at SAP and is responsible for the UI/UX design, workflows and recommending key methods to effectively utilize the strengths of IPFS as the decentralized storage solution.

Vibhor Bijoy: (Email: bijoy.vibhor19@gmail.com ) (Github: https://github.com/vibsdrockstar )
Vibhor is our expert on developing security solutions and compliance software. With multiple years of experience at Thales (https://www.thalesgroup.com/en ), he will enable us to build a decentralized mobility solution using IPFS that can be trusted and deployed in a variety of topographies. He will enable us to do a pilot project at IIT Delhi campus in Delhi.

Raghav Kumar: (Email: dev@seeta.in) ( GIthub: https://github.com/thisisraghavkumar ),  Raghav is responsible for solving all the key issues around the implementation of smart contracts and IPFS. He has been responsible for enabling us to use Ethereum blockchain with IPFS effectively. He has also enabled us to bootstrap our efforts on improving the unit testing of our smart contracts and will enable us to scale our efforts on using FEVM more effectively for DAO tooling.

Geetanshu Gupta (marketing@tickervalue.com)  (Github: https://github.com/geetanshu2502 ) Geetanshu is both a frontend as well as the backend engineer. He is a great UI/UX designer and will be enabling us on the design aspects of the project.

Project Advisers
Dr MPS Bhatia : (aspiringuserapps@gmail.com ) Dr MPS Bhatia is the key enabler on piloting this project at Delhi. He is our go to mentor on building business partnerships with Ministry of Road and Transportation and also build up the collaboration on hiring software engineers specializing in IPFS. He teaches Computer Science to engineering students, Phds and MTech students) and enables us on both technical as well as business fronts (please visit http://www.nsit.ac.in/faculty/mps/)

Vithika Gupta: (aspiringworkapps@gmail.com) Vithika is our go to guide on implementing iot stack and integrating with IPFS and open source video streaming solutions. She guides us on key iot protocols and their implementation.

Abinash Patra (Email: Luffy.Abinash@gmail.com) (Twitter: https://twitter.com/LuffyAbinash ) Abinash is a React expert and will enable us to do better in creating good integrations of data analytics solutions powered by react framework and ethercalc with IPFS.

Arush Bartaria (Email: arushbartaria@gmail.com ) Arush is the founder of Tech Swarm (https://www.linkedin.com/company/tech-swarm/ ) and will be guiding us on the hardware software interfacing and on the backend performance. 

* How did you learn about our microgrant program?
We learned about the Filecoin microgrant from the prize email as well as a memo from Niki Gokani, Eco System Growth at IPFS and Filecoin, who motivated us to scale up our project.  

* If your project was created as part of an event or hackathon:
Moralis Filecoin 1,2,3 hackathon (https://moralis.io/filecoin-hackathon/ )

  * Please link to your hackathon submission: Moralis hackathon submission was via a google form. Please find the submission materials at https://drive.google.com/drive/u/3/folders/130gWNRVsPS9O7tUs0iAx-bolx2wyYCDU
  * Github Repository at https://github.com/aspiringsecurity/EthTransport

**Comment by ErinOCon** [comment]
Hi @aspiringsecurity, I hope your project is going well! Please note that your final grant report is due within two months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by seetadev** [comment]
Hi @ErinOCon , great to hear from you. Wish to share that our project has been coming along well and we should have arrived at a good conclusion on our project goals and milestones. We are delighted to have the opportunity to share our final grant report with the committee and get value feedback and pointers. We have studied the link shared and are good on almost all fronts at this juncture. On the same note, wish to share that the Filecoin technical documentation, community support and learning opportunities are wonderful and have enabled us to do better. Wish to thank you and everyone in the eco-system.
