### ISSUE TITLE
[MICROGRANT] ZKsig delegated authorization contracts and tooling

### ISSUE THREAD

**Issue by mehtaphysical** [ipfs/devgrants#264]
### 1. What is your project? (max 100 words)

We built a platform to create, send, sign, and verify legally binding digital signatures. From the binding digital signatures we create NFTs for better interoperability.

- [Solidity Contracts](https://github.com/zksig/solidity-contracts)
- [dApp](https://github.com/zksig/app)

https://github.com/zksig/solidity-contracts

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

We use FEVM to store digital signature information and generate NFTs. We use IPFS to make agreement PDFs available to signers. We use Filecoin to archive agreements for long-term storage.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- Improve and test our delegated authorization contracts (see [this](https://github.com/lotus-web3/client-contract))
    - Tooling for easy use with DataDAOs
- Add persistent storage for agreement PDFs (which is a requirement for making the digital signatures legally binding)
- Tooling to easily add agreements to other dApps
    - sign agreement from dApp
    - verify agreement from dApp and gate access
- Tooling and documentation to have other contracts verify agreement
 
### 4. Is this project open source?

Yes. MIT.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

- https://ethglobal.com/showcase/zksig-nfts-j597n
- https://zksig.io/
- https://devnet.zksig.so/
- https://nft-clients.zksig.io/
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
    * Ryan @mehtaphysical Full-Stack developer
    * Adrian @adrimonasterios
* How did you learn about our microgrant program?
    * After the hackathon we receive an email inviting us to apply
* If your project was created as part of an event or hackathon:
  * HackFEVM https://ethglobal.com/showcase/zksig-nfts-j597n

**Comment by ErinOCon** [comment]
HI @mehtaphysical, this microgrant has been approved! We will send an email to confirm payment details.

**Comment by ErinOCon** [comment]
Hi @mehtaphysical, I hope your project is progressing well! If you have any questions regarding the reporting process for this work, please be in touch. In the meantime, here are some things we are looking for when reviewing FVM Microgrant results: 

- A fully working user-facing demo with nice UX that anyone case easily use.
- Deployment to FVM mainnet - now that it has officially launched!
- Interesting use of the EVM on Filecoin, especially with respect to what's unique to Filecoin

Happy building!

**Comment by ErinOCon** [comment]
HI @mehtaphysical, can you provide an update on your project progress? Below is a current list of what we look for when determining if a FVM microgrant project is complete:

- A fully working user-facing demo with nice UX that anyone can easily use.
- A dapp deployed to a Filecoin testnet like [Calibration testnet](https://docs.filecoin.io/networks/calibration/details/) so that we can see all the functionality working in a demo, and will be deployed to Filecoin mainnet in a production-ready state on project completion.
- Interesting use of Filecoin’s EVM, especially with respect to what’s unique to Filecoin (for example, via exploration of FVM use cases or the Filecoin Solidity API (see https://github.com/filecoin-project/community/discussions/585#resources, or [Bacalhau x FVM](https://github.com/bacalhau-project/lilypad), etc.)

Please be in touch with any questions!

**Comment by ErinOCon** [comment]
Hi @mehtaphysical, can you provide an update on your project progress?

**Comment by ErinOCon** [comment]
Hi @mehtaphysical, please provide an update for your project this week.

**Comment by ErinOCon** [comment]
HI @mehtaphysical, we have not heard from your team and have resolved this project.

Please contact [grants@fil.org](mailto:grants@fil.org) with any questions.
