### ISSUE TITLE
[MICROGRANT] woop-pay

### ISSUE THREAD

**Issue by alessandromaci** [ipfs/devgrants#265]
### 1. What is your project? (max 100 words)
Woop Pay is a web application to make web3 payment requests frictionless. 

How do you ask someone to send you web3 money? I often get this answer: share your address, your friend enters the address in Metamask, and finally sends transactions. This process is not so UX-friendly. I want to change it.

This is the problem that Woop Pay tries to solve - make web3 payment requests frictionless. Do you want to ask your friend 20 DAI for your ordered pizza? Great! Go to Woop Pay, create the payment request, share the link with them using Telegram/Twitter/WA/QR code, and wait for their payment confirmation.

GitHub: https://github.com/D-D-Agency/woop-pay
Demo: https://wooppay.xyz

(If you need Goerli ERC20 tokens to test the app E2E, please reach out to me)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
IPFS is the link between the request and the payment. When creating a payment request, some payment metadata is stored on IPFS and the result "cid" is used to identify that specific request. 

In this way, when the payment link is shared, the application fetches from the IPFS "cid" the payment details and asks the user to pay according to the request.

IPFS will also allow in the future support more data field descriptions (e.g. payment description - what is this payment for) to increase the UX even further
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
The product, as it stands today, is an E2E working prototype. 

This grant will allow me to move from a prototype to an MVP by:

1. Investing in design and front-end work. I need help improving the existing app design so that the application results aesthetically appealing and UX-friendly. I have experience mostly in backend development and I can't improve it further than this
2. Infura IPFS hosting costs. I am relying on Infura to enable seamless interactions between my app and IPFS. The more users will test this application, the higher the costs will be

Based on the resource left, I am also busy planning the work for the next step - from an MVP to a product 1.0. This is still a work in progress, but I want to explore the integration with Biconomy SDK and the introduction of a relayer to remove the need for wallet confirmations. This will result in simplifying even further the UX. However, it is quite expensive because the relayer will subsidy the gas fees. 
 
### 4. Is this project open source?
Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
N.A
  
### Additional questions:
* For each team member(s), please list name, email, GitHub account, and role in the project.

The project was built by Agency Developer DAO members (https://agency.developerdao.com/)
Alessandro Maci, alessandromaci96@gmail.com, https://github.com/alessandromaci, Founder & Developer
Gordo, gordo@gordo.design,  https://github.com/gordo-labs, Product Designer

* How did you learn about our microgrant program?
I was part of a team that in the past applied for a microgrant program

* If your project was created as part of an event or hackathon:
N.A

**Comment by ErinOCon** [comment]
Hi @alessandromaci, thank you for your proposal! This microgrant has been approved. We will send an email to confirm payment details.

**Comment by ErinOCon** [comment]
Please note your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
