### ISSUE TITLE
[MICROGRANT] AgoraChat

### ISSUE THREAD

**Issue by prllrp** [ipfs/devgrants#266]
### 1. What is your project? (max 100 words)

About
AgoraChat is an MVP for a decentralized chat room built with IPFS. It tries to adresss three features that are fundamental for the free and open digital society that Web3 and Decentralized technologies promise, these features being that AgoraChat is Public, Pseudoanonymous, and Accountable.

https://github.com/prllrp/Agora

https://www.agorachat.xyz/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
  IPFS is used to provide the back-end functionality for the app through the JS-IPFS package. The PubSub functionality is used to pass messages and rooms in a decentralized manner. The site is also entirely hosted on IPFS with the help of Fleek. 

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Funding will be used to support myself while I continue learning more about IPFS and related technologies. I am a recent graduate and am hoping to join Protocol Labs or a related project. Current plans for the project are to drive more traffic to test the response, and continue to improve the robustness of the app as I continue to learn. 
 
### 4. Is this project open source?

MIT

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  N/A
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Patrick Lane patricklane09@gmail.com github.com/prllrp Sole Contributor
* How did you learn about our microgrant program?
Word of Mouth from Logan Lentz, Founder of OpenLinks
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @prllrp, this microgrant has been approved! We will send an email to confirm payment details. Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
