### ISSUE TITLE
Open Grant Proposal: index.as

### ISSUE THREAD

**Issue by serafettin** [ipfs/devgrants#267]
# Open Grant Proposal: `index.as`

**Name of Project:** index.as

**Proposal Category:** `app-dev`

**Proposer:**[@serensandikci](https://github.com/serensandikci)  [@nurinlowercase](https://github.com/nurinlowercase) [@serafettin](https://github.com/serafettin) [@furkanozelge](https://github.com/furkanozelge)

**(Optional) Technical Sponsor:** None

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

Today, information discovery is vastly centralized. We depend on several algorithms. This not only prevents us from accessing quality information, it also harms society by creating echo chambers and filter bubbles. Overgeneralized, unsourced and mediocre information is the only information people discover. Niche or credible content is extremely difficult to reach, sometimes impossible.

index.as is an interoperable tool that allows people to create and monetize curated search engines. Search engines can serve as a decentralized form of content, a medium of information, for delivering in-depth information about a specific topic/context. We believe that this is the most scalable and reliable way to organize information through context in a decentralized way. In addition, monetization and collaboration are two components of this solution that provide motivation and continuity for mapping information at different levels.

## Value

index.as aims to serve three main purposes:

### Decentralization of information organization
Information organization should be decentralized in order to reach and discover meaningful, inspirational, and stimulating perspectives. That's why index.as aims to change the way information is distributed. Creating decentralized libraries with subject matter experts will help us achieve this. As a result, we can achieve independent, censorship-resistant, yet authenticated information sources. With IPFS, we decentralize information organization and thanks to LIT Protocol we can offer creators and curators composable access control actions and collaboration options. In this way, we will contribute to the Web3 ecosystem by providing an interoperable tool that decentralizes information organization and offers a variety of monetization, collaboration options as well.

Monetization and collaboration are both crucial components and benefits of index.as, as one of our aims is to include information organization as part of the creator economy.
    
### Including subject-matter experts and new use-cases to the Web3 ecosystem
With index.as, curators, journalists, niche content creators, and subject-matter experts will be onboarded to Web3. Those people cannot be found on Web2, as they aren't given incentives or represented. The role of monetization and collaboration is vital in this field, as they provide means of incentive and cooperation.  Making information discovery as a part of creator economy will expand and diversify the web3 ecosystem.

### Enabling a Web2 - Web3 bridge 
Also, by indexing Web2 data on Web3, index.as also plays a bridge role, which has the potential to onboard Web2 users to Web3. In order to do this, we will collaborate with ecosystem-mates ipfs-search.com and webrecorder.net.

#### Indexer (API & Web app)

We created a tool that enables users to create a topic-based index. They can add articles, documents, NFTs, photos, videos, tweets and any other kind of content as links. In this way, they can create their own library of content in any format. Advanced filtering and search options can also make these indexes function as small search engines. Index data will be stored on IPFS, users will authenticate on indexes with their DIDs.

#### Web2-Web3 Bridge

We built a crawler that indexes web2 documents, fetches URL content, and indexes IPFS content. We will collaborate with the ipfs-search.com team to make this part interoperable.

#### Web2 Archiver

To generate cryptographically verifiable archives of websites, we will use webrecorder.net. Archive data will be stored on IPFS. As a result, there will be no data deletion risk for curated contents.

#### Collaborative indexing

We’ll provide composable access control options so that curators have full control over their content. They’ll curate collaboratively with on-chain conditions are as follows:

-   User is a member of a DAO
-   User holds an NFT in a collection
-   User holds at least 0.1 ETH
-   The result of any smart contract function call
-   User owns a specific wallet address
-   Using boolean operations (AND + OR) for any of the above
    
These composable conditions will enable information organization from two-person projects up to DAO-scale.

### Dataflow 
![Indexas Dataflow (5)](https://user-images.githubusercontent.com/1573640/204903890-a4461575-8ac0-44e3-b200-826ff4b626f5.png)

## Development Roadmap

 | # | Description | People | Funding | Period (week) | 
 | - | - | - | - | - |
 | 1 | Web3 Indexer API & Web App  | @serafettin @furkanozelge @serensandikci @nurinlowercase | USD 20,000 | 6 | 
 | 2 | Web2 - Web3 Bridge  | @serafettin @furkanozelge @serensandikci @nurinlowercase | USD 10,000 | 3 | 
 | 3 | Web2 Archiver  | @serafettin @furkanozelge @serensandikci @nurinlowercase | USD 10,000 | 3 | 
 | 4 | Collaboration Feature  | @serafettin @furkanozelge @serensandikci @nurinlowercase  | USD 10,000 | 3 | 

## Total Budget Requested

We requested $50,000 to accomplish the four milestones. The budget will be used as team salary.

## Maintenance and Upgrade Plans

The main goal for index.as and will be the basis for new features. Our next step is to continue improving the project as a team. Please refer to the link below for our future roadmap. Also, index.as is an open source project, and always open to community contributions and suggestions.

[Roadmap](https://pitch.com/public/b5a95ac8-8de0-4c85-9ba8-3d0d63da4432/cf8fc6ee-9708-4a7b-b93a-793996865894)

# Team

## Team Members

-   Seren Sandikci (Product Designer)
-   Nur Yildirim (Communications)
-   Serafettin Yarar (Project Lead, Software Engineer)
-   Furkan Ozelge (Software Engineer)
    
## Team Member LinkedIn Profiles

-   [https://www.linkedin.com/in/serensandikci](https://www.linkedin.com/in/serensandikci)
-   [https://www.linkedin.com/in/nuryildirim](https://www.linkedin.com/in/nuryildirim)
-   [https://www.linkedin.com/in/serafettin](https://www.linkedin.com/in/serafettin)
-   [https://www.linkedin.com/in/furkanozelge](https://www.linkedin.com/in/furkanozelge)

## Team Website

[https://index.as](https://index.as)

### Seren Sandikci
- Bachelor of Industrial Design
- User Experience Designer, IBM IX 
- User Experience Designer, QNB 
- 5 years in digital product design.
- Experienced in designing collaborative interfaces.
- Curator.

### Nur Yildirim
- M.A in Culture Management, B.A in Political Science
- Strategy Director, Publicis Groupe Istanbul
- Over 10 years' experience in brand and communication strategy. 
- Having an understanding of niche content creation & discovery.

### Serafettin Yarar
- Bachelor of Computer Science
- Co-founder and CTO,  Gowit Advertising Technologies 
- Over 10 years of experience in advertising, publishing, and media. Has a strong understanding of content monetization and distribution.
- Supports new media initiatives and fact-checking organizations such as teyit.org and Aposto. Also been working on blockchain and distributed systems since 2018 as a personal interest.

### Furkan Ozelge

- Bachelor of Computer Science
- 3 years in software development.
- Involved in building the current prototype using IPFS, DIDs, Ceramic Network, and LIT Protocol.

## Team code repositories

[https://github.com/indexas](https://github.com/indexas)

# Additional Information

- How did you learn about the Open Grants Program?
`IPFS Camp 2022`, `Protocol Labs Summit`
- Please provide the best email address for discussing the grant agreement and general next steps.
[serafettin@index.as](mailto:serafettin@index.as)
- Please include any additional information that you think would be useful in helping us to evaluate your proposal.
[Here is an example of an index](https://testnet.index.as/0x182590b8052072b9954B066ba5794E8eB5c67112/kjzl6cwe1jw149hsnxwnyx735bdxrttphnfcuj9juuhgbgltex5sbi5w1ynb59l) that we created to collect all the information about us.

**Comment by serensandikci** [comment]
Hi @ErinOCon @realChainLife,

Quick update: we're making progress and excited to keep building ⚡️

Any updates on our grant application? We are waiting for a feedback 🙂 

Let us know if you have any questions 👀

**Comment by ErinOCon** [comment]
Hi @serensandikci, thank you for checking in! We are currently reviewing a large number of proposals and hope to have more information available soon. 

In the meantime, can you briefly describe how/if users are currently engaging with your project? Do you have a timeline and plan in place for growing this user base?

**Comment by serensandikci** [comment]
Thanks for the update. 

We are constantly exploring new ways to connect with users, and we have recently adopted various approaches including:

Forming partnerships with protocols and apps to enhance interoperability and reach more users. Examples:
- Collaboration with [Veeo.io](https://www.veeo.io/), we are developing a shared data model to enable interoperable web annotations.
- We are implementing diverse data models on the [Ceramic Network](https://ceramic.network/), starting with a model to bring product data into web3 in an interoperable way. Thus, we plan to onboard brands to web3 as well.
- We are implementing a Video model on [Livepeer](https://livepeer.org/) to facilitate curated videos, which will enable DAOs (e.g., in education and research) to publish their resources in video format

Our tool can also be used by researchers in various fields, such as academia, business, and journalism, to create topical indexes of research and information. Example: 
- [CSMakers](https://www.csensemakers.com/) is using our Index schema to curate research and knowledge work.

Moreover, we are reaching individual creators across various domains, including artists, musicians, writers, and developers. They can leverage our tool to establish self-sovereign contexts and improve the visibility and accessibility of their content to potential audiences.

**Comment by ErinOCon** [comment]
Hi @serafettin, thank you for your proposal and for your time with our inquiries. After much consideration, we have determined that we will not be proceeding with a grant at this time. 

Wishing you all the best as you continue to build!

**Comment by serafettin** [comment]
Hello @ErinOCon ,

Sorry to hear that, and thank you for your consideration. 🙂
We continue to collaborate with IPFS in different ways, for sure!
