### ISSUE TITLE
[MICROGRANT] St3mz

### ISSUE THREAD

**Issue by Token-Factory-dApp** [ipfs/devgrants#269]
### 1. What is your project? (max 100 words)
A platform that allows artists to publish their music in the form of NFTs in the Polygon blockchain, so that other users can buy them acquiring also the rights to use the music with different levels of freedom.
Each audio track is an NFT based on the ERC1155 standard, but adapted to be transferable just once (when it is bought). This ensures that the buyer cannot resale the NFT after they have exercised the licensing rights associated with its purchase.

https://github.com/St3mz-dapp
https://st3mz-dapp.web.app/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
IPFS is used to store the audio files and the metadata of the NFTs. The front end application will also be stored in Filecoin with a service like Fleek.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
The application requires additional improvements to fulfill a high standard of quality:
- User experience improvements, including reponsiveness, additional form validations and enhancement of the overall design.
- For faster load times, caching NFTs data in a cloud service like AWS or Firebase.
- New section to track all the items created and/or owned by an account.
- Front end hosting in Filecoin though Fleek to increase the decentralization.
- Acquire a domain name.
 
### 4. Is this project open source?
Yes, it is under MIT license.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
https://gitcoin.co/hackathon/socialhour/projects/17184/st3mz
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Jota 
token.factory.dapp@protonmail.com
https://gitcoin.co/token-factory-dapp
Developer
* How did you learn about our microgrant program?
From Gitcoin's Discord.
* If your project was created as part of an event or hackathon:
  * What was the name of the event?
  Gitcoin Social Hour
  * Please link to your hackathon submission
   https://gitcoin.co/hackathon/socialhour/projects/17184/st3mz

**Comment by ErinOCon** [comment]
Hi @Token-Factory-dApp, this microgrant has been approved! We will send an email to confirm payment details. Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
