### ISSUE TITLE
[MICROGRANT] The Crypto Studio

### ISSUE THREAD

**Issue by Suhel-Kap** [ipfs/devgrants#272]
### 1. What is your project? (max 100 words)
TheCryptoStudio is a decentralized social platform that allows users to create and monetize NFT (non-fungible token) ERC115 collections as a space. These spaces include features such as a group chat, posts, and proposals, and each user has a profile showing their own posts and NFTs. The platform also includes the option to encrypt posts using the Lit protocol and custom or token-gated encryption rules, as well as verifiable credentials provided by Gitcoin Passport. Overall, TheCryptoStudio is designed to be a hub for NFT communities to connect and interact with one another.

The Crypto Studio Collection supports all kinds of NFTs like :

- Interactive visualizers using the CID of HTML pages
- Song Albums for singers, rapers, electronic music creators
- Just classic Image NFTs
- Ticket NFTs

[The Crypto Studio](https://github.com/Suhel-Kap/the-crypto-studio)
[Live Demo](https://the-crypto-studio.vercel.app/)
[Youtube demo](https://youtu.be/I24-SiVT1fg)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
Our project uses the nft.storage to securely store the metadata and distribute digital assets associated with non-fungible tokens (NFTs). This allows us to provide a decentralized and transparent system for managing the ownership and provenance of these assets.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- Research and evaluate different approaches for implementing artist collaborations and encryption on our platform using services like Orbis and Litprotocol with the help of our smart contract.
- Develop a plan for integrating these features into our platform, including changes to our user interface, data storage, and marketplace.
- Deploy a docker container to perform computations using services like StackOS.
- Provide the ability to artists to upload their own p5-js visualisations for the NFTs and write proper documentation for doing the same.

 
### 4. Is this project open source?
Currently, it is open-sourced under MIT License.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
[Protocol labs payment link](https://pl.coinemissary.com/transfer-requests/790330032908)
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
@nijoe1 Nick Lionis (nicklioniss@gmail.com) - Smart Contract Engineer
@Suhel-Kap Suhel Kapadia (suhelkapadia2@gmail.com) - Full Stack Engineer

* How did you learn about our microgrant program?
From the prize claiming email.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
We got the runner up for the Social Hour hackathon hosted on Gitcoin
  * Please link to your hackathon submission
 [Github link](https://github.com/Suhel-Kap/the-crypto-studio)

**Comment by Suhel-Kap** [comment]
Since it has been quite a few weeks since we opened this grant, we were working on it in the meantime and we would like to update the "How we would improve the project with this grant" section

So the updated points are:
- We are going to create an Economic model to reward us but also our users. By making GTM strategy, financing, user testing and feedback to understand what features most users need
- Instead of using a third-party blockchain for proposals we are going to implement an on-chain governor for each space that is going to comply with the openZeppelin governor standards and find a generic way to call a different kind of functions like dynamic nft features upon successful proposals from the community
- Instead of using the same contract we already have the knowledge to create a Proxy Contract Factory to improve the gas for our users, so we are going to introduce a dynamic collection factory with different kinds of contract implementations, Each one with its own dynamic features so users can choose what fits their needs best.
- We are going to make our contracts more gas efficient
- Deploy a docker container to perform computations using services like StackOS. For the HTML visualized NFTs and the IPFS file upload.
- Provide the ability to artists to upload their own p5-js visualisations for the NFTs and write proper documentation for doing that.

**Comment by ErinOCon** [comment]
Hi @Suhel-Kap, than you for the provided updates! This microgrant has been approved! We will send an email to confirm payment details. Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). 

Please let us know if you have any questions!
