### ISSUE TITLE
[MICROGRANT] Flex Nodes

### ISSUE THREAD

**Issue by tesol2y090** [ipfs/devgrants#275]
### 1. What is your project? (max 100 words)

Flex node allows users to write graphql query commands or our template command to query on-chain activities such as borrows events in compounds on Polygon mainnet or nft holding in opensea on Ethereum mainnet and store those file as json file into ipfs via web3.storage.

When smart contract want to calculate those file, we also provide chainink external adapter to get those file and compute on chainlink node and send result back into smart contract.

https://github.com/tesol2y090/flex-node
https://flex-node.vercel.app/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

We use IPFS to store and retrieve on-chain data that smart contract create it that point CID each user on smart contract.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We will make flex node smart contract on FVM for store and retrieve on-chain data.

- Create core smart contract on FVM to store and retrieve data on IPFS.
- Create dynamic query command.
- Add signature verification when query data.
- Support more chain.
 
### 4. Is this project open source?

Yes, all project in flex nodes will continue open source.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, we will update with the report every week util finish.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions

https://devpost.com/software/flex-nodes
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  Name: Kantapat Chankasem
  Email: gangkantapat@gmail.com
  Github: https://github.com/tesol2y090

* If your project was created as part of an event or hackathon:
  * Chainlink Fall Hackathon 2022
  * https://devpost.com/software/flex-nodes

**Comment by ErinOCon** [comment]
Hi @tesol2y090, thank you for your proposal and for all of your patience with our unexpectedly long review process. We will not be moving forward with a grant at this time, but are wishing you all the best as you continue to build.

Thank you again for your interest in our grants program!
