### ISSUE TITLE
[MICROGRANT] pRoots-IPFS-cli-tool

### ISSUE THREAD

**Issue by weitinglin** [ipfs/devgrants#276]
![logo](https://shdw-drive.genesysgo.net/6WSW4N85PxPUFVrjB41vicn5ZqZRWA4SDuqtczAnjtLA/little%20LOGO.png)
### 1. What is your project? (max 100 words)
[pRoots](https://github.com/Proots-Foundation/proots-doc) **IPFS command line tool** is what we want to apply for the IPFS  microgrant. pRoots is a desci project found from GR15. and we want to build web3 infrastructure on genomic data, currently focusing on plasmid data use case first. 

**IPFS-cli-tool** will enable people to check, compress, upload, search, fetch, and compute genomic data(fasta currently) under the DAG-PLASMID IPLD schema into IPFS and use our tool for local computing to implement ADL in genomic applications such as k-mer indexing. As we deep dive into IPFS, we also found more we can imagine of building future web3 biotech lab tools on this ecosystem.

Overall pRoots github doc: [pRoots doc](https://github.com/Proots-Foundation/proots-doc)
pRoots **Command line tool**[repo](https://github.com/Proots-Foundation/proots-cli-ipfs)
pRoots **DAG-PLASMID** [repo](https://github.com/Proots-Foundation/pRoots-DAG-PLASMID)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
  In this microgrant support, we will use it to build command line tools for scientist or citizen scientist to interact IPFS under genomic data format fasta user case.  We need to understand and depend on the underline repositories related to IPFS ecosystem:

**IPFS**

- ipfs specs
- kubo
- libp2p
- multiformatcs

**IPLD**

- libipld
- js-car
- js-dag-json
- js-ipld-schema

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Under this grant, we want to build this command line tool pRoots-ipfs-cli for pRoots project. Below is what we will do and need to solve.

:black_square_button: **DAG-PLASMID**

complete the version 1 IPLD schema design for plasmid data in IPLD schema files. define the nodes and kinds in the data model. 

:black_square_button: **Command Line Tool: pRoots-ipfs-cli**
 1. **check** : check the data format whether follow the DAG-PLASMID , alert possible error spec in the data
 2. **convert**: turn fasta into DAG-PLASMID compatible object 
 3. **compress**: compress fasta sequence or serialization of the data for better upload  experience
 4. **upload**:upload the DAG-PLASMID compatible objects into IPFS network
 5. **search**: search objects in IPFS network, which compatible with DAG-PLASMID. we will also create public IPSN for curated plasmid data from iGEM, addgene and NCBI.
 6. **fetch**:download the object compatible with DAG-PLASMID in IPFS network into local
 7. **compute**: computing or indexing the fasta data for possible ADL application

:black_square_button: **Questions/Ideas**
 1. Can or Should there be a CID designed specifically for genomic data (ATCG...), which can deduplicate the sequence data.
 2. Should there be a genomic-specific hash method for building CID, which is more efficient, small
 4. How we can design DAG-PLASMID, which enables to build native knowledge graph in the IPFS under the data structure design
 5. Can we use IPSN as a public or curated plasmid data structure intro under DAG-PLASMID spec and make people use it under the command line as a data endpoint
 6. Build test data set from curated plasmid data in order to test and learn from using the command line tools
 
### 4. Is this project open source?
pRoots IPFS command line tool will be open source under MIT license.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, the report will contain the above stuff we want to figure out and build, contain:
- version 1 DAG-PLASMIDs schema, and the design thinking align with how to aggregate the plasmid data into a graph knowledge network native in IPFS
- the implementation result of pRoots-ipfs-cli and the details how we implement and the future to do list
- the experiment process of using current public plasmid data set to use our pRoots ipfs cli 

### 6. Does your proposal comply with our Community Code of Conduct?
Our project is also under the same scope with Community Codes of Conduct to Filecoin Code of Conduct.

### 7. Links and submissions
We are referred to apply microgrant after winning [2022 gitcoin social hour hackathon](https://github.com/ipfs-and-filecoin/hackathons-bounties/issues/15).1st Runners up. We are also planning to apply other parts of tools using FVM on Filecoin microgrant in the near future.

![20221220 v1](https://shdw-drive.genesysgo.net/6WSW4N85PxPUFVrjB41vicn5ZqZRWA4SDuqtczAnjtLA/ppt_blueprint_v1.png)

pRoots found from [GR15](https://gitcoin.co/grants/7445/proots-empower-people-to-store-share-annotate-and). Below are our current team members and as our project grows more complex, we are also looking for people aligned for the desci direction in web3.
- [Weiting Lin](https://t.co/elU5wwOvpc)| email: weitinglin66@gmail.com | github: https://github.com/weitinglin | bioinformatician
- [Chitaolang](https://twitter.com/chitaolang) | email: tingyilin91@gmail.com |github: https://github.com/chitaolang | blockchain engineering
- Social Hour Hackathon submission: [repo](https://github.com/Proots-Foundation/proots-client-v1), [gitcoin link](https://github.com/ipfs-and-filecoin/hackathons-bounties/issues/15)

**Comment by ErinOCon** [comment]
Hi @weitinglin, thank you for your proposal and congrats on the progress made thus far! For next steps, I would recommend checking out [accelerator opportunities].(https://ecosystem-wg.notion.site/Protocol-Labs-Accelerator-Program-d45d8792a7d544eca9beb7d3e3d3b05d) 

We are not proceeding with a microgrant for this particular proposal, but will be in touch with more information regarding [pRoots-FVM-computegenomics](https://github.com/filecoin-project/devgrants/issues/1293) soon. Thank you again for your time with this submission. Wishing you all the best as you continue to build!
