### ISSUE TITLE
Next Step Microgrant: Upgrade-doge - A visual EVM/FVM contract upgrade tool

### ISSUE THREAD

**Issue by FWangZil** [ipfs/devgrants#277]
### 1. What is your project? (max 100 words)

The owner of a Web3 project is sometimes not the same person as a developer with contract upgrade privileges. As a result, there are often security incidents caused by disclosure of private keys or left bank of insiders, such as the Token additional issuance accident that occurred in Ankr last month.

Therefore, we provide the following features for Openzeppelin-based upgradeable contracts:

1. [Manage proxy contract](https://docs.upgrade-doge.xyz/use-cases/manage-proxy-contract)
   * View contract permissions and administrators and manage them easily
2. [Create-notifications](https://docs.upgrade-doge.xyz/use-cases/create-notifications)
   * Subscribe to contract permission changes via Email

Front-end: [GitHub Repo](https://github.com/doge-verse/contract-tool-web) Back-end: [GitHub Repo](https://github.com/doge-verse/easy-upgrade-backend)

Demo: [Demo website](https://www.upgrade-doge.xyz) Doc: [Documents](https://docs.upgrade-doge.xyz/)

#### Fleek

Our front-end web page is deployed on IPFS, and we immediately implemented upgradeable contract support for FVM networks.

#### web3.storage

Due to privacy concerns, all information related to our user contracts is processed locally, and in the future we will provide an option for users to choose to encrypt and store this data on IPFS to prevent loss, so that users can use authorized accounts to manage their contracts anywhere.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

This microgrant will fund the following research,technical and community work:

#### Research

- Continue to investigate contract security related issues and solutions
- Research provides more effective tools for the WASM version of FVM

#### Technical/ UX Upgrades

- Create official website, optimize dapp user experience, and invite professional designers to design logo and UI.
  - We've already started this part of rebrand.
- Completion feature: contract upgrade information can be stored in IPFS and a certain encryption scheme can be designed, and users can verify the signature of their wallet address to recover the data backed up in IPFS.
- Expand additional alert notification types and channels, such as Slack/Telegram/Discord

#### Community

- Create Mirror/Medium blog post about the Upgrade-doge project and create Twitter accounts and interact with users.

### 4. Is this project open source?

Yes. All the code is under <https://github.com/doge-verse>

Ps. Doge is part of the name of our team during the [Antalpha Hackerhouse 2022](https://labs.antalpha.com/hackerhouse)

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions

- If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  - [Antalpha Hackerhouse 2022](https://labs.antalpha.com/hackerhouse)
  - <https://www.notion.so/Upgrade-Doge-upgradeable-smart-contract-toolkit-5c7f4bed24dc45d69ac64436cf463006>

### Additional questions

- For each team member(s), please list name, email, Github account, and role in the project.

  | Name          | Email                | GitHub Account                    | Role                |
  | ------------- | -------------------- | --------------------------------- | ------------------- |
  | metanomad2082 | v12924543@gmail.com  | <https://github.com/metanomad21>  | front-end developer |
  | JM            | xjmsvip@qq.com       | <https://github.com/Caploef-Xie>  | front-end developer |
  | Zelig         | zeliangchu@gmail.com | <https://github.com/JangoCCC>     | back-end developer  |
  | inftor        | justemo247@gmail.com | <https://github.com/AMARAjustone> | back-end developer  |
  | Merlin        | acewzk@gmail.com     | <https://github.com/FWangZil>     | back-end developer  |

- How did you learn about our microgrant program?
  - Learned from [Antalpha Hackerhouse 2022](https://labs.antalpha.com/hackerhouse)
- If your project was created as part of an event or hackathon:
  - What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
    - Antalpha Hackerhouse
  - Please link to your hackathon submission
    - <https://www.notion.so/Upgrade-Doge-upgradeable-smart-contract-toolkit-5c7f4bed24dc45d69ac64436cf463006>

**Comment by ErinOCon** [comment]
HI @FWangZil, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
