### ISSUE TITLE
[MICROGRANT] Word Block

### ISSUE THREAD

**Issue by monica-ty** [ipfs/devgrants#278]
### 1. What is your project? (max 100 words)

*block-based note-talking tool with ownership control*
https://github.com/fat-garage/wordblock

#### Wordblock extension

- You can clip any text from any website, add tags, comments, and save the location (URL) as *metadata*.
- You can write block-based memos, add tags and extra information(e.g. the real location: 📍🚶‍♀️38W,4S).
- The text is generated under the user's own DID signature, while data is stored on IPFS to enable public search.
https://chrome.google.com/webstore/detail/wordblock/jbihofgilkjgaofihhklnkeocejckcjk?hl=en-GB

#### Wordblock.xyz - a global text block search engine

- All the word blocks created will be pooled in one place for **public search**, or later public *reference*.
- For example, you can process public block searches via tags, keywords, or user DID
https://fat-garage.github.io/wordblock/

#### Ceramic Streams

Wordblock uses Ceramic Stream to store a JSON metadata of a block. Metadata includes BlockID, Creation Date, Source URL, Author, Tags, Type and Content. The DID of the user submitting the block to the Ceramic network is also bound to the metadata. The Wordblock data model can be shared between any applications on the Ceramic network.

#### web3.storage

Wordblock uses web3.storage for data backup and permanent storage. Our backend API can get all the blocks created by the given user DID to implement a global search on the wordblock.xyz page.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- A data graph
  - Migrating from Ceramic Streams to Ceramic ComposeDB to support complex network relationships and apply GraphQL queries among accounts, wordblocks, tags to implement deep-level searches/comments/references.
  - we are in the early stage of defining data as an asset with maturing infrastructure like IPFS, Ceramic network, dataverseOS etc, the excitement of web3 is the data as streams that can be visualized and later used by individuals. We could first collect those fragmented attentions 👀 with ease, and then browse/ the data, or re-organize(reference) with personal signature.
- A social graph
  - After collecting those text blocks, it is easy to form P2P social relations(e.g. walletChat) via tag matching
- Semantics algorithms
  - More detailed searching with combined keywords, tags, DIDs, and DNS.
  - Recommendations/Feeds based on submitted blocks and/or searching history.
 
### 4. Is this project open source?

Yes, with [AGPL-3.0 license](https://github.com/fat-garage/wordblock/blob/main/LICENSE)

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  Yes, we submitted https://devpost.com/software/the-word-block/ to [Web3 Infinity Hackathon](https://web3infinityhackathon.devpost.com/)
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

| Name | Email | Github Account | Role |
| ------------- | ------------- | ---------- | --------- |
| Jessie Lee | jessie@fat-garage.com  | https://github.com/lg565245594 | Initiator/Prototype Designer |
| Qibing Lee | qblee@zju.edu.cn | https://github.com/QibingLee | Consultant/Technical Guidance |
| Qijin Zhang | jinqizing@gmail.com | https://github.com/qijinzing | Project Manager |
| Tongyu Zhao | tongyuz@andrew.cmu.edu | https://github.com/monica-ty | Researcher/Database |
| Peihan Lee | 291630202@qq.com | https://github.com/lpeihan | web and extension developer |
| Merlin | acewzk@gmail.com | https://github.com/FWangZil | IPFS and back-end developer |
| Hedong | lhd791150351@gmail.com | https://github.com/lhd791150351 | Ceramic and front-end developer |

* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @monica-ty, thank you for your proposal and for your patience with our review process. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
