### ISSUE TITLE
Open Grant Proposal: HotSkills - blockchain marketplace for freelancers

### ISSUE THREAD

**Issue by vadkutsen** [ipfs/devgrants#279]
# Open Grant Proposal: HotSkills

**Name of Project:**
HotSkills

**Proposal Category:** 
`app-dev`

**Proposer:**
vadkutsen

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:**
Yes

# Project Description

Crypto freelance marketplace. Get paid for work in cryptocurrencies.

Problems we are trying to solve:
1. Web2 freelance platforms do not offer payments in cryptocurrencies and charge high fees.
2. Existing web3 freelance platforms are not user-friendly:
- require registration with email and full name;
- use platform wallets to receive freelancers’ rewards and then freelancers have to withdraw crypto manually;
- require buying and staking their tokens.

The solution we offer:
1. We offer fast and secure payments in cryptocurrencies and low fees.
2. We don’t require registration - just connect your wallet.
3. Freelancers receive rewards automatically and directly to their wallets.
4. Free access - no buying tokens or staking needed.

## Value

HotSkills will promote mass adoption by attracting freelancers to the crypto world.  HotSkills platform also encourages active use of the  IPFS/Filecoin (web3.storage) to store the results of executed tasks, store service galleries, and store user profile images.

## Deliverables

Web3 freelance platform:
- a web interface built with React for interacting with smart contracts and for storing data on IPFS/Filecoin;
- smart contracts built with Solidity and deployed to multiple blockchains; 
- a landing page that contains all necessary info about the project.

## Development Roadmap

Milestone 1:

1) Add an image gallery to services (multiple images uploading to the web3.storage).
2) Add a message system to allow communication between buyers and sellers.
3) Add arbiter functionality to allow arbiters to handle disputes.
4) Add a contest functionality (multiple users can submit results (stored on the web3.storage) and the contest author can select a winner).

People involved: vadkutsen.

$10 000

2 month.

Milestone 2:

1) Expand multiple blockchains support.
2) Community growth & engagement.
3) Marketing phase 1.
4) Public incentivized testnet.
5) Feedback analysis, bug fix, improvement suggestions implementation.

People involved: vadkutsen.

$20 000

3 month.

## Total Budget Requested
$30 000

## Maintenance and Upgrade Plans
Maintenance and bug fixes will be performed on a regular basis as well as feedback analysis and system upgrades in order to improve the project.

# Team

## Team Members
Vadym Kutsenko (vadkutsen) - founder, full stack web3 developer.

## Relevant Experience
I'm a  full stack web3 developer with 8+ years of hands-on experience in Software Development (full stack web development, test automation, QA) and over 1.5 years of experience in web3 development.

## Team code repositories
https://github.com/vadkutsen

# Additional Information
-- How did you learn about the Open Grants Program?
Email from IPFS/Filecoin.

My email: vadkutsen@gmail.com

**Comment by ErinOCon** [comment]
Hi @vadkutsen, it looks like you already completed the outlined project - congrats! If you have an interest in sharing the results of your work, please feel welcome to email grants@filecoin.org.
