### ISSUE TITLE
[MICROGRANT] Drone Monitor

### ISSUE THREAD

**Issue by seetadev** [ipfs/devgrants#281]
### 1. What is your project? (max 100 words)

Ensure effective design, engineering and delivery of solution for detecting & managing UAVs & Drones using Ethereum, IPFS & Filecoin eco-system tools, modular iot gateway device solution and Layer 2 scaling solutions.

Features: 

•Detection : Identifying the UAVs in the video feed using object detection.

•Discovery : Logging the identities of UAVs flying in a particular air space, using exchange of unique identifiers.

•Geo-fencing : Discovering unlawful presence, raising alarms using w3ui.

•Monitoring and Reporting: Looking out and reporting incidents based on event detection in files uploaded using w3ui.

•Analysis : Analyzing route patterns and incidents.

Github Repository:  https://github.com/aspiringsecurity/Water-ICM (Layer 2 scaling, smart contracts compiled to FVM, use-cases and hardware-software interaction)

https://github.com/seetadev/PolyOps (smart contracts compiled to EVM and FVM) 

Websites: https://sites.google.com/view/latcglobal/home

https://sites.google.com/view/dronesforrealestate/home (drones for operations and maintenance) 

https://sites.google.com/view/integratedwatermanagment/home (Drones for Water Monitoring).

Link to the Demos:  

Frontend Demo: https://www.youtube.com/watch?v=dk3TQlEsxfo&t=3s (software) 

Screen Capture of mobile dapp demo with IPFS storage of incidents and smart contract prototype: https://drive.google.com/drive/u/3/folders/1l9ZG65js2Q-a1m8Iy3BO25dWISqr3oPk (please visit the file screen_capture_without_sound.mov )

Hardware-software Demos (End Node Commissioning of nodes using NFC tag, iot modular gateway): Please visit https://www.youtube.com/watch?v=vNKONKA2sow&t=2s and https://www.youtube.com/watch?v=XOq55l0NIZI

Use-case demo: https://www.youtube.com/watch?v=dqR-I70UT1I&t=74s (drone monitor for integrated water management)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

IPFS is the key pillar of our project as all the drone routing and incident data is saved at IPFS. We are using IPFS for storing a variety of incident data like incident snapshots, alarm metadata and object types at the time of incident. Please visit the demo videos at https://drive.google.com/drive/u/0/folders/1V8OCwu_MJmyAHQVbbepzsR8_igx5huer and https://drive.google.com/drive/u/3/folders/1AUdsHAcUPTF85gVk93w8tzfEzbD7K6-Y

We are using web3.storage’s w3ui to upload and store geolocation file data and and map data. We are also storing Alarm metadata at IPFS;  Saving/deleting alarm metadata and image to/from IPFS; Video analytics configuration and IPFS for incident snapshots. 

  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We will be focusing on the following objectives with the Microgrant:

1.  We wish to develop an incident notes tool for the drone and UAV administrators using web3.storage’s w3ui. We also wish to implement web3.storage developer platform to use decentralized protocols for enabling better citizen mobilization for creating incident data along with its relevant metadata.

2.  We plan to decentralize key components, bottlenecks in our existing IPFS solution.

3.  Integration: We wish to integrate Livepeer’s IPFS playback tool with web3.storage’s w3ui and w3up for better outcomes in aerial traffic control. We also wish to integrate our solution with filecoin based lighthouse storage sdks for better access control and Webnative edge computing stack for reducing overall operational costs.

4.  For the administrator's role, we wish to store the relevant information on a drone or UAV incident at IPFS and enable investigative case management solution for early-stage detection and prevention of incidents.

5. Learning with Wing (https://wing.com/): We are extending and developing our platform for path planning, guidance, navigation and control utilizing the strengths of programmatic DAOs available in Filecoin Virtual Machine.  The path planner is used in all Wing business operations, which as of 2022 is greater than 300,000 flights in 3 continents. We can also utilize IPFS and Filecoin to store geolocation data, drone review and ratings data, incident and routing data in Wing's fleet of lightweight, autonomous delivery drones, which can transport small packages directly from businesses to homes in minutes. 

6.  Learning with Thales Group (https://www.thalesgroup.com/en) and ZF Mobility (https://www.zf.com/site/zms/en/zms.html): We are extending and adapting our platform for aerial taxis. We wish to use FEVM for compiling smart contracts. FEVM enables us to use composable and stackable building blocks and primitives exposed through standardized interfaces, enabling the construction of interconnected solutions, thereby improving better outcomes. We wish to spend quality time on understanding how we can utilize the strengths of FEVM in our smart contracts.

7.  Development of Rotable Levels Planning software tool for spare parts, inventory management of drones; Repair Invoice dapp, Building Maintenance Planner using an OSS spreadsheet solution with Filecoin storage: We wish to develop Post PC applications namely Repair Invoice and Building Maintenance Planner for enabling drone service providers to actively participate in improving the aerial transport conditions by providing instant maintenance to drones and UAVs with breakdown or damage. We will extend and adapt EtherCalc for a Post PC interface with persistent file storage of Filecoin for data analytics. We also wish to explore IPFS integration with key open-source computer vision librariers like PyTorch, Tensorflow and analytics tools like R, Scipy, Matplotlib, Octave and Power BI.

 
### 4. Is this project open source?

Yes, the project is open source with license type: MIT License.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, definitely. We would share a final grant report at the end of 3 month period.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

We participated at the Moralis Filecoin 1,2,3 hackathon (https://moralis.io/filecoin-hackathon/) and won multiple prizes (please watch the video at https://www.youtube.com/watch?v=a_2n0sEPuxc and visit the website at https://moralis.io/filecoin-hackathon/winners/ )

We won the filecoin prize for both our submissions: Drone Monitor and Eth Transport and received a sum of 1429 FIL. We learned about the Filecoin microgrant from the prize email as well as a memo from Niki Gokani, Eco System Growth at IPFS and Filecoin, who motivated us to scale up our project. Wish to also share that we won XMTP pool prize for Drone Monitor project.

We extended the project and focused on its applications at the Encode x Harmony Hackathon, Encode x Next Video Build and Garuda 3.0 Hackathon. We won the Covalent prize (1000 USDC) and Harmony prize (20906 ONE).  Please watch the video at https://www.youtube.com/watch?v=62hrsmOShhg and visit the link at https://medium.com/encode-club/encode-club-x-harmony-hackathon-prizewinners-and-summary-e088485c8af7

We won the best use of Hedera Hashgraph at the Garuda 3.0 Hackathon. Please find the winner's certificate at https://drive.google.com/drive/u/3/folders/1l9ZG65js2Q-a1m8Iy3BO25dWISqr3oPk (merit certificate directory) and winner's link at https://garuda-hacks-3-0.devpost.com/project-gallery

We won the Aptos Challenge (5000 USDC) at Encode's Next Video Build Hackathon: https://www.encode.club/next-video-build. Please find the finale and prize giving video: https://www.youtube.com/watch?v=2USgb11kYzY and blog entry at https://medium.com/encode-club/next-video-build-hackathon-prizewinners-and-summary-33f258fdc9f5
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Manu Sheel Gupta: Email (Email: manu@seeta.in , aspiring.investments@gmail.com ) (Github: https://github.com/seetadev )
Manu is the software architect and full stack engineer in the project. He is responsible both operationally and strategically to enable sustaining and scaling the project. He is also responsible for developing collaborations in the Blockchain eco-system and managing the project roadmap, milestones along with the feature spec and code freeze timelines.

Deepti Gupta: (Email: deepti.kotwal.2011@gmail.com ) (Github: https://github.com/aspiringsecurity/ )
Deepti brings years of experience of developing mobility solutions at SAP and is responsible for the UI/UX design, workflows and recommending key methods to effectively utilize the strengths of IPFS as the decentralized storage solution.

Vibhor Bijoy: (Email: bijoy.vibhor19@gmail.com ) (Github: https://github.com/vibsdrockstar )
Vibhor is our expert on developing security solutions and compliance software. With multiple years of experience at Thales (https://www.thalesgroup.com/en ), he will enable us to build a decentralized mobility solution using IPFS that can be trusted and deployed in a variety of topographies. He will enable us to do a pilot project at IIT Delhi campus in Delhi.

Praveen Patel (Email: android.seeta.dev@gmail.com)  Praveen is our support and logistics executive, who looks after maintenance and support efforts. He is from an agricultural background from Bihar (India) and will enable us to utilize our platform more effectively in an agricultural setting. Praveen's native place is Muzaffarpur, where agricultural fields experience consistent flooding for a number of months every year. We look forward to mapping our solution for better outcomes and productivity in food and agricultural management, integrated water monitoring.

Raghav Kumar: (Email: dev@seeta.in) ( GIthub: https://github.com/thisisraghavkumar ),  Raghav is responsible for solving all the key issues around the implementation of smart contracts and IPFS. He has been responsible for enabling us to use Ethereum blockchain with IPFS effectively. He has also enabled us to bootstrap our efforts on improving the unit testing of our smart contracts and will enable us to scale our efforts.

Geetanshu Gupta (marketing@tickervalue.com)  (Github: https://github.com/geetanshu2502 ) Geetanshu is both a frontend as well as the backend engineer. He is a great UI/UX designer and will be enabling us on the design aspects of the project.

Project Advisers

Dr M.P.S. Bhatia : (aspiringuserapps@gmail.com ) Dr MPS Bhatia is the key enabler on piloting this project at Delhi and California. He is our go to mentor on building business partnerships with Ministry of Airways and Transportation, Wing (www.wing.com) and D.R.D.O.  (https://www.drdo.gov.in/) and also build up the collaboration on hiring software engineers specializing in IPFS. He teaches Computer Science to engineering students, Phds and MTech students) and enables us on both technical as well as business fronts (please visit http://www.nsit.ac.in/faculty/mps/)

Usha Gupta (Email: seeta.team@gmail.com) Usha Gupta is an agripreneur (agriculture entrepreneur) and social educator, who owns a smart garden covering a large size and utilizes smart water management and cultivation practices for growing lemon, pomegranate and guava trees. She will be our collaborator and guide on enabling us to pilot and deploy drone monitor with IPFS and filecoin backend in her smart garden. We wish to utilize data dao analytics using FVM to enable better outcomes in her gardening practice.

Arvind Kumar Gupta (Email: arvindsenior@gmail.com) Arvind Kumar Gupta comes from metallurgy and copper refining industrial experience. He will be enabling us in piloting drone monitor solution with IPFS as the decentralized storage in Delhi based industrial factories for preventive maintenance of machines, better supply chain and improved asset management. We also look forward to learning and collaborating with him on how we could use FVM for enabling perpetual decentralized storage in key industrial use-cases and application reports.

Vithika Gupta: (aspiringworkapps@gmail.com) Vithika is our go to guide on implementing iot stack and integrating with IPFS and open source video streaming solutions. She guides us on key iot protocols and their implementation.

* How did you learn about our microgrant program?

We learned about the Filecoin microgrant from the prize email as well as a memo from Niki Gokani, Eco System Growth at IPFS and Filecoin, who motivated us to scale up our project.  

* If your project was created as part of an event or hackathon: Moralis Filecoin 1,2,3 hackathon (https://moralis.io/filecoin-hackathon/ )

  * Please link to your hackathon submission: Moralis hackathon submission was via a google form. Please find the submission materials at https://drive.google.com/drive/u/3/folders/1l9ZG65js2Q-a1m8Iy3BO25dWISqr3oPk
  
  * Github Repository at https://github.com/seetadev/PolyOps

**Comment by ErinOCon** [comment]
HI @seetadev, thank you for your proposal! It is generally our process to award one microgrant at a time. Since [this proposal ](https://github.com/ipfs/devgrants/issues/263)is currently active, we will not be moving forward with an additional grant at this time. 

Please feel welcome to check back in for future grant opportunities. We will be rolling out [specific focus areas](https://github.com/filecoin-project/devgrants/blob/master/microgrants/microgrants.md#focus-areas) throughout the year!

**Comment by seetadev** [comment]
Thank you so much for your encouragement, support and kind feedback. Appreciate it. Wish to share that we completely agree and would like to thank you and the Filecoin team for awarding us a Microgrant. On the same note, wish to add that we applied after we receive an invitation link on winning the pool prize at Moralis Filecoin hackathon. We are more than satisfied and happy with the support and encouragement currently provided and the wonderful opportunities that are available for us to learn, contribute and collaborate in the IPFS and Filecoin community.
