### ISSUE TITLE
Next Step Microgrant: Bountyz

### ISSUE THREAD

**Issue by kaushikmrl** [ipfs/devgrants#282]
### 1. What is your project? (max 100 words)
Learners' dropout rate is up by 67 % with most of them leaving due to a lack of Motivation and
engaging content. We need to fix this problem by focusing on ways to Motivate the users, Personalise
and Reward their learning journey.

Edutech dApp (Bountyz) build to reskill and upskill the learning community across the globe. Bountyz makes
them more productive and efficient by providing personalized content, learning pathways with AI-driven
recommendations (future roadmap) and by using LTEM (Learning-Transfer Evaluation / Kirk Patricks
Model) to increase ROI on learners' journey. Bountyz Incentivizes learners by streaming rewards when a
certain milestone is achieved.

https://github.com/bountyzz

https://bountyz-ui-fvjdwx.spheron.app/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
One of the main use cases of Bountyz is the Edtech platform, which enables content creators to create educational content. The videos and assessments used in the platform will be stored and retrieved dynamically using IPFS. Currently, we have only implemented IPFS for storing and retrieving assessment questions (json files).
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We built Bountyz as an MVP during HackFS for incentivizing learners when certain milestones are achieved during the learning path.

With the grant, we plan to build/iterate on the following features but not limited to, for release:
* Implement IPFS for storage/retrieval of video files for content creators and the learners
* Providing SBTs for the learners on milestone achievements
* Enhanced UI/UX with additional functionalities to upload, retrieve and embed video content based on IPFS.
* Implement push protocol for sending notifications
* User acquisition and onboarding
 
### 4. Is this project open source?
Yes. MIT License

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes. We will provide updates upon request and a final grant report at the end of the three-month period.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes. Our proposal complies with the Community Code of Conduct.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
This is our submission at HackFS2022: https://ethglobal.com/showcase/bountyz-nj85m
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
 Kaushik Murali: [kaushik.mrl@gmail.com](mailto:kaushik.mrl@gmail.com); https://github.com/kaushikmrl; product manager
 Ram Vittal: [ramvittal@gmail.com](mailto:ramvittal@gmail.com); https://github.com/ramvittalkumar; fullstack developer
 Sajith Mohideen: [s.sajith.mohideen@gmail.com](mailto:s.sajith.mohideen@gmail.com); https://github.com/SajithMohideen; fullstack developer
* How did you learn about our microgrant program?
After our submission to HackFS 2022, Nikigoakani from protocol labs reached out to us to apply for further grants and evolve the product.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  HackFS2022
  * Please link to your hackathon submission
We created the project during HackFS 2022.
Submission: https://ethglobal.com/showcase/bountyz-nj85m

**Comment by ErinOCon** [comment]
Hi @kaushikmrl, thank you for your proposal. We will not be moving forward with a grant at this time, but wish you all the best as you continue to build!
