### ISSUE TITLE
IPFS devgrants readme points to filecoin's grant

### ISSUE THREAD

**Issue by RonaldZielaznicki** [ipfs/devgrants#287]
The main README.md file for devgrants links to filecoin's grant program.

I am not sure this is intended since there are still grants listed here. But, looking at the issues posted from before and after the change, there was a significant drop in new issues after the change to the readme.

If IPFS is still taking in grants, this confusion could explain why the drop in new issues / grant applications.

Changes occured in https://github.com/ipfs/devgrants/commit/947e3468f0088ad4f7d89fc25fc48509b23b6d35, where several readme links were changed to filecoin ones. On top of the updated content.

**Comment by ErinOCon** [comment]
Thanks, @RonaldZielaznicki! Dev grant proposals are now managed under the [Filecoin Project repo](https://github.com/filecoin-project).
