### ISSUE TITLE
Microgrant: Decentralized Online Digital Library

### ISSUE THREAD

**Issue by tani** [ipfs/devgrants#52]
### What do you work on? (max 100 words)

I am a Ph.D. student of JAIST. My research interests lie in the area of formal semantics of natural language, and programming language. I am working on an online digital library of public domain Japanese novels to save for the next 20 years. As Japan law has extended copyright protection period since 2018, the two largest online digital libraries in Japan, Aozora Bunko, and Project Sugita Genpaku, faced with difficulties to maintain for expiring copyright protection. While the internet archive passively archives contents, my project archive's contents with pinning contents.

These contents are used by [natural language processing researches](https://ci.nii.ac.jp/search?q=%E9%9D%92%E7%A9%BA%E6%96%87%E5%BA%AB+OR+aozorabunko&range=0&count=20&sortorder=1&type=0) and [Japanese educations](https://sheffield.libguides.com/guideeastasian/databasesjapanese) for example.

### How are you planning to incorporate IPFS into your work? (max 250 words)

1. Create IPFS directory for these books.
2. Add [client side full text search function](https://github.com/nextapps-de/flexsearch), and readers for [epub](http://futurepress.org/) and [pdf](https://mozilla.github.io/pdf.js/) .
3. Create software to read these content with IPFS for mobiles.

Phase 1: There are pioneers about the Project Gutenberg, and it is trivial but serious phase as; 
- IPFS and IPNS will be post-DOI (Digital Object Identifier) of publication.
- IPFS ensures the editing history of content. The online digital library updates books but its edit history is closed for readers. IPFS solves this issue. 

Phase 2:  The library does not only provide books, but also interfaces to find new books. We are going to create an efficient index for over 15, 000 novels. That is too large to load at once. As the brief idea, we can split index by first two letters such as index.aa.json, index.bb.json, and dynamically loads these indexes. As the result, the user reads the content in the browser.

Phase 3: This is the most important concept of this proposal. The reward is important to become decentralized online digital library. This software pins the content in the mobile, the reader can read content offline as rewards. The offline situation happens often daily life, for example, airplanes and subways. The users will want the reward when they faced such situations. Hence, this reward is more instantly and clearly.

### Website(s) (CV, GitHub, personal page...)

TANIGUCHI Masaya, [CV](https://www.docs.casa/profile.html), [GitHub](https://github.com/tani/)

### Will the work be Open Source? (if not, explain why)

Yes, I hope to visit the largest online digital library on the planets like primitive world wide web.
I will publish these softwares on the IPFS and GitHub.

### Does your proposal comply with our Community Standards?

I agree with https://github.com/ipfs/community/blob/master/code-of-conduct.md

**Comment by mishmosh** [comment]
hi @tani, apologies for the very long delay. our grant process is back up and running, with some small tweaks to the program which you can read at https://github.com/ipfs/devgrants/blob/master/MICROGRANTS.md.

are you still working on the decentralized online digital library, and if so are you interested in being considered? we now review applications every 2 weeks, so you would have a response within 2 weeks of submission.

**Comment by ErinOCon** [comment]
Hi @tani, this Issue has been closed. If you still have an interest in receiving a grant for this work, please do not hesitate to open a new ticket. We would love to hear of your progress!
