### ISSUE TITLE
[MICROGRANT] an asynchrous jam session web app for musicians

### ISSUE THREAD

**Issue by felixniemeyer** [ipfs/devgrants#66]
### What do you work on? (max 100 words)
This is for musicians who want to exchange and build on their musical ideas with their friends remotely. 
Latency keeps musicians from having real time online jam sessions over the network. A convenient way to record a groove and send it to our friend for him to add vocals and to another one to play solo on top of it, would be a salvation and a motor for musical creation. 

### How are you planning to incorporate IPFS into your work? (max 250 words)
I am building this app on ipfs. It's a web app that is hosted on ipfs. All the data it stores (project files and audio data) is stored on ipfs as well.  

<img src="https://github.com/felixniemeyer/jam/raw/webpack/screenshots/home.png" height="450">  <img src="https://github.com/felixniemeyer/jam/raw/webpack/screenshots/session.png" height="450">

You can 
- create a jam session, rename it
- record audio tracks, rename them
- publish the project and send the link to sb else
- with this link he can load the project and audio from ipfs and record further tracks 

### Website(s) (CV, GitHub, personal page...)
The webapp is in a working state already: 
`ipfs://bafybeighc72fdo454nbaw5wkegw2k6vtmw2c27gbpoiypfhwb4dxtbkgbm` 
You're welcome to try it out! 

### Will the work be Open Source? 
It is open source: https://github.com/felixniemeyer/jam/tree/webpack
MIT license

### Does your proposal comply with our Community Standards?
I think so.

### expert help

I could use some ipfs expert help about how to reduce file loading times. I've read about delegate nodes and I think setting one up may be a good solution to make fresh audio recordings & projects well available until they become wider spread in the network. That's an issue especially when people are running a node in their browser only... Once they close it, their recordings might be gone.

**Comment by parkan** [comment]
hi @felixniemeyer, our grant applications are currently on hold while we restructure the org, but I really like this project -- I'll update you once we're back up to speed in the coming weeks

**Comment by mishmosh** [comment]
hi @felixniemeyer, apologies for the delay. our grant process is back up and running, with some small tweaks to the program which you can read at https://github.com/ipfs/devgrants/blob/master/MICROGRANTS.md.

are you still working on this jam app, and if so are you interested in being considered?

**Comment by felixniemeyer** [comment]
Hi @mishmosh, 
thanks for your notification!
Yes, I am still working on a-jam and I am interested in being considered for a microgrant.  
I have already added a-jam to the IPFS Community Showcase.  
Kind regards!

**Comment by mishmosh** [comment]
Hi @felixniemeyer - Good news, this microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
