### ISSUE TITLE
[MICROGRANT] Evido(Journalist's Diaries)

### ISSUE THREAD

**Issue by Adithya-adi-Menon** [ipfs/devgrants#81]
### 1. What is your project? (max 100 words)

One of the biggest risks faced by journalists is that their content can be manipulated and controlled by those in high power. Even if they try to publish pieces of evidence through various centralized sources, they are tracked down and suppressed. The truth never sees the light.

We provide a decentralized platform for journalism providing anonymity to journalists who wish to relinquish the true evidences and facts through our 'Evido'.

https://github.com/Adithya-adi-Menon/ipfs-evido
  

Will be updated later
![Screenshot 1](https://media.discordapp.net/attachments/853989819206074382/854407595023663174/Screenshot_11.png?width=1046&height=589)
![Screenshot 2](https://media.discordapp.net/attachments/853989819206074382/854407605941960754/Screenshot_12.png?width=1046&height=589)
![Screenshot 3](https://media.discordapp.net/attachments/853989819206074382/854407607757701152/Screenshot_13.png?width=1046&height=589)
![Screenshot 4](https://media.discordapp.net/attachments/853989819206074382/854407612275884062/Screenshot_14.png?width=1046&height=589)

### 2. How are you planning to improve this project? (max 200 words)

We will be trying to complete the project within the next 30 days and then try to document and deploy it to know the shortcomings.  We will try to enhance the user interface and experience in the first week. In the second and third weeks, we will complete the backend and IPFS functionalities. In the fourth week, we will be testing our application for bugs and get ready for deployment.
 
### 3. Will the work be Open Source?

Yes, the project will be MIT licensed.

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

Yes, we are planning to release a blog on our project after completing the project.
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes.

### 6. Links and submissions
  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
  https://github.com/ipfs/community/blob/master/projects/Evido.md

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 
 Yes.
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
Yes
### Additional questions:
*Team Members : 
 - Adithya Menon S - Backend Development - https://github.com/Adithya-adi-Menon/
 - Vasanth T - Frontend Development-https://github.com/vasanthsteve23

**Comment by mishmosh** [comment]
Thank you for the submission! We review these every 2 weeks, so you can expect to hear from us soon after June 29.

**Comment by mishmosh** [comment]
Hi @Adithya-adi-Menon, before we can consider this microgrant application, section 6 needs to be completed. Can you update your original issue comment and ping here when done?

As you build Evido you might be interested to read about SecureDrop, a web2 whistleblower document submission platform.

```
### 6. Links and submissions
<!-- Complete each step, and include the link of the published submission (or "Yes" if there is no URL) -->
  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
  <!-- Once your PR is merged, include the link here -->

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? <!-- Submit the form, then change this text to "Yes" -->
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
 ```

**Comment by Adithya-adi-Menon** [comment]
Hi , I have updated 

Thank You

**Comment by ErinOCon** [comment]
Closed Issue as grant was approved and sent in 2021. Please feel welcome to reopen issue or email with any questions!
