### ISSUE TITLE
[MICROGRANT] The Convo Space

### ISSUE THREAD

**Issue by anudit** [ipfs/devgrants#82]
### 1. What is your project? (max 100 words)

Convo aims to be the Decentralized Conversation Layer of Internet, helping reduce interaction/conversation cost and is a substrate that connects conversations and communities across the Internet independent of the Interface and always owned by the users.

  
[Github](https://github.com/anudit/convo)
[Website](https://theconvo.space)
[Docs](https://docs.theconvo.space)

### 2. How are you planning to improve this project? (max 200 words)

 - Scaling up operations to onboard the next thousand users.
 - Building a Refreshed Dashboard Interface that works on all platforms and support a dynamic overview of your conversations across the Internet.
 - Allow users to backup their data to Filecoin.
 - Integrate services like Ocean Protocol to help users monetize their data on Filecoin.
 - Package Convo into a  React Component to allow any application to natively integrate Convo.
 - Overhaul Docs for a better Developer Experience.
 - An improved Query Aggregation Engine allowing developers to aggregate conversations from across the Internet.

### 3. Will the work be Open Source?
Yes under the [MIT LICENSE](https://github.com/anudit/convo/blob/main/LICENSE.md)

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?
**Yes**

### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
[https://github.com/ipfs/community/blob/master/projects/The%20Convo%20Space.md](https://github.com/ipfs/community/blob/master/projects/The%20Convo%20Space.md)

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 
**Yes**
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  - [Web3Weekend Submission](https://showcase.ethglobal.co/web3weekend/the-convo-space)
  - [Featured in IPFS blog](https://blog.ipfs.io/2021-06-08-web3-weekend)

* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
**Yes**
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

**Anudit Nagar**
Email: nagaranudit@gmail.com
Github: @anudit
Position: Full Stack Developer

* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
  Web3Weekend
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.
     - [Web3Weekend Submission](https://showcase.ethglobal.co/web3weekend/the-convo-space)
     - [Featured in IPFS blog](https://blog.ipfs.io/2021-06-08-web3-weekend)

**Comment by mishmosh** [comment]
Thank you for the submission! We review these every 2 weeks, so you can expect to hear from us soon after June 29.

**Comment by mishmosh** [comment]
Hello @anudit — Good news, this microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
