### ISSUE TITLE
[MICROGRANT] Codework NFT

### ISSUE THREAD

**Issue by ysongh** [ipfs/devgrants#83]
### 1. What is your project? (max 100 words)

A dapp where users can post the requirements for building their website and developers can find work.  Developers can upload their codes, which is stored on IPFS.  Users can see a preview of the developers's codes on a web page.  Users can make a purchase for the code.

https://github.com/ysongh/Codework-NFT

https://codeworknft.netlify.app/

### 2. How are you planning to improve this project? (max 200 words)

- Adding more features and improving UI
- Add a feature where developers can sell their codes as NFT
- Add custom domain name
- Deploy the contracts to the mainnet

### 3. Will the work be Open Source?

Yes

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?

Yes

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 

Yes
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

https://showcase.ethglobal.co/web3weekend/codeworknft

* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 

Yes

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

**Name:** You Song Hou

**Email:** yousonghou@gmail.com

**Github account:** ysongh

**Role:** Full Stack Developer

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  
  Web3 Weekend

  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.
  
  https://showcase.ethglobal.co/web3weekend/codeworknft

**Comment by mishmosh** [comment]
Hey @ysongh - this microgrant has been approved! Look out for an email to submit payment details. Please use your existing Community Discussion thread for updates.
