### ISSUE TITLE
Next Step Microgrant: DBS-Decentralized Broadcast & Stream

### ISSUE THREAD

**Issue by optimus789** [ipfs/devgrants#84]
### 1. What is your project? (max 100 words)

Integrating Live Stream for Audius music Creators- Decentralized Broadcaster Streamer
There are various music creators on Audius, this is a decentralized platform for audio creators. 
This project focuses on live streaming, concerts for those music creators. It is a platform which allows user to create his/her live stream for which people have to get a pass to watch. 
We have implemented Unlock protocol such that users would need to pay a certain amount to our streaming platform so that they can get access to new content or concerts hosted by their favourite independent creators. 

  https://github.com/Rishikeshk9/DBS-Decentralized-Broadcaster-Streamer

https://bafzbeic2l4q6n7ecxhbqg64hqpweo7h4bhczjkqgmfyaj4zmblpnvobfqe.textile.space/
https://youtu.be/RGCnPxr1PNc

### 2. How are you planning to improve this project? (max 200 words)

We are going to implement NFT drops while live streaming and will be using IPFS to store the metadata for the same.
Work on storing the live stream for future viewers as an on-demand video on IPFS. Major UI improvement to increase the user base and onboard a wide range of age groups easily on our platform. Implementing Super-Chats functionality for viewers watching the stream.
 
### 3. Will the work be Open Source?

Yes, It will be

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

Yes, we agree
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes, Our proposal comply with your Community Code of Conduct.

### 6. Links and submissions

https://showcase.ethglobal.co/web3weekend/dbs-decentralized-broadcast-stream
  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
  Yes
  
 
* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 
Yes
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  Yes

* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
Yes
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project. 
[Rushikesh Kardile](https://github.com/Rishikeshk9) - CEO, SuperSapiens

[Vinay Sudrik](https://github.com/optimus789) - Developer

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
   ETHGlobal  Web3Weekend
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.
   https://showcase.ethglobal.co/web3weekend/dbs-decentralized-broadcast-stream

**Comment by mishmosh** [comment]
Hey @optimus789 - This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.

**Comment by vinays-bst** [comment]
@mishmosh Thank You So Much for giving us a chance to work on this, we have so many things which we are going to add as soon as possible.

**Comment by optimus789** [comment]
Thank You, so much for this opportunity.
@Rishikeshk9 is the project leader
email : rushikeshkardile9@gmail.com
Please keep him in the cc too.

**Comment by optimus789** [comment]
Linking @Rishikeshk9 to this issue
