### ISSUE TITLE
[MICROGRANT] a-jam: a collaborative multitrack recorder for musicians

### ISSUE THREAD

**Issue by felixniemeyer** [ipfs/devgrants#85]
### 1. What is your project? (max 100 words)
a-jam is a collaborative multitrack recorder for musicians in a web app that builds on IPFS. 
It allows musicians to easily record audio with their PC or mobile phone. Tracks can be recorded one by one building up to a entire song with guitar tracks, a voice track, keys, percussion, and so on. Different musicians can take turns in adding recordings and sharing the results back and forth. It's a bit like jam sessions but round based: asynchronous jams!    

  

### 2. How are you planning to improve this project? (max 200 words)
Users generate data using the web app. This data is stored on ipfs through a js-ipfs node running in the browser. When sharing their projects with others via links, a js-ipfs node running in other persons browser loads the data that has previously been pinned by the former user. The loading of these ipfs resources takes so long, that sharing jam sessions is unusable.

I am planning to implement a solution that accelerates the transfer of pinned content from one js-ipfs node to another. Ideas are: 
- using pinning services that are configured to allow websocket connections 
- setting up a-jam dedicated pinning service 

There is also [a file with a tree of features](https://github.com/felixniemeyer/a-jam/blob/main/issues) that I am working on. 

 
### 3. Will the work be Open Source?

It already is open source: [a-jam LICENSE](https://github.com/felixniemeyer/a-jam/blob/main/LICENSE)

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

Yes, I would like to give updates weekly and write a final report. 
I am happy to connect with the IPFS community.  
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?

  https://github.com/ipfs/community/blob/master/projects/a-jam.md

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? Yes
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 

  I think this does not apply to me. I did not participate in any event accelerator. 
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project
  * Felix Niemeyer
    * niemeyer.felix@gmail.com
    * https://github.com/felixniemeyer
    * developer
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.

**Comment by mishmosh** [comment]
Hi @felixniemeyer - Good news, this microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
