### ISSUE TITLE
[MICROGRANT] InterPlanetary File System for Business (IPFSfB)

### ISSUE THREAD

**Issue by feliciss** [ipfs/devgrants#86]
### 1. What is your project? (max 100 words)

InterPlanetary File System for Business (IPFSfB) is based on InterPlanetary File System, which aims to provide an enterprise form, unstructured data storage network for any blockchain and it’s intended to help developers to build their private network on IPFS, leveraging the capability that enabling private storage for any blockchain.

Inspired by the build your first network (BYFN) sample from Hyperledger Fabric, IPFSfB is built with Docker and Docker Compose to start up quickly on any platform or computer and enables them to run distributed and private storage networks in enterprise form where any blockchain can store unstructured data.

 
https://github.com/feliciss/IPFSfB

https://developer.ibm.com/patterns/build-first-private-blockchain-network-interplanetary-file-system

### 2. How are you planning to improve this project? (max 200 words)

 
1. Supporting the latest feature of IPFS Web UI and make it private by pulling the latest IPFS Web UI CID and handle necessary config checkout to private host. For example, a private Web UI should have enabled:

      - Download and upload content from/to the private network.
      - Share content by custom private gateway or DNS. e.g., ipfs.io.
      - Browse CID hash on the private network.

2. Upgrade the current version of IPFS to 0.9 or above. Make unit and integration tests and CI/CD running on it to ensure productivity.
 
3. If necessary, migrate current architecture from go-ipfs to ipfs-cluster to improving data redundancy and availability for private network on IPFS.
 
4. If necessary, migrate the current bootstrap from Docker and Docker-Compose to Ansible script for starting a private network on IPFS.

### 3. Will the work be Open Source?

All work will be open-sourced with the MIT license.

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

  
Yes.

### 5. Does your proposal comply with our Community Code of Conduct?

Yes.

### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
  

  https://github.com/ipfs/community/blob/master/projects/IPFSfB.md

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 

  Yes.
 
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
  https://hackerlink.io/en/buidl/465?roundProj=465
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
  
  Yes.

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

  - Name: Feliciss
  - Email: fiveswind@gmail.com
  - GitHub account: @feliciss
  - Role in the project: Project owner

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)

    HackerLink Filecoin Grant 1

  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.

    https://hackerlink.io/en/buidl/465?roundProj=465

**Comment by mishmosh** [comment]
Hey @feliciss - this microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
