### ISSUE TITLE
[MICROGRANT] PassVault

### ISSUE THREAD

**Issue by hackyguru** [ipfs/devgrants#87]
### 1. What is your project? (max 100 words)
PassVault is a browser extension built with Inter Planetry File System. Users can use their seed phrase to login their account and view their saved credentials. PassVault was built considering security as the #1 priority and is better than most of the traditional password managing methods.

https://github.com/hackyguru/PassVault

### 2. How are you planning to improve this project? (max 200 words)
We are planning to add more features in the chrome browser extension and polish the UI. We are also looking to test it using Browser stack and make a firefox ad on for the same. At the end, we will also publish a detailed blog/ documentation about our project.

### 3. Will the work be Open Source?
PassVault is licensed with MIT license for code or [CC-BY-SA 3.0](https://ipfs.io/ipfs/QmVreNvKsQmQZ83T86cWSjPu2vR3yZHGPm5jnxFuunEB9u) license for content.

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Yes.

### 5. Does your proposal comply with our Community Code of Conduct?
Yes.

### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
https://github.com/ipfs/community/pull/596

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? Yes
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
  Yes
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Kumaraguru T
Full stack web developer and blockchain enthusiast
https://github.com/hackyguru/
kumaragurut7@gmail.com

Mridula Kalaiselvan
Front end developer
https://github.com/Mridula90/
19eucs094@skcet.ac.in

Emma Thomas
UI/UX designer
https://github.com/Emma-Thomas-jj
19eucs034@skcet.ac.in

* If your project was created as part of an event or hackathon: No

**Comment by mishmosh** [comment]
@hackyguru Thank you for your submission! Can you complete the additional info questions?

> For each team member(s), please list name, email, Github account, and role in the project.
> If your project was created as part of an event or hackathon:
> What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
> Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize

**Comment by hackyguru** [comment]
@mishmosh Oops, sorry we missed it out. I've edited the message with the information required.

**Comment by mishmosh** [comment]
Hey @hackyguru - this microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
