### ISSUE TITLE
[MICROGRANT] 4EVERLAND

### ISSUE THREAD

**Issue by cryptobuffer** [ipfs/devgrants#89]
### 1. What is your project? (max 100 words)
4EVERLAND is a Web3.0 cloud computing platform with global acceleration, privacy protection, distributed storage and other technical features.

Github: [https://github.com/4everland](https://github.com/4everland)
  
Website: [https://4everland.org](https://4everland.org)

### 2. How are you planning to improve this project? (max 200 words)
- Build decentralized gateway for IPFS
- Distributed PIN with global multi-node storage
- TEE-based Proof of Storage Challenge (PoSC)
 
### 3. Will the work be Open Source?
YES, 4EVERLAND is licensed with MIT license for code or CC-BY-SA 3.0 license for content. 

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Yes.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes.

### 6. Links and submissions
  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
  Yes, https://github.com/ipfs/community/pull/591

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)?
Yes.

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
No.
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
Yes.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

  **Name**: Clarence
  **Role**: Core Team Developer|Full Stack Engineer
  **Email**: qwertyhqwerty475@gmail.com
  **Github**: @cryptobuffer
  
  **Name**: Thloyi
  **Role**: Core Team Developer|4EVER-Hosting Architect
  **Email**: tfspq@protonmail.com
  **Github**: @thloyi
  
  **Name**: Saullary
  **Role**: Core Team Developer|Front End Developer
  **Email**: saullarytzc94@gmail.com
  **Github**: @saullary

* If your project was created as part of an event or hackathon: No
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.

**Comment by mishmosh** [comment]
Hi @cryptobuffer, thank you for this application. One of the [Program Qualifications](https://github.com/ipfs/devgrants/blob/master/MICROGRANTS.md#program-qualifications) is that you are applying on behalf of a project you have already started building with IPFS or related technologies. I only see a Github link for the website. Can you include a link to the underlying software project?

**Comment by cryptobuffer** [comment]
@mishmosh Our project is still under development. Some modules have been submitted to https://github.com/4everland in the past week. More modules will be submitted to this repo in the coming weeks. Here are some useful links:

- Official website: https://4everland.org
- Whitepaper ( Our Blueprint will be based on this paper ) : https://www.4everland.org/4everland-whitepaper-en(Draft%20V0.0.2).pdf
- @4everland/cluster-cli ( A command line to upload content to IPFS cluster ) : https://github.com/4everland/4ever-cluster-cli
- 4ever-name-server ( A plugin of CoreDNS ) : https://github.com/4everland/4ever-name-server

We will update our progress and the latest open source projects in the community discussion

**Comment by realChainLife** [comment]
Hi @cryptobuffer We would like to fund the work outlined in this proposal. Can you email grants@filecoin.org so we can discuss next steps.

**Comment by realChainLife** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.

**Comment by ErinOCon** [comment]
Closed Issue. Grant approved and sent in 2021.
