### ISSUE TITLE
[MICROGRANT] Esteroids

### ISSUE THREAD

**Issue by eyalron33** [ipfs/devgrants#92]
### 1. What is your project?
Esteroids is a tool for the Web3 community to discover ENS+IPFS. Made by the community - for the community. 

We want Esteroids to be a combination of an early day Yahoo directory with a search engine, made in a modern way to fit the decentralized web.

Esteroids has two functionalities. One is an explorer for users to discover new and popular ENS+IPFS websites, while the other is an option to search in our ENS+IPFS websites database.

We update esteroids.eth hourly with new ENS+IPFS websites.

Besides the esteroids.eth website we also have a [Twitter account](https://twitter.com/e_steroids), announcing all new ENS+IPFS websites as they are created.

Check our website at http://esteroids.eth (with Brave) or http://esteroids.eth.link (in other browsers).

We will have a Github link once we open source it in the next stage.

### 2. How are you planning to improve this project?
We ask for a microgrant to pay a designer to improve esteroids.eth.

While we handle the technical side of the project on our own, we need aid with design. The funds will go to a designer for creating a logo, graphics and UX design for esteroids.eth.link.

If any budget is left we will use it to cover our server expenses (so far we pay for everything from our own pockets).
 
### 3. Will the work be Open Source?
Yes, we will release the artwork and code funded by the grant under CC-BY-SA 3.0 license and MIT license correspondingly.

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Yes.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes.

### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase?
  https://github.com/ipfs/community/blob/master/projects/Esteroids.md

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 
  Yes.
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  No.
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
Yes.
  
### Additional questions:
We are a team of two people:

- **Name**: Eyal Ron
  **Email**: eyal@esteroids.xyz
  **Github**: https://github.com/eyalron33/
  **Role**: Algorithms, communications, business development.
  
- **Name**: Tomer Leicht
  **Email**: tomer@esteroids.xyz
  **Github**: https://github.com/tomlightning/ 
  **Role**: Main developer, business development.

**Comment by eyalron33** [comment]
I see the status changed to "seeing addition info", is there anything we need to do?

**Comment by SeedingTrees** [comment]
> I see the status changed to "seeking addition info", is there anything we need to do?

Thanks, Eyal.  I sent you and Tomer an email starting a conversation regarding this additional information.  Please let me know if my email does not come through.

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
