### ISSUE TITLE
[MICROGRANT] CryptoSouls

### ISSUE THREAD

**Issue by junoware** [ipfs/devgrants#94]
### 1. What is your project? (max 100 words)

CryptoSouls is an NFT minting and battling game. In it, souls of famous warriors can be minted as NFT's, complete with a set of 5 stats: Strength, Intelligence, Endurance, Charisma, and Luck. IPFS is used for the NFT token data and assets.

Players can enlist their CryptoSouls in the Battle Arena, where they're matched up against other CryptoSouls. Battles consist of 3 rounds of random stat matchups, with the warrior having the higher stat the victor!

https://github.com/junoware/cryptosouls

### 2. How are you planning to improve this project? (max 200 words)

With this grant, I'm planning on getting CryptoSouls to mainnet as a public-facing release. There will need to be general improvements to the smart contracts and specific fixes for the battle mechanics (that are already underway). In addition, the website needs a lot of work from a UI and UX perspective. Part of the grant would be used for UI design and additional visual assets, which it's currently lacking. My overall goal with this grant is to have a completed, launched product.

### 3. Will the work be Open Source?

Yes

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
 
Yes

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)?

Yes
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

CryptoSouls won a Protocol Labs prize at the ETHGlobal Web3Weekend hackathon. If that counts towards the relevant Protocol Labs prizes, then yes. -- https://showcase.ethglobal.co/web3weekend/cryptosouls
  
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)?

Yes
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Name: Yambo
Email: yambo.eth@gmail.com
Github: https://github.com/junoware
Role: Designer, Developer, Project Manager

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) -- ETHGlobal Web3Weekend
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize. -- https://showcase.ethglobal.co/web3weekend/cryptosouls

**Comment by realChainLife** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.

**Comment by ErinOCon** [comment]
Closed Issue. Grant approved and sent in 2021.
