### ISSUE TITLE
Next Step Microgrant:HubShare

### ISSUE THREAD

**Issue by bkyogesh28** [ipfs/devgrants#95]
### 1. What is your project? (max 100 words)
 * Hub Share is a secure and decentralized file sharing web application built with JS-IPFS.Hub Share stores the files in IPFS and encrypts the link to the file with an cryptographic algorithm. This makes the file storage secured, private and immutable. IPFS plays a major role here as our novelty totally relies on it.

 ### GitHub Repo
  https://github.com/bkyogesh28/HubShare

### Demo Link
 https://youtu.be/XDOaD5jdPV4
### 2. How are you planning to improve this project? (max 200 words)
   This project uses JS-IPFS.We are planning to add more features and deploy the application for users.The things we are going in the first phase is to enhance the frontend and the UI. The backend code is to be re-factored more to give a clean code and functionality.The Second phase will undergo Analysis of the application.We are going to do this things in next 20 days.
 
### 3. Will the work be Open Source?

  Yes this application is open source and it is open to contributors.

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

  Yes we will give weekly updates on time.Our project is 60% completed and it is in the enhancement stage. 
### 5. Does your proposal comply with our Community Code of Conduct?

      Yes
### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
  
  https://github.com/ipfs/community/blob/master/projects/HubShare.md

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 
  Yes
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
   https://showcase.ethglobal.co/hackmoney2021/yogeshwar-b-k
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
  Yes
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
### 1. Yogeshwar B K 
              Email: bkyogesh28@gmail.com
              GitHub: https://github.com/bkyogesh28
### 2. Jawahar P M
             Email:jawahar002tp@gmail.com
             GitHub:https://github.com/Jawaharpmm

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  
             ETHGlobal
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.
             https://showcase.ethglobal.co/hackmoney2021/yogeshwar-b-k

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
