### ISSUE TITLE
[MICROGRANT] Juni::Db

### ISSUE THREAD

**Issue by MikeMS-sys** [ipfs/devgrants#96]
### 1. What is your project? (max 100 words)

It's a very highload action to store large amounts of data on-chain. The most-common and useful solution for decentralised apps is to use IPFS as a data storage and store on-chain only hashes. Our team, inspired by the OrbitDB, focuses on the scalability, decentralised, easy-learning solution. We work on the development of the configurable database module that allows users to store and manipulate a big amount of data.

#### Key advantages

Usability - just integrate and 

Code Security - built-in encryption 

Scaling - ready for changes and big data

#### Available storage data types

Key-value - simple key-value storage 

Hash - hash storage like Redis hash

[Link to Github repo](https://github.com/uddugteam/juniDB)

### 2. How are you planning to improve this project? (max 200 words)

Estimated Duration: 2 month

1. Implement an encryption module to allow encrypt and decrypt needed data out of the box.
2. Update web application to interact with the encryption system.
3. Documentation of the code and complex quality assurance.
 
### 3. Will the work be Open Source?

Prefer GNU GPL v3, but may choose MIT.

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?

 Yes

### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
  

https://github.com/ipfs/community/blob/master/projects/Juni::Db.md

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 
  
Yes
 
* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
  
No, we did't participate as part of a recent hackathon or accelerator.

But we had experience of building with IPFS. Actually we used IPFS stack within development process for different nft projects, for example [Snark.art](https://snark.art).

Presented project Juni::Db uses IPFS for data storage.
And another own project "Health Consul" also uses IPFS for data storage.

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

 Tech lead, backend: Andrew Skurlatov

 https://github.com/andskur

 https://www.linkedin.com/in/andrew-skurlatov/

 Junior back-end developer: Sergey Grachev

 https://github.com/Misnaged

 https://www.linkedin.com/in/painof-donbass-b07187206/

 Head of product: Mike Manko

 https://github.com/MikeMS-sys

 https://www.linkedin.com/in/mikhail-manko-97a491a2/

 DevOps: Ivan Podcebnev

 https://github.com/naykip

 https://www.linkedin.com/in/naykip/

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.

**Comment by MikeMS-sys** [comment]
Hi @SeedingTrees!

Oh great, thank you. I will provide access to the product specification for grants team.
There was a question about licensing: We prefer GNU GPL v3, but may choose MIT. Whats better to use?

**Comment by SeedingTrees** [comment]
Thanks for the question, MikeMS.  Please see the repo here
<https://github.com/filecoin-project/devgrants#license>.  For licenses, it
says:

The Filecoin Project is dual-licensed under Apache 2.0 and MIT terms:

   - Apache License, Version 2.0, (LICENSE-APACHE
   <https://github.com/filecoin-project/devgrants/blob/master/LICENSE-APACHE>
    or http://www.apache.org/licenses/LICENSE-2.0)
   - MIT license (LICENSE-MIT
   <https://github.com/filecoin-project/devgrants/blob/master/LICENSE-MIT>
    or http://opensource.org/licenses/MIT)

All Filecoin dev grant projects are open sourced and also use these
licenses.


[image: Logo]

Hunter Treseder

Senior Fellow for Social Impact

Filecoin Foundation & Filecoin Foundation for the Decentralized Web

✆: (415) 570-9164

Fil.org <https://fil.org>
