### ISSUE TITLE
[MICROGRANT] NiftySubs

### ISSUE THREAD

**Issue by therealharpaljadeja** [ipfs/devgrants#98]
### 1. What is your project? (max 100 words)
NiftySubs is a "Pay-as-you-watch" decentralized livestreaming platform. NiftySubs leverages IPFS pubsub for chatting alongside the livestream. Livestream functionalities are provided by Voodfy which leverages Filecoin and LivePeer. NiftySubs stores all the data like video IDs, video creator, and many other attributes on Textile ThreadDB.

Github:- https://github.com/NiftySubs/niftysubs

Website:- https://niftysubs.com/

### 2. How are you planning to improve this project? (max 200 words)

- NiftySubs is an infinitely scalable platform.
- We plan to add NFT features where creators can create moment NFT's and lootboxes, we plan to use nft.storage for that. 
- Furthermore we plan to use Textile User mailboxes for establishing a notification system for users.

 
### 3. Will the work be Open Source?
Yes

### 4. If selected, do you agree to complete weekly updates and a grant report upon conclusion?
Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions

  
* Have you submitted to the IPFS Community Showcase ([instructions](https://github.com/ipfs/community/blob/master/README.md#showcase-your-project))?
 [IPFS Community Showcase Link](https://github.com/ipfs/community/blob/master/projects/NiftySubs.md)

* Have you added your project to the [IPFS Ecosystem Directory](https://airtable.com/shrjwvk9pAeAk0Ci7)? 
Yes
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  [HackMoney 2021](https://showcase.ethglobal.co/hackmoney2021/niftysubs)

* Have you filled out the [Interplanetary Builder Feedback Survey](https://airtable.com/shrDZMizx03jOa4mQ)? 
   Yes
  
### Additional questions:
For each team member(s), please list name, email, Github account, and role in the project.
 
- **Name**: Harpalsinh Jadeja
 **Email**: [jadejaharpal14@gmail.com](mailto:jadejaharpal14@gmail.com)
 **Github**: [threalharpaljadeja](https://github.com/therealharpaljadeja)
 **Role**: Full Stack Developer

- **Name**: Elio Jordan Lopes
**Email**: [lopeselio@gmail.com](mailto:lopeselio@gmail.com)
**Github**: [lopeselio](https://github.com/lopeselio)
**Role**: Developer.

- **Name**: Huy Vu Nguyen
**Email**: [hv.ng@outlook.fr](mailto:hv.ng@outlook.fr)
**Github**: [skudskud](https://github.com/skudskud)
**Role**: Designer.

- **Name**: Sushant Kumar
**Email**: [sushantkumar23@gmail.com](mailto:sushantkumar23@gmail.com)
**Github**: [sushantkumar23](https://github.com/sushantkumar23)
**Role**: DevOps.

- **Name**: Rishabh Keshan
**Email**: [rishabhkeshan@gmail.com](mailto:rishabhkeshan@gmail.com)
**Github**: [rishabhkeshan](https://github.com/rishabhkeshan)
**Role**: Frontend Engineer.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  **ETHGlobal HackMoney 2021**
  
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.
  [HackMoney 2021 Showcase](https://showcase.ethglobal.co/hackmoney2021/niftysubs)

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
